### ISSUE TITLE
mapping ellenőrzés berakása utcákhoz is

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1008]
#784 as funkciót kérném a további utcák és a hiányzó utcák aljára is. 
Az alap probléma, hogy budapest_02-nél nincsen hiányzó házszám oldal így nem látszik, hogy a Díszfű utca mapping rossz.

**Comment by vmiklos** [comment]
Megoldható.

**Comment by vmiklos** [comment]
Lehet tesztelni, pl itt:

https://osm-gimmisn.vmiklos.hu/osm/missing-streets/budapest_16/view-result

**Comment by vasony** [comment]
Ez jó.
Olvastam valamelyik commentben, hogy van összesített lista?

**Comment by vmiklos** [comment]
Parancssorban van: ./invalid_refstreets.py
Arra csináltam, hogy találjak relaciot ahol van kimenete a hibalistanak :)

**Comment by vasony** [comment]
És ki lehet tenni felületre, nyissak issuet? :)

**Comment by vmiklos** [comment]
Persze, ki lehet
