### ISSUE TITLE
mapping ellenőrzés összes reláció 1 helyen felületre

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1025]
#1008 
>Parancssorban van: ./invalid_refstreets.py
>Arra csináltam, hogy találjak relaciot ahol van kimenete a hibalistanak :)

**Comment by vmiklos** [comment]
Lehet róla szó.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/invalid-refstreets

Magyarítás kell még

**Comment by vasony** [comment]
Egy dolog kellene még, a terület neve legyen kattintható, pl. biatorbagy vezessen a /missing-housenumbers/biatorbagy/ oldalra

**Comment by vasony** [comment]
Az osm/referencia szövegezés nem jó. mert szerintem már az átmappelt utcaneveket veszi figyelembe, nem az eredetit.

Pl. Biatorbágy:

  'Juhász Gyula utca': 'Juhász Gyula út'

Figyelem: sérült OSM <-> **referenia** hozzárendelés, a következő referencia nevek érvénytelenek:

    Juhász Gyula út

- Valójában a referenciában és az osm-en is Juhász Gyula út szerepel, azt vártam volna, hogy osm névre panaszkodik, mert valójában az a rossz, nem a referencia oldal, de a mappelés miatt ugye a referencia nevet megváltoztatta. 
- El van írva: referenia -> referencia 

Ha túl bonyolult az eredeti halmazon futtatni, akkor simán csak meg kell cserélni a 2 szöveget.

**Comment by vmiklos** [comment]
'Juhász Gyula utca' (osm) <-> 'Juhász Gyula út' (ref) az összerendelés. A warning azt írja, hogy a 'Juhász Gyula út' mint ref név invalid. A ref név attól invalid, hogy szerepel az osmben. (Az osm név meg attól lenne invalid, ha nem szerepel az osmben.) Szóval ez alapvetően úgy működik, ahogy beszéltük. Esetleg érdemes valahol ezt explicite leírni, hogy mitől invalid, hogy ne az eredeti issue-ból kelljen kitúrni. Például:

> Warning: broken OSM <-> reference mapping, the following reference names are invalid (reference name exists in OSM):

Alfeladatok:

1. linkesítés
2. szöveg bővítése, hogy mit jelent az invalid osm vagy ref név
3. elírás a létező magyarításban
4. magyarítás

**Comment by vasony** [comment]
> Juhász Gyula utca' (osm) <-> 'Juhász Gyula út' (ref) az összerendelés. A warning azt írja, hogy a 'Juhász Gyula út' mint ref név invalid. A ref név attól invalid, hogy szerepel az osmben. 


ja tényleg... akkor tényleg a szövegen kell változtatni

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
ok
