### ISSUE TITLE
hiányzó utcák frissítése nem működik

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1033]
https://osm-gimmisn.vmiklos.hu/osm/missing-streets/budapest_22/view-result

Az Arany János út nem jelenik meg mint hiányzó, frissíteni kellene, de nem frissül a "frissítés referenciából" menüpontra, se a "frissítés osmből" menüpontra. cronból viszont jó.

így kellene kinéznie:
https://osm.vasony.hu/missing-streets/budapest_22/view-result

**Comment by vmiklos** [comment]
Azt várnám, hogy azért nem jelenik meg, mert van egy Arany János utca (osm) <-> Arany János út (ref) hozzárendelés, és mivel utca van osmen, így az út nem minősül hiányzónak. Ha ez így van, akkor ez nem hiba. Vagy valami részlet felett elsiklottam?

**Comment by vasony** [comment]
budafokban van filter itt nincs. ez csak frissítési gond, mert nálam jó.

**Comment by vmiklos** [comment]
Ez azért lesz, mert a házszám listából is nézzük az utcaneveket. Ha workaroundolok, hogy https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_22/view-result -> update from osm, akkor már jó. Mi legyen a megoldás, ha a missing streets oldalon rámész, hogy "update from osm", akkor frissítsük osmból ne csak az utcákat hanem a házszámokat is?

onUpdateOsmStreets() main.ts-ben végülis megoldhatja.

**Comment by vasony** [comment]
igen, akkor legyen ez

**Comment by vasony** [comment]
a nehezítés ugye az volt, hogy nincs kivezetve a 22. kerületnél a hiányzó házszám, mert ki van kapcsolva.

**Comment by vmiklos** [comment]
Lehet tesztelni, eddig a workdir/street-housenumbers-budapest_22.csv timestamp nem változott, most meg kell, hogy változzon.

**Comment by vasony** [comment]
nálam nem változott meg a timestamp

**Comment by vmiklos** [comment]
bundle.js checksumja egyezik nálad meg nálam? Ilyesmire gondolok, hogy a webhook után nálad esetleg előbb indult a bundle.js letöltés, mint hogy nálam elkészült az új.

**Comment by vasony** [comment]
megnézem újra, azóta volt egy commit

**Comment by vasony** [comment]
igen, most már jó a timestamp
