### ISSUE TITLE
Filter ellenőrzés osm utcákhoz

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1048]
Csináltam egy filtert, de elírtam az utcanevet benne, ezért nem jutott érvényre.
Ezt is lehetne ellenőrzőnél. hogy az utca ami a filterben szerepel, szerepel-e az osm utcák között:

rakospalota-oregfalu tesztelhető, benne hagytam a rosszat is:

rossz:
```
  Battyhány utca:
    invalid: ['9b', '13', '20a', '26a', '28', '31a', '35b', '40a', '51a']
    ranges:
      - {start: '1', end: '51'}
      - {start: '2', end: '56'}
```
jó
```
  Batthyány utca:
    invalid: ['9b', '13', '20a', '26a', '28', '31a', '35b', '40a', '51a']
    ranges:
      - {start: '1', end: '51'}
      - {start: '2', end: '56'}
```

**Comment by vmiklos** [comment]
Lehet róla szó. Kicsit szerencsétlen ez a https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/invalid-refstreets részeként, mert ez nem igazán az osm-ref nevek összerendeléséről szól, de talán oda a legegyszerűbb berakni.

Validátorba lenne a legjobb, de a validátor csak a formátumot nézi, nincs alatta adat (se OSM, se ref), így ott nem megoldható.

**Comment by vasony** [comment]
Lehet, hogy akkor kicsit általánosabban kellene funkciót hívni, pl. invalid-filters és akkor nem zavarna az invalid-refstreets

**Comment by vmiklos** [comment]
Jó ötlet, azt hiszem invalid-relations lesz a neve.

**Comment by vmiklos** [comment]
Talált mindenfélét: https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/invalid-relations

Lehet tesztelni

**Comment by vasony** [comment]
A legtöbb hiba a ranges: [] az igazítások miatt már nem szükségesek. Úgy tűnik valid mind.

**Comment by vasony** [comment]
viszont a hiányzó házszámok alá nem teszi be, csak az összegfoglaló oldalra, ez direkt van?

**Comment by vmiklos** [comment]
Külön van a kettő, az összesített oldalon tesz bele h1-et, de csak akkor ha a kétfajta check közül valamelyik talál valamit. De megoldható

**Comment by vasony** [comment]
Sajnos most találtam máts is:
https://osm.vasony.hu/street-housenumbers/budaors-kertvaros/view-result#

A házszámokban nem nézi az utcát. Tűzkőhegyi utca valós, de hozza hibának

**Comment by vmiklos** [comment]
Hol hozza hibának?

https://osm.vasony.hu/missing-housenumbers/budaors-kertvaros/view-result

itt ír kettőt, de a Tűzkőhegyi utcát nem.

**Comment by vasony** [comment]
Remek, az előbb még 3 volt.

**Comment by vasony** [comment]
Kipucoltam jó lett minden, nem okoztak gondot a szűrő törlések.
