### ISSUE TITLE
Ha nincs érvénytelen mapping, akkor ne jelenjen meg a megjegyzés szöveg

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1067]
https://osm.vasony.hu/missing-housenumbers/budaors-kertvaros/view-result

>Megjegyzés: egy OSM név érvénytelen ha nem szerepel az OSM adatbázisban.Egy referencia név érvénytelen ha szerepel az OSM adatbázisban.

Ha nincs érvénytelen, akkor ne jelenjen meg a szöveg

**Comment by vmiklos** [comment]
Valóban nem volt szándékos a dolog.

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
most ok
