### ISSUE TITLE
Oldalbetöltési optimalizáció - devops

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1112]
- [ ] A HTTP 404 nincs kezelve - mindig a főoldal jön be rá.
- [ ] A favicon.ico hiányzik. Talán emiatt jelentősen lassabb a betöltés, mert a háttérben kétszer tölti be az oldalt.
- [ ] A szerver nem használ tömörítést a visszaadott lapokra és erőforrásokra (.htaccess?).
- [ ] Érdemesebb volna a JavaScript és CSS behúzást az oldal legvégére, a </body> elé rakni, mert így a <head>-ben blokkolja az első megjelenítést. Nem ellenőriztem, hogy bírja-e ezt a függvénykönyvtárad.
- [ ] Valamiért az osm.css nem mindig cache-elődik Chromiumon, míg a bundle.js igen. Utána egy idő után elkezdi, aztán mégse, de nem túl determinisztikus (talán az utolsó frissítés dátuma működik véletlenszerűen). A válasz fejlécébe érdemes volna felvenni néhány dolgot, nem tudom, hogy a frameworkod csinálja vagy a `.htaccess` (`Expires`, `max-age` `Cache-Control`) https://tools.ietf.org/html/draft-ietf-httpbis-p6-cache-13#section-2.1 https://robinroelofsen.com/browser-caching-htaccess-apache
- [ ] A következőhöz már kódolni is kell, bár nem vészesen sokat. Jelentősen csökkentené a késleltetést (300-500ms+) ha minden oldalbetöltés statikus HTML-re mutatna. Ezen belül két megoldás adódik. Vagy az adatokat JavaScripttel töltené ki, vagy optimálisabban előre ki volna töltve adatokkal, így nem is kéne lekérni. Utóbbihoz nem csak a txt-ket generálná a cron és a frissítés gomb meghívása, hanem statikus html-ként az eredményeket is. Ehhez ipari oldalakon illendő versenyhelyzet ütközések okán ehhez ideális verziózott fájlnevekre átállni, bár itt még lehet, hogy elmegy simán a felülírogatás.
- [ ] A következőhöz gyakorlatilag az egész frontendet ki kell cserélni, így nem várom el, csak érdekességként megírom, hogy lehetne progresszív egyoldalas webalkalmazás is az egész, amikor egyetlen statikus HTML-ben navigál a felhasználó és esetleg a backendről az adatokat kéregeti le vagy frissítgeti, így még a kattintásonkénti <100ms statikus oldalbetöltést is meg lehetne spórolni.

**Comment by bkil** [comment]
* [ ] Még egy olcsó alternatívaként a staticizmusig megfontolandó lehet a Python endpointok például 24 órás cache-elhetőségének beállítása is. Nem minden böngésző veszi figyelembe ezt kattintással történő elnavigációnál (például Chromium se nagyon), de például a Firefoxon tovább gyorsítana, és legalább a lehetőségét megadnánk másoknak is.

**Comment by vmiklos** [comment]
Elég sok minden van itt, szét kéne bontani az összes pipát külön issue-ra, nekem legalábbis anélkül nincs nagyon motivációm ezzel foglalkozni. :) Szétbontsam, vagy megcsinálod?

Ez azért is fontos, mert egy issue-ra csak egy confirmed vagy needs-testing labelt lehet rakni, így ha egy issue-ban két dolgot kérsz, nem egyértelmű, hogy mlyeik confirmed, tesztelendő.

De röviden:

>     * [ ]  A HTTP 404 nincs kezelve - mindig a főoldal jön be rá.

Jogos, megoldható.

>     * [ ]  A favicon.ico hiányzik. Talán emiatt jelentősen lassabb a betöltés, mert a háttérben kétszer tölti be az oldalt.

Jogos.

>     * [ ]  A szerver nem használ tömörítést a visszaadott lapokra és erőforrásokra (.htaccess?).

Ezt kicsit konkretizálni kéne, hogy pontosan milyen headerre kéne reagálnia a kódnak.

>     * [ ]  Érdemesebb volna a JavaScript és CSS behúzást az oldal legvégére, a  elé rakni, mert így a -ben blokkolja az első megjelenítést. Nem ellenőriztem, hogy bírja-e ezt a függvénykönyvtárad.

Erre van valamilyen html megoldás is, nem? html elementre attribútum rémlik, amivel lehet opt-inelni, hogy async legyen a betöltés.

>     * [ ]  Valamiért az osm.css nem mindig cache-elődik Chromiumon, míg a bundle.js igen. Utána egy idő után elkezdi, aztán mégse, de nem túl determinisztikus (talán az utolsó frissítés dátuma működik véletlenszerűen). A válasz fejlécébe érdemes volna felvenni néhány dolgot, nem tudom, hogy a frameworkod csinálja vagy a `.htaccess` (`Expires`, `max-age` `Cache-Control`) https://tools.ietf.org/html/draft-ietf-httpbis-p6-cache-13#section-2.1 https://robinroelofsen.com/browser-caching-htaccess-apache

Itt is utána kéne járni, hogy pontosan milyen headert kérsz amitől jobb lesz. 
Last-Modified van rajta, ez legutóbb lég volt, de lehet csak firefox alól néztem.

>     * [ ]  A következőhöz már kódolni is kell, bár nem vészesen sokat. Jelentősen csökkentené a késleltetést (300-500ms+) ha minden oldalbetöltés statikus HTML-re mutatna. Ezen belül két megoldás adódik. Vagy az adatokat JavaScripttel töltené ki, vagy optimálisabban előre ki volna töltve adatokkal, így nem is kéne lekérni. Utóbbihoz nem csak a txt-ket generálná a cron és a frissítés gomb meghívása, hanem statikus html-ként az eredményeket is. Ehhez ipari oldalakon illendő versenyhelyzet ütközések okán ehhez ideális verziózott fájlnevekre átállni, bár itt még lehet, hogy elmegy simán a felülírogatás.

Lehet elég lenne csak annyi, hogy a diff kimenete cache-elve legyen, abból htmlt generálni elég olcsó.

>     * [ ]  A következőhöz gyakorlatilag az egész frontendet ki kell cserélni, így nem várom el, csak érdekességként megírom, hogy lehetne progresszív egyoldalas webalkalmazás is az egész, amikor egyetlen statikus HTML-ben navigál a felhasználó és esetleg a backendről az adatokat kéregeti le vagy frissítgeti, így még a kattintásonkénti <100ms statikus oldalbetöltést is meg lehetne spórolni.

Ez ott bukik el, hogy jelenleg az oldal tökéletesen működik JS nélkül is, tehát bármilyen JS használat csak akkor megengedett, ha opcionális. Ha megnézed, az összes js handler js-ből regisztrálódik be, anélkül is mennek a linkek, sima http gettel.

**Comment by bkil** [comment]
Rendben, szétbontottam: #1114 #1115 #1116 #1117 #1118 #1119  #1121

**Comment by vmiklos** [comment]
Kösz!
