### ISSUE TITLE
Oldalbetöltési optimalizáció: a favicon.ico hiányzik

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1115]
Ráadásul enélkül #1114 miatt jelentősen lassabb a betöltés, mert a háttérben kétszer tölti be az oldalt.

**Comment by vasony** [comment]
mint egy falat kenyér :)
javaslatom: https://commons.wikimedia.org/wiki/File:Housenumber_icon.svg

**Comment by vmiklos** [comment]
Lehet róla szó

**Comment by vasony** [comment]
nálam nem látszik ikon, kellene?

**Comment by vmiklos** [comment]
Reload? Ha egyszer nem kap ikont a böngésző, akkor sztem cache-eli ezt a nemleges választ

**Comment by bkil** [comment]
Az én böngészőmben most már mindkettőtök oldalán megjelenik. :rocket:

**Comment by vasony** [comment]
igen, lehet tényleg cache volt bár F5 volt, de ezek szerint nem voltam alapos
