### ISSUE TITLE
Oldalbetöltési optimalizáció: válaszok tömörítése

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1116]
A szerver nem használ tömörítést a visszaadott lapokra és erőforrásokra. Nem ismerem az infrád, de talán .htaccess-ből is megoldható:

* https://bobcares.com/blog/gzip-compression-htaccess/

```
<IfModule mod_deflate.c>
...
<ifModule mod_gzip.c>
...
```

Miután jól működik, a nagyobb oldalak response header-jében meg fog jelenni ez: `content-encoding: gzip`

**Comment by vmiklos** [comment]
A tömörítés, vagy annak hiánya a webframe.py send_response()-ban dől el, valami ilyesmire lesz szükség:

https://stackoverflow.com/questions/22114321/how-to-use-gzip-encoding-with-wsgi-application/22118910

Csak ebből a példából hiányzik, hogy azt is meg kell nézni, hogy a gzip szerepel-e a Accept-Encoding: request headerben.

**Comment by bkil** [comment]
Igen, ez a hátránya, hogyha a teljes web stack kódból van megírva és nincs előtte web szerver/cache. Nekem a brotli is jó amúgy. :smile:

**Comment by vmiklos** [comment]
Ez is egy trade-off: egyik véglet, hogy egy nyomorult balra shiftelést se old meg a kód magától, hanem egy külön dependencyt használ rá, másik véglet, hogy mindent magának ír. Mivel a python standard libraryban van egysoros gzip compress, szerintem itt nem indokolt egy hard dependency egy teljes apache-ra.
