### ISSUE TITLE
Oldalbetöltési optimalizáció: ne blokkoljon az első rendering a JS letöltéséig

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1117]
Amennyiben csak úgy be van hivatkozva JS a fejlécben a két fájl, a dokumentum nem jelenik meg amíg ezek le nem töltődtek és el nem kezdtek értelmeződni. Ez különösen zavaró cache miss esetén.

Gyors körüljárásként érdemesebb volna a JavaScript behúzást az oldal legvégére, a `</body>` elé rakni. Nem ellenőriztem, hogy bírja-e ezt a függvénykönyvtárad, elképzelhető, hogy ehhez apró változtatásokat kell eszközölni.

Illetve van erre manapság korszerű megoldás is, de ilyenkor is szokták fallback-ként a fentit csinálni. Lásd:
- https://code.habd.as/jhabdas/fetch-inject#user-content-progressive-enhancement
- https://news.ycombinator.com/item?id=14380191

> Dynamically inline assets into the DOM using Fetch Injection

**Comment by vmiklos** [comment]
Ha jól értem a JS esetén annyi a megoldás, hogy:

```
<script defer src="foo.js"></script>
````

CSS-re nincs ilyen szép megoldás, csak JS workaround vagy az, amit írsz, hogy az oldal végére rakod, ami szembemegy azzal, hogy a CSS-t illik a head-be rakni. A JS defer az szerintem is jó ötlet.

**Comment by bkil** [comment]
Igen, ez még jobb.
