### ISSUE TITLE
Oldalbetöltési optimalizáció: a felhasználók által elért végpontok memoizáljanak, várható értékben ne sokat számoljanak

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1119]
Jelentősen csökkentené a késleltetést (ami jelenleg 300-500ms+) ha minden oldalbetöltés statikus HTML-re mutatna. Ezen belül két megoldás adódik:
* Vagy az adatokat JavaScripttel töltené ki (vagy iframe, bár azzal nem lehet jót kihozni ebből...),
* Vagy még optimálisabban előre ki volna töltve adatokkal, így nem is kéne lekérni semmit.

Utóbbihoz nem csak a txt-ket generálná a cron és a frissítés gomb meghívása, hanem statikus HTML-ként az eredményeket is. Ehhez ipari oldalakon illendő versenyhelyzet ütközések okán verziózott fájlnevekre átállni, bár itt még lehet, hogy elmegy simán a felülírogatás.

Kicsit kódolni is kellene hozzá, bár érzésre nem vészesen sokat.

Erre a felvetésre a következőt válaszoltad, bár nem 100%, hogy mire gondolsz:

> Lehet elég lenne csak annyi, hogy a diff kimenete cache-elve legyen, abból htmlt generálni elég olcsó.

Alternatív, drágább, de jobb implementáció: #1121

**Comment by bkil** [comment]
Lehetne streamelni a HTML-t alternatívaként, azaz soronként kiírni a táblázatot a teljes oldal pufferelése helyett. Ez sokkal több fejlesztést igényelne és kicsit bonyolultabb és csúnyább is lehet tőle a kód, ezért érzésre nem javaslom.

Nos, így az architektúrádat átgondolva bár a teljesen statikus HTML-ek igazi webszerver általi kiszolgálása volna a leggyorsabb (<50ms), akkor tényleg egy szűk keresztmetszetet képező rutint lehet érdemes memoizálni.

A fenti kommentben a `diff` ha jól értem erre vonatkozik `areas.py:get_missing_housenumbers()` amit a `wsgi.py:missing_housenumbers_view_res()` hív.

Na most lehet egy alternatíva, hogy így próbálgatással és profilozással egyenként bővítjük a cache-elt köztes adatok körét, vagy tényleg átgondolhatjuk, hogy nem-e lehet mindent egységes módon statikussá varázsolni (és leíróan dekorálni az adatfüggőségeket, hogy tudja melyik oldalakat kell újragenerálni frissítés esetén).

**Comment by vmiklos** [comment]
Ez egy elég nagy téma, talán két részre lehetne bontani: 1) a diff cache-elése 2) statikus html az olyan oldalra ami ritkán változik.

A cache azért fontos, mert pl a footer tartalmazza a git hash-t ami arányag gyakran változik, tipikusan naponta. 0-ról újraszámolni az összes missing-housenumbers oldalt sok relációra csak azért, mert változott a git hash az elég nagy pocsékolás. Más static site generátorok is tipikusan cache-elnek, pl a pelican is cache-eli az asciidoc outputot, így tudja kb 1 sec alatt legenerálni egy 1000 oldalból álló oldal tartalmát. Ezt eddig azért nem valósítottam meg, mert minden teljesítménybeli fejlesztés növeli a szoftver bonyolultságát, és én házszámozni szeretnék az osm kontextusában, nem programozni. Minél unalmasabb, régimódibb és egyszerűbb a technológia, annál jobb. :) De most a 11. kerület legenerálása nálam helyben is 26 sec körül van, ami egyértelműen lassú, így látom értelmét valamiféle cache-elésnek. Elvileg ezek a függőségek vannak: 1) osm utcák 2) osm házszámok 3) ref házszámok 4) filterek. Ha a HTML kimenet lényegi részét elmentjük és nézzük, hogy a cache ennél a 4-nél újabb legyen, akkor ez megoldható.

A static html ezek után engem max akkor izgat ha a cache önmagában nem viszi el mondjuk a költség 80%át. Egyéb esetben inkább adnék json apit, és utána külső projekt építhet belőle html/js webappot ha akar, ezzel én nem nagyon tervezek foglalkozni.

De a cache-t sem most, inkább megyek házszámozni. :)

**Comment by bkil** [comment]
Rendben. Amikor nyitottam a hibajegyet már elfelejtettem hogy van üzemeltetve (ez pedig nincs dokumentálva sem) - hirtelen nem volt meg a kontextus, hogy nem fut alattad igazi web szerver ami pillanatok alatt visszaadhat statikus oldalakat.

Amennyiben így is, úgy is be kell tölteni egy Python értelmezőt és a modulokat, már tényleg kis különbség, hogy az egész oldal bitenként van-e elmentve avagy csak a számításnak az a része ami az üres oldalbetöltés feletti mondjuk 0.1s-nél hosszabb időt teszi ki. Tehát rád bízom, hogy a memoizálás melyik szinten legyen.

_Ötlet: bárhol is fog ez megtörténni, működhetne lusta kiértékeléssel is - azaz bár ideálisnak tartanám ha minden cache minden nap frissen lenne tartva, de ha az túl sok idő, elég csak az első használatkor elindítani egy frissítést. (UX szempontjából amúgy rá lehet ültetni egy hacket, hogy ilyenkor stale cache értéket adunk vissza a felhasználónak illetve esetleg erről egy tájékoztató bannert és egy linket amivel frissíthetik az oldalt időnként)_

Jó sportolást!

**Comment by vmiklos** [comment]
> ez pedig nincs dokumentálva sem)

https://github.com/vmiklos/osm-gimmisn/blob/master/INSTALL.adoc#production-setup

Szólj ha valami nem világos

> Jó sportolást!

Köszi!

**Comment by bkil** [comment]
A hivatkozott leírásban is szerepel a megoldás: :smile: 

> Optionally, set up a reverse proxy with SSL support.
