### ISSUE TITLE
Pontosvesszős hászám parse

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#112]
Bornemissza utca 22;24-ből csak a 22-t veszi figyelembe.
Régebben "22, 24" volt, abból semelyiket sem vette figyelembe.

**Comment by vmiklos** [comment]
Igen, jelenleg csak "-" mentén darabol és utána minden eldob a szám után. Nem tudtam, hogy van ilyen ";" menti darabolás is, megoldható. A lényeg, hogy olyan szeparátor ne legyen ami után valami alszám jön. Tehát pl 120/1, 120/2, akkor nem jó / mentén darabolni, mert az igazi 1, 2 hiányát akkor nem találjuk meg.

**Comment by vmiklos** [comment]
Szólj ha mégse jó.

**Comment by vasony** [comment]
megy, kösz.
szokott lenni sajnos, főleg vidéken láttam, ilyet pl: 1;3;5, amikor nem veszik fel külön a bejáratokat.
majd elmegyek és megnézem mi a valóság, valószínű 22-24 lesz az.

Sajnos a vessző is meg van adva a wikin, de egyelőre hanyagoljuk
"Separate the numbers by commas (e.g., 11,13,15) or semicolon (e.g., 11;13;15). "
