### ISSUE TITLE
UX: redundáns oszlopok kitörlése a street-housenumbers, streets és additional-streets oldalon

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1139]
Ki lehetne vágni egy adott oszlopot amennyiben minden sorban üres vagy egyforma értékek vannak.

Utóbbi esetben a táblázat elé vagy után meg lehetne említeni a kihagyott egyező értéket.

Bizonyos, kis értékkészletű oszlopot kézileg kiválasztva akár több táblázatot is létre lehetne hozni aszerint csoportosítva, például 3 táblázat lenne egymás alatt minden egyes `@type`-ra 1-1, vagy lehetne Budapesten ilyen az `addr:postcode` is.

Ez csökkentene a fájlméreten és a jót tenne a szépérzéknek is.

Alternatívaként vagy további funkcionalitásként ki lehetne nevezni "sparse" oszlopokat amikben tudjuk, hogy csak nagyon ritkán szokott érték lenni, főleg a többivel kombinálva. Ezeket egy új, összevont "tags" oszlopban szöveg szerint fel lehetne sorolni. Ez további oszlopokat szabadíthat fel. Tipikusan ilyenek ezek: `addr:place`, `addr:housename`, `addr:conscriptionnumber`, `addr:flats`, `addr:floor`, `addr:door`, `addr:unit`.

**Comment by vasony** [comment]
Szerintem pont jó igy ahogy most van

**Comment by vmiklos** [comment]
Először jussunk egyetértésre, addig felesleges a kódba belepiszkálni

**Comment by vasony** [comment]
> Alternatívaként vagy további funkcionalitásként ki lehetne nevezni "sparse" oszlopokat amikben tudjuk, hogy csak nagyon ritkán szokott érték lenni, főleg a többivel kombinálva. 

Ha kiveszed az oszlopokat, akkor nem lehet normálistan sortolni.

Ezek marginális oldalak, csak néha kell nézni, amikor nem stimmel valami, de akkor viszont nem probléma ha egy táblázatban lehet látni mindent, a sort-al és ctrl-f-fel  teljesen jól használható most is.
Nem biztos, hogy megéri az erőforrást.

**Comment by bkil** [comment]
No de kell azok az oszlopok alapján sortolni? Még nem láttam gimmisn felhasználót közelről vagy használat közben, így nem tudom, hogy mire szoktatok nap mint nap kattintani.

Én nem gondoltam volna, hogy akarná valaki `addr:housename` szerint rendezni a táblázatot, ami a képernyő tetejére (aljára) hozza azt a 3 elemet amin szerepel az a címke (az ezerből mondjuk).

Ezzel szemben ha létezne egy új kompozit oszlop ezekkel és erre kattintana rendezést a felhasználó, akkor a képernyő tetejére kerülne az a 30 elem, amin a címkék bármelyike szerepel ("pszeudorandom sorrendben", gondolom erre gondolsz). Csúnyán néz ki? Kicsit.

Alternatívaként ha ezt tényleg szűrésként szoktátok használni, szerintem megoldható olyan gombok kifejlesztése amik csak az `addr:housename`, csak az `addr:unit` stb sorokat jelenítenék meg, ugyanebből a kompozit oszlopból főzve.

És végül bár ez bennem most akkor merült fel amikor ránéztem, hogy a SPA megoldást hogyan tehetnénk kisebbé, ez a hatalmas mennyiségű oszlop már annak idején is zavart (mind kinézetben, mind koncepcióban) amikor én tettem bele a kódba.

Fun fact: mivel a transzformáció a többi javaslatomhoz hasonlóan veszteségmentes, JavaScriptben vissza lehet csinálni kliens oldalon, hogy pontosan ugyanígy nézzen ki ahogy most, ha valaki ezt szereti.

Ha mindezek után is úgy gondoljátok, hogy nem tetszene ez az új kimenet és nem javítana a gimmisn jelenlegi változatán, zárjuk le ezt az issue-t és megoldom magamnak out of tree - ezzel akkor nem terhelem a core fejlesztőket. :bowing_man: :+1:
