### ISSUE TITLE
Overpass nem frissül

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#114]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenfold/view-result
Utolsó frissítés: 2019-08-03 22:57

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/csilleberc/view-result
Utolsó frissítés: 2019-08-03 03:33

Tegnap is észrevettem, de adtam neki 1 napot..

**Comment by vmiklos** [comment]
Elindul az éjszakai cron job, és márthonhegynél lehal. Elindítottam kézzel, meglátjuk ad-e valami használható hibaüzenetet.

**Comment by vmiklos** [comment]
És most lefutott hiba nélkül. Esetleg az lehet, hogy a pythonanywhere IP-jéről pont akkor futtat más is overpass query-t, és akkor hiába nézem meg a status-t, látom, hogy mehet a query és azonnal küldöm, mégis visszadob.

Annyit mindenesetre majd megteszek, hogy majd injektálok hibát és megoldom, hogy ha exceptiont dob a cron akkor az logolódjon, így okosabbak leszünk legközelebb.

**Comment by vasony** [comment]
El tudod menteni a kimenetet valami logba amit éjszaka produkál? Mert akkor könnyebb elkapni.
Esetleg lehetne kezelni valahogy, hogyha elindítottad és nem frissült, akkor retry.

**Comment by vmiklos** [comment]
Jah, ennyi az ötlet, u.úgy elkapni az exceptiont mint ahogy a webappnál már meg van oldva.

**Comment by vmiklos** [comment]
Ma amúgy megint lefutott gond nélkül. De minden esetre a fenti most már logol mindent, így legközelebb ha ez előjön, okosabbak leszünk.

**Comment by vasony** [comment]
Nézd meg a logot, légy szíves, mert megint nem frissült.
Kelenföld: Utolsó frissítés: 2019-08-06 03:40

**Comment by vmiklos** [comment]
````
HTTP Error 504: Gateway Timeout
````

Tegyek bele retryt? Ha `wget` segítségével töltesz le valamit, alap esetben 20x próbálkozik újra mielőtt feladja. Hmm.

**Comment by vasony** [comment]
Az jó lesz, de kellene vmi sleep is közé.

**Comment by vmiklos** [comment]
Explicit sleepet nem raktam bele, minden iteráció előtt nézi az overpass státuszát; ha túl gyorsak vagyunk, ott úgyis szólni fog szerintem.

**Comment by vasony** [comment]
Gateway timeout-nál eljut odáig? majd kiderül. logból gondolom látszik, hogy milyen sűrűn futott neki majd.

**Comment by vmiklos** [comment]
Helyben futtattam, ilyet kapok most pl:

````
update_street_housenumbers: start: szilvasvarad
overpass_sleep: waiting for 390 seconds
update_street_housenumbers: http error: HTTP Error 504: Gateway Timeout
update_street_housenumbers: try #1
update_street_housenumbers: end: szilvasvarad
````

Ez egyelőre bíztató. (A try 0-tól számol, az elsőt nem írja.)

**Comment by vasony** [comment]
dátum nincs a logban? :)

**Comment by vmiklos** [comment]
Konzolra nem ír dátumot, logba igen:

````
2019-08-07 13:33:57 INFO update_street_housenumbers: start: szilvasvarad
2019-08-07 13:33:58 INFO overpass_sleep: waiting for 390 seconds
2019-08-07 13:41:09 INFO update_street_housenumbers: http error: HTTP Error 504: Gateway Timeout
2019-08-07 13:41:09 INFO update_street_housenumbers: try #1
2019-08-07 13:41:57 INFO update_street_housenumbers: end: szilvasvarad
````
