### ISSUE TITLE
UX: street-housenumbers táblázat betöltéskori természetes rendezése

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1140]
Régen volt egy rendezés irányítószám, utcanév, házszám meg ilyesmik szerint. Ez mintha teljesen eltűnt volna a JavaScriptes varázsrendezés óta és már alapból ID szerint jön le az adatkészlet. Ez szándékos?

**Comment by vmiklos** [comment]
Félig. Ott veszett el a funkció, hogy a csv oszlopokra régen pozíció szerint hivatkoztunk, ma pedig az oszlop nevével. Ha küldesz PR-t ami visszaállítja ezt a rendezést úgy, hogy nem pozíció szerint hivatkozik az oszlopokra, akkor szerintem nincs ezzel baj.

**Comment by vmiklos** [comment]
Ha valamit debuggolok, az a legegyszerűbb ha utcák szerint van rendezve a kimenet, azon belül pedig házszámok szerint. Keresni (szűrni) a tartalomban a sima böngészős keresés is tud, ennyi eddig mindig megfelelt.

Én nem gondolnám túl a dolgot, ahogy @vasony máshol írta:

> ez egy marginális oldal, debug céloknak ez a megjelenítési struktúra felel meg a legjobban
