### ISSUE TITLE
UX: hiányzó házszámokból az összefüggő tartományok összevonása

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1142]
Elég nagy a hiányzó házszámokat felsoroló táblázat. Volna értelme emberileg, hogy az egymást követő számokat összevonjuk? A tárhelyen mindenképpen segítene.

Tehát ha ebből:

```
1, 3, 5, 13/A, 15, 17, 19
```

Például ez is lehetne:

```
1..5, 13/A, 15..19
```

**Comment by vmiklos** [comment]
Mikor házszámozok, akkor engem segít, hogy van egy listám, és elsősorban a terepen azokat kerestem. És nem kell fejben tartani, hogy a 15..19 az 15, 16, 17, 18, 19 vagy 15, 17, 19, mert látom az összes elemet. Várjunk ezzel egy kicsit, hátha másnak is van véleménye.

**Comment by vasony** [comment]
Az én véleményem, hogy maradjon ahogy most van, tökéletesen használható így is a gyakorlatban. 
(Igaz én a checklist kimenetet használom)

**Comment by bkil** [comment]
Rendben.
