### ISSUE TITLE
UX: ID oszlop eltüntetése, OpenStreetMap.org linkelése egy kötelező mezőről az additional-streets, street-housenumbers, streets oldalakon

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1143]
Meg tudnánk-e szabadulni az ID oszloptól, amennyiben az OSM link egy olyan mezőre kerülne át helyette, ami minden sorban szerepel, ezt pedig ideálisan az első oszlopba lehetne mozgatni.

Ez csökkenti mind az oszlopi túlterheltséget, mind a tárhelyigényt.

Az alapkoncepció, hogy a felhasználó számára nincs információértéke az OSM ID-nek a képernyőn - ő csak meg szeretné nyitni a hivatkozást.

Szoktatok ID szerint rendezni vagy akar ilyet bárki is? Meglepődnék, ha igen (akkor már inkább egy oszlop a létrehozás vagy utolsó módosítás dátumával). Ha mégis, ez a funkció megtartható volna amennyiben a JavaScript rendezést okosítjuk, hogy a `href`-et is vegye figyelembe.

Ezt már körüljártam out of tree, így a javasolt kinézetet megtekinthetitek az SPA-Misi demóban. Alternatívaként ezen felül ahogy az #1139 (redundáns oszlopok) ötletben említettem, lehetne még takarékosabban külön táblázat node/way/relation szerint, és ekkor a link nem a `@type`-ra, hanem például a `name`/`addr:street`-re kerülne.

**Comment by vasony** [comment]
Szoktam id-re rendezni, mivel a létrehozás dátum nincs fent, illetve néha látni belőle az egy kupacban létrehozott dolgokat.

**Comment by bkil** [comment]
Rendben, akkor erre JavaScript körüljárást kell csinálni ami beszúr egy szintetikus oszlopot a fallback HTML href-ek alapján, és akkor működne a jelenlegi keresőgomb is és ugyanúgy nézni ki minden.
