### ISSUE TITLE
UX: a street-housenumbers oldal miért nem hasonlít jobban a missing-housenumbers oldalra?

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1145]
Az alapadatokat ugyanolyan aggregált táblázatban is meg lehetne jeleníteni (egyéni ízlés szerint irányítószám szerint külön táblázatban vagy egy táblázatban ahol az irányítószám és utcára párosra egyedi sorok szerepelnek). A további megtalálható adatok kerülhetnének akár egy felbukkanóba vagy sima zárójelbe is, és az OpenStreetMap entitás hivatkozás mondjuk kattintásra is megnyílhatna.

Ez masszívan csökkentené a tárhelyigényt és körüljárná a táblázat szokatlan, egyéni finomhangolásának megosztóságát (#1139 ).

**Comment by vasony** [comment]
Mint írtam ez egy marginális oldal, debug céloknak ez a megjelenítési struktúra felel meg a legjobban.

**Comment by bkil** [comment]
Tehát a felhasználói igények alapján érdemes megtartani a jelenlegi oldalkinézetet, és a tömörebb változat lehetne egy új oldalon (akár a már említett tartomány-összevonásokkal).
