### ISSUE TITLE
Ötlet: a végpontok ne legyenek egymás prefixei

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1146]
A `wget` elsírta magát amikor meglátta ezt a két fájlt:

- `osm/filter-for/refcounty/01`
- `osm/filter-for/refcounty/01/refsettlement/001`

Bár ezt körüljárja az `--adjust-extension`, de ez pedig elrontja a cache-elést (`--no-clobber`) - azaz mindig letölti ugyanezeket a fájlokat.

Tudom, hogy ez egyéni szociális probléma  - üzemeltethetnék proxy szervert vagy saját rekurziót. És ebben a pillanatban amúgy sem tervezem gyakran `wget`-elni az oldalt.

Viszont tervezési szempontból is elegánsabb volna mondjuk egy `osm/filter-for/refcounty/01/everything` és nem tűnik nehéznek lekódolni, így gondoltam azért bepróbálkozok. :smile_cat: :angel:

**Comment by vmiklos** [comment]
Küldesz rá patchet? Nekem teljesen mindegy
