### ISSUE TITLE
Oldalbetöltési optimalizáció: ne blokkoljon az első rendering a CSS  letöltéséig

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1158]
Ötletek:
- inlining & tree shaking (léteznek rá eszközök)
- preload a fejbe, a CSS hivatkozás a body végére akár (kissé villódzhat)

Leválasztva erről: #1117

**Comment by bkil** [comment]
- https://web.dev/extract-critical-css/
- https://dev.to/didof/handle-css-in-webpack-inline-css-fho
- https://purgecss.com/

Ezt csak a margóra JavaScripthez:
- https://webpack.js.org/guides/tree-shaking/

**Comment by vmiklos** [comment]
Mutatsz js mentes megoldást ami valid html? Ha egyszerűen a </body> elé rakom a style-t az invalid:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fshare.vmiklos.hu%2Fosm-gimmisn-gh1158%2F

**Comment by bkil** [comment]
Inline nem működik, viszont ha kicseréled hivatkozásra `<link rel="stylesheet" type="text/css" href="/spamisi/static/osm.css" />` akkor már zöld.

Inline-olni esetleg a `<head>`-be érdemes a CSS kritikus, rövid részét, ha van ilyen neki.

**Comment by bkil** [comment]
De mondjuk így jobban megnézve amíg nálad összesen ez az 1888 bájtos stílusfájl van (ami még nincs is minifikálva), addig ennek a hibajegynek a tanácsa még az is lehet, hogy simán inline-old be az oldal fejlécében.

Ha küldök PR-t a JavaScript nélküli grafikákról akkor azt a nagyobbacska CSS-t már érdemes lesz a végén behúzni a fentiek szerint.
