### ISSUE TITLE
UX: A táblázatok oszlopainak jelentése nem világos egy teszt szerint

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#1179]
Nem volt világos, hogy mit jelent:
* "további utcák" (hiányzó házszámokat próbáltuk belegondolni)
* "házszám lefedettség" (nem volt egyértelmű, hogy a százalékra kattintva a hiányzó házszámok listája nyílik meg)

Még nem tudom mi a jó megoldás, de vagy át lehetne nevezni őket, vagy felbukkanóban lehetne pár szavas magyarázat. Illetve esetleg a lefedettségi %-on való hoverre is előbukkanhatna az a tény, hogy a hiányzó házszámok megtekintése fog megtörténni a kattintás után (vagy zárójelben mögötte lenne a link, esetleg külön oszlop?).

**Comment by vmiklos** [comment]
A linkeknek tudsz adni title attribútumot, oda tudsz neki adni tooltipet.

Utána kell neki `make update-pot`, `make update-po`, aztán a magyar .po file fordítása.

Ez eléggé ilyen kozmetika kategória: ha érdekel, akkor kérlek küldj rá egy PR-t, csak a yattag tag-ek generálásába kell belenyúlni, azt már ismered te is. Esetleg a doksiba lehet bővebben kifejteni.

**Comment by vasony** [comment]
Most az utolsó frissítés dátuma van a % tooltipjében

**Comment by vmiklos** [comment]
Ja tényleg. Akkor meg egyszerűen a doksiba kéne szájbarágni. Nekem a mostani is egyértelmű, de ha @bkil szeretné bővíteni a doksit, ám legyen.

**Comment by vasony** [comment]
Fejlécbe lehet tooltip
