### ISSUE TITLE
Tesztek függenek az igazi relációktól (gazdagret)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1198]
Ha letörlöm gazdagret területet, akkor a tesztek nem futnak le, mert szerintem nem találja a referenciát

https://github.com/vmiklos/osm-gimmisn/pull/1197/checks?check_run_id=2260571671

**Comment by vmiklos** [comment]
A test_config.TestCase alapú tesztek a tests/data alól dolgoznak, nem a data alól. A unittest.TestCase viszont a data alól. Ott lesz a gond, ahol véletlenül az utóbbi base class is működött eddig.

**Comment by vmiklos** [comment]
Azt hiszem ez zárható.
