### ISSUE TITLE
cron cache

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1209]
cron futásnál cache-elődejenek be a területek (magyar is)

**Comment by vmiklos** [comment]
Az angol már most is megy, a magyar valóban hiányzik.

**Comment by vmiklos** [comment]
Lehet tesztelni. `./cron.py --refcounty 01 --refsettlement 011 --mode relations` után kell legyen mostanában módosított `workdir/budapest_11.htmlcache.hu`.

**Comment by vasony** [comment]
Úgy tűnik, hogy mindenhez legenerálta a cachet.
