### ISSUE TITLE
Travis yaml . az utcanévben

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#122]
Vótmá' a Május 1. utcánál, hogy leszedtük a pontot, hogy a travis megegye.
Most a XI. utcát nem eszi meg, pont nélkül meg nem jó a filter

**Comment by vmiklos** [comment]
Ez most így nem jó, a helyes YAML syntax:

````
  'XI. utca':
````

'' nélkül a '.' az így értelmeződne:

````
XI:
    utca:
````

A validátor mondjuk így se eszi meg, ld. a 1c0b89c05685daab0679cd2cd0f549eab0ba420e commit message-ét. Legjobb lenne egyelőre ezt kiszedni és akkor megnézem, hogy mire lehet lecserélni a gagyi validátort, de a master jó lenne zölden tartani.

**Comment by vasony** [comment]
Igen, próbáltam úgy is, nem ment. Nem lehet maszkolni?

**Comment by vasony** [comment]
vagy visszakapcsoljuk a simplify-t erre :)

**Comment by vmiklos** [comment]
Kipróbáltam, a saját kód megy '' meg anélkül is. (Ld. fenn, azt hittem a '' nem opcionális.) A XI. utcára 39 házszámot ad filterrel, 43-at ha törlöm a filtert. Inkább a validálást kapcsolom ki egyelőre a problémás yamlokra, aztán ha van jobb validátor (ennek követésére tökéletes ez az issue) akkor lehet újra validálni ezeket is.

**Comment by vmiklos** [comment]
Lényeg a lényeg: ha a CI hibát jelez, akkor beszéljük meg a pull requestben, ne bíráld felül, az csak különleges esetekre van. :-)

Ld. fenti commitom, a Makefile-ba fel tudsz venni egy sort (a listának most csak egy eleme van) ami kikapcsolja a validálást adott file-ra ha ezzel van a baj. Köszi!

**Comment by vasony** [comment]
ok, tesztnek vettem fel hibásan, hogy megy-e az oldal a hibás szintakszissal, de közben már jelentkeztél :)
egyébként a yamlint nem döglik meg rajta csak a másik, most mindkettőt letiltja?

**Comment by vmiklos** [comment]
A lint nem hasal el. Amúgy a validátort is megszerelték közben, most írtam a csávónak, hogy csináljon már kiadást és akkor csak annyi az egész, hogy a requirements.txt-ben meg kell követelni az új verziót. (23andMe/Yamale alatt PR 58).

**Comment by vmiklos** [comment]
Gyorsan reagáltak. :-)
