### ISSUE TITLE
Frissítés referenciából heti futtatás

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#128]
Kedd éjszakára be kellene ütemezni a területek végighívását: /suspicious-streets/*/update-result. Illetve nem tudom, hogy ennek a dátumát hova tudjuk kivezetni? 
A suspicious-streets/*/view-query végén milyen dátum található? Lehet azt kellene lecserélni.

**Comment by vmiklos** [comment]
Igen, erről már beszéltünk, hogy a referencia nem frissül automatikusan, jogos.

**Comment by vmiklos** [comment]
Ja, és a kérdésedre válaszolva: a suspicious-streets/.../view-query alján a referencia és az OSM házszámlista maximuma van, ezt még az #57 -ben kérted. :-)

**Comment by vasony** [comment]
A view-result-ra kértem :-) Ha tudjuk válasszuk ketté, a view-result
maradjon, a view-query pedig legyen a tényleges ref frissítést.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/0d26d0e02e3edcb197f8c4c6f0cd2165caf04ebb

Gondolom az referencia utca listát is érdemes lenne cronból újragenerálni? Ez most csak a házszámokkal foglalkozik.

**Comment by vmiklos** [comment]
A dátumot is megszereltem: ahogy mondtad a dátum közös volt az összes hiányzó házszám oldalra, most a view query az speciális eset, ott csak a ref dátumot mutatjuk, nem az osm és a ref maximumát. Szóval ez egyelőre kész, bár ha érdekel, mindkét fenti commitnak az utcás verzióját is meg lehetne csinálni (hiányzó utcák ref adatai, dátuma).

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/krisztinavaros/view-query -> 2019-08-12 16:25

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/krisztinavaros/view-result -> 2019-08-17 15:01

Aztán ezt a cron majd jól "elrontja" kb azonos dátumokra. :-)

**Comment by vasony** [comment]
Az a jó ha elrontja :) Akkor tudjuk hogy működik .

Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. aug. 17.,
Szo 15:24):
