### ISSUE TITLE
Hiányzó házszámok, text kimenet - sort order

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1408]
Valamelyik frissítés elrontotta a sortolást a text kimeneteten.

https://osm.vasony.hu/missing-housenumbers/budapest_03/view-result.txt

o ő ü ű rosszul sortolódik
a helyes o ó egyben majd ö ő egyben, most a kettő együtt megy

Régen (06.01) - ez jó

```
Kovácsi utca	[3, 5], [2]
Kőbánya utca	[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 63, 65, 65-67, 69, 71, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93/A, 95, 97, 99, 111, 113, 117, 119], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 70, 72, 74, 76, 78, 80, 82, 86, 88, 90, 92, 94, 96, 102, 104, 106, 116, 120 A, 132]
Köles utca
```

Most (06.21) - ez nem jó

```
Kőpor köz	[3, 5, 7, 11, 13, 15, 21, 23, 25, 27, 29, 31, 33, 35], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 36]
Kőpor utca	[1, 3, 5, 7, 9, 11, 13, 13-15, 17, 19, 19-21, 25, 27, 33, 37, 39, 41, 45, 47/D, 49/A, 51, 55, 57, 59, 61, 63, 65, 67], [2, 2-4, 6, 8, 10, 12, 14, 16, 18/B, 20, 22, 26, 28, 32, 34, 36, 38/B, 40, 44, 46/A, 48, 52]
Kőrés lejtő	[3, 5]
Kórház utca	[17, 19, 19/2*, 21, 21/1*, 23, 25, 27, 27/3*, 29], [20]
```

Kórháznak a Kőpor előtt kell lennie

**Comment by vasony** [comment]
Erre is lehetne teszt

**Comment by vmiklos** [comment]
Látom, a teszt is jó ötlet

**Comment by vmiklos** [comment]
A github actionsban nincs magyar locale (legalábbis alapból, ennek esetleg még egy kicsit utána lehet járni), így a teszt feltételes: nálam fut, de ha nem találja a locale-t akkor nem fut. Több mint a semmi. Ha teszteled, töröld a budapest_03 txt cache-t, ami abban van az a fix után is rossz lesz.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/pull/1419 közben megtaláltam a CI részt, úgyhogy fut a teszt szépen, gányolás nélkül.

**Comment by vasony** [comment]
Jónak tűnik. A frissítés osm-ből nem kellene törölje a txt cache-t is?

**Comment by vmiklos** [comment]
de igen. a txt cache a reláció filter (yaml), osm street, osm housenumber és a ref housenumber file-októl függ. ha bármelyik újabb, újraszámoljuk.

**Comment by vasony** [comment]
nem töltöttem újra, akkor ez volt a baj, csak a frissítés utáni dátumokat néztem os-ben.
