### ISSUE TITLE
Hiányzók szinezése residential/commercial

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#141]
Valahogy jó lenne megkülönböztetni, hogy melyik ref állományból jön a hiányzó házszám, hogy mit keressek a helyszínen lakóépületet, vagy irodaházat/boltot.
1) Vagy 2 file kellene, az eredetit hívom residential-nak, a kiegészítettet commercial-nak, vagy 1 fileban de kellene egy marker bele, hogy innen másik fajta
2) Vagy plusz oszlop minden házszámhoz, de ez eléggé megnöveli az állományt.

Az eredmény htmlben más színnel kellene az üzleti. Amelyik mindkettőben van, az residential.
Jó lenne, ha a view query-ben is látszódna

Tesztelhető Sasaddal, ott csak üzleti maradt fent
Ági Virág 	1112 Budapest Márton Áron tér 14

**Comment by vmiklos** [comment]
Szerintem legyen 2 file. (Valami ilyesmi, hogy hazszamok_20190511_residential.tsv meg commercial u.így.) Mik legyenek a színek? :-)

A view-queryben ugye most egy újsor-szeparált listát kapsz, ezt ki lehet bővíteni TSV-re és akkor az eddigi 1 helyett 2 oszlop lenne, a 2. oszlop a tipus. Kicsit macerás, mert eddig csak 1 referencia volt, de nem megoldhatatlan.

Magamnak írom, hogy ne kelljen újra kikeresni, hogy a commercial címek forrása a govcenter.hu.

**Comment by vasony** [comment]
Marad fekete a residential, kek vagy piros a comercial.
Plain textben és view queryben elég egy *, lényeg hogy orderben maradjon a
helyén, ne legyen 2 oszlop.
Pl.

Akármi út 1
Akármi út 2*
Akármi út 3
Akármit út 4

....

Akármi út [1,3][2*,4]


Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. aug. 25.,
V 21:05):

**Comment by vmiklos** [comment]
Jól van, remélem az épületek típusai előbb fognak elfogyni mint a speciális karakterek. :-) Első lépésben akkor az kell, hogy több forrásból is jöhessen a referencia, ezt majd megnézem.

**Comment by vmiklos** [comment]
Következő lépés: a relációra leszűrt referenciában (.lst file-ok) csillaggal jelölni a commercial házszámokat.

**Comment by vmiklos** [comment]
Ha az éjjeli cron lefut akkor majd a *nak itt látszódnia kell pl a Márton Áron tér 1-nél:

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/sasad/view-query

Helyben legalábbis látszódik. Persze mikor a .lst-t máshol beolvassuk és értelmezzük, akkor továbbra is eldobjuk a *ot a végéről, ez lesz majd a következő lépés.

**Comment by vasony** [comment]
Nem látszódik.

**Comment by vmiklos** [comment]
Valóban nem frissült, de más miatt:

````
2019-08-29 01:46:11 ERROR main: unhandled exception: Traceback (most recent call last):
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 151, in main
    our_main(relations, config)
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 127, in our_main
    update_street_housenumbers_ref(relations, config)
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 93, in update_street_housenumbers_ref
    relation.write_ref_housenumbers(reference)
  File "/home/vmiklos/git/osm-gimmisn/helpers.py", line 412, in write_ref_housenumbers
    lst += self.build_ref_housenumbers(memory_cache, street, suffix)
  File "/home/vmiklos/git/osm-gimmisn/helpers.py", line 384, in build_ref_housenumbers
    if street in reference[refmegye][reftelepules].keys():
KeyError: '005'
````

Majd megnézem, mi ez.

**Comment by vmiklos** [comment]
Ja világos; a valasztas.hu referenciában mindig volt 5. kerület, míg a kiegészítőben nincs, viszont ezt nem kezelem le.

**Comment by vasony** [comment]
Ezt majd nézd meg légyszí, középen van a csillag
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenfold/view-query

Rátz László utca 000000*7

**Comment by vmiklos** [comment]
Az a valasztas.hu referenciából jön. Annyira nem is lenne problémás, mert a közepén van, de ha rákeresek, van bőven * a végén is. :-(

Opciók:

1. Együtt élünk ezzel.
2. Csillag helyett valami más szimbólum, pl kereszt jel (†).
3. Vissza az én kicsit túlbonyolított megoldásomhoz, hogy a referencia listából tsv lesz, és a második oszlop explicite írja a házszám típusát.

Az egyszerűség kedvéért tetszik az első kettő, az utolsó meg több munka, de szerintem elegánsabb...

**Comment by vasony** [comment]
4. csinálok új refet ahol ezeket kiszedem :)


Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. aug. 30.,
Pén 16:31):

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/farkasret/view-result Rácz Aladár 1 kék lett, a többi maradt fekete. A .txt kimenet meg csillagozik. Azt hiszem ez készen van.

**Comment by vasony** [comment]
most ha mindkettőben van, akkor dupla lesz, a view-resultban
Alkotmány utca	[1, 5, 5*, 7...

a view-query-ben így van: 
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/budafok/view-query
Alkotmány utca 1-5
Alkotmány utca 5*

Lehet nem is baj ha az ilyen típusok jönnek duplán, csak nem tudom van-e kódolva vmi a sima egyezésre, ahogy eredetileg gondoltam, mert feltűnően nem láttam máshol ilyen duplát.

**Comment by vasony** [comment]
A statisztikában viszont biztos duplán számítanak, mert kelenföldön megnőtt a meglévők száma úgy hogy nem csökkent a hiányzó:

2019-08-30 07:51	OpenStreetMap nem tartalmazza a lenti 21 utcához tartozó 123 házszámot. (meglévő: 2383, készültség: 95.09%).
2019-08-31 03:44	OpenStreetMap nem tartalmazza a lenti 21 utcához tartozó 123 házszámot. (meglévő: 2396, készültség: 95.12%).

**Comment by vmiklos** [comment]
Kezeljem le ezt én, vagy generálsz új kieg referenciát amiben nincs felesleges duplikalt házszám?

Annyira nem zavar engem amúgy a duplikacio, ha pl az alap szerint van 4., a kieg szerint 4-5, azt aránylag macera deduplikalni, ha meg rendesen fel van mérve a 4 meg 5 vagy 4-5, úgyis eltűnik mindkettő.

**Comment by vmiklos** [comment]
A sima egyezést szűrni van értelme, csak az a kérdés hogy ezt már a kieg ref generalasa idején még tudod-e csinálni, vagy oldjam meg később én.

**Comment by vasony** [comment]
nem szűrném le, akkor maradjon így, nem baj ha duplikált, ez is információ.
egyébként azért se szűrném már ki, mert még vannak további terveim UI szempontjából a kékekkel.
de megígérem nem lesz több extra karakter :-)

**Comment by vasony** [comment]
most néztem meg a kódot, le volt szűrve, hogy csak azok jöjjenek amik nincsenek a valasztas.hu-ban, akkor csak a trükkösök jönnek, ez nem is baj, mert most a 6. kerületben sok a dupla.
