### ISSUE TITLE
stat: ha nincs előző időszak a havi statisztikához, akkor elszáll a frissítés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1463]
Előbb kéne ellenőrizni, aztán futtatni, vagy vegye az utolsó létezőt

```
 ./cron.py --mode stats --no-overpass
2021-07-04 08:55:19 INFO update_stats: start, updating whole-country csv
2021-07-04 08:55:22 INFO update_stats: generating json
2021-07-04 08:55:22 ERRORmain: unhandled exception: Traceback (most recent call last):
  File "./cron.py", line 385, in main
    our_main(conf, relations, args.mode, args.update, args.overpass)
  File "./cron.py", line 330, in our_main
    update_stats(conf, overpass)
  File "./cron.py", line 322, in update_stats
    stats.generate_json(conf, statedir, stream)
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py", line 217, in generate_json
    handle_topcities(conf, state_dir, j)
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py", line 91, in handle_topcities
    ret = get_topcities(conf, src_root)
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/stats.py", line 68, in get_topcities
    with open(old_count_path, "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/www/osm.vasony.hu/osm-gimmisn/workdir/stats/2021-06-04.citycount'
```

**Comment by vmiklos** [comment]
Igen, ez az "utolsó x nap" feltételezi, hogy minden napra van adat, lehetne helyette, hogy az előző napit veszi ha nincs adat. Csak arra le kell zárni az iterációt, hogy holnapra ne tippelje be a mai adatot. :-)

**Comment by vasony** [comment]
Szerintem elég ha nem frissíti **azt a statisztikát** ahol hibára futna.

**Comment by vmiklos** [comment]
Lehet tesztelni. workdir/stats/2021-06-09.citycount után eddig elszállt, most meg nem számol a városokra deltákat. Mivel mindig 0rol számolunk mindent, így az "ezt ne frissítse" logika nehezebb lenne, meg talán abba is bele lehet kötni, hogy az üres vagy az elavult adat-e a jobb, de a lényeg, hogy az egész cron nem robban fel ha egy adott napi adat hiányzik. Következő nap meg majd jó lesz.

**Comment by vmiklos** [comment]
Jó lesz?

**Comment by vasony** [comment]
ez ki is ment a fejemből, most letöröltem magamnál 17-18-19-20-át, holnap kiderül

**Comment by vasony** [comment]
ok, most üres a városos statisztika, nem száll el

**Comment by vasony** [comment]
bocs, ez egy másik hiba lesz, visszazárom
