### ISSUE TITLE
új relation-nél 1 kattintással minden létrehozása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#148]
új relation-nél, amikor bemegyünk a hiányzó házszámok alá, 1 kattintással fusson végig a 2 overpass, valamint a ref-ből való létrehozás.

**Comment by vmiklos** [comment]
Ezzel teszteltem:

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/farkasret/view-result

Töröltem az összes farkasret file-t ami generálva volt, és a 7 kattintás helyett (1 a főoldalról + 6 a generálás) elég volt csak az első + végigvárni amíg lefutnak a lekérdezések, szóval azt hiszem ez készen van.

**Comment by vasony** [comment]
Ha kézzel frissítem a meglévő házszámokat, akkor a frissítés sikeres szöveg után visszaugrik a hiányzó házszám oldalra. Ez egy nem várt mellékhatás?

**Comment by vmiklos** [comment]
Nem, szándékosan csináltam így. Kicsit zavart, hogy kiírja, hogy kész a frissítés, de kézzel kell kattintani a menübe, hogy lássam is az eredményt.

**Comment by vmiklos** [comment]
megnézem :-)

**Comment by vmiklos** [comment]
^ javítva.
