### ISSUE TITLE
start-end ellenőrzése (was: Márton Áron tér filter nem jól működik)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#156]
Nem tudom mi okozza a hibát, de ha a Márton Áron tér filter-t beteszem, akkor mindent kiszűr, függetlenül, hogy mit adok meg. Az tűnt fel, hogy megadtam először az 1-4 filtert, de még nem frissítettem a házszámokat, és mégis eltűnt minden.

Először azt hittem az interpolation zavar be, de az mindegy neki. A 14-et ki kellene dobnia hiányzónak, de nem teszi.

**Comment by vasony** [comment]
Megvan a hiba oka. A start és end fel van cserélve. 
Kellene az ellenőrzőbe még 2 dolog
- end >= start
- ha interpolation nincs, akkor mod(start,2) = mod(end,2)

**Comment by vmiklos** [comment]
3f5770097736e136f6ff2c0621f9a78bccfa4507

Az első rész megvan, talált is még 2 hasonló problémát. Azokat javítottam, de azért nézz rá, hogy jók-e a javítások.

**Comment by vmiklos** [comment]
Ez a második nem talált hibát, ami bizonyos szempontból jó hír. :-)

**Comment by vasony** [comment]
király! már megérte ha talált az első 2 hibát.

**Comment by vasony** [comment]
nem direkt, de elrontottam a paritást meg is fogta az ellenőrző.
viszont ha több hiba van, csak az elsőt írja ki

**Comment by vmiklos** [comment]
A több hiba mutatasa a legtöbb esetben sztem nem lesz bonyolult, megnézem.
