### ISSUE TITLE
Eltérő írásmódú utcák kezelése (felső határút, zólyom köz)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#16]
Felsőhatár utca/Felső határút/Felső határ út

Nem jó, mert bekavar a budaörsi név is (mivel ez van a name mezőben, nem illeszkedik az házszámokra), mivel az utcának 2 oldalon 2 neve van. streets: 202087363 Felsőhatár utca street-housenumbers: 4480832206 Felső határút 36 1112 ref: felso hatar ut

**streetname-mapping.yaml** file szükséges arra az esetre ha eltér a különböző fájlokban az utcanév.

1. spanyoret:

felsohatar_utca:  {ref_name = "Felső határ út", numbers_name = "Felső határút"}

meghagynám ékzetetesen a ref_name, és numbers_name értékeket, ha ref-et kell áltani, a program konvertálja majd át simplified-ra ahol szükséges

Kapcsolódók
streets:
687957392	Felsőhatár utca

street-housenumbers:
373731059	Felső határút	2/C	1112	Sasad Resort 1

ref:
http://www.valasztas.hu/dyn/onepsz201610/map/telepulesek/budapest%20xi.ker./felso%20hatar%20ut/all.json

2. sashegy

Zólyom köz/Zólyomi köz
Zólyomi köz alatt vannak a házszámok, valamiért nem működik a mappelés

**Comment by vmiklos** [comment]
Jól értem, hogy itt két dolog kéne?

1. A jelenlegi leképezés buta, nem A-t kell B-be képezni, hanem ha a terület pl sashegy, akkor A legyen B.
2. A leképezés elég gyakori probléma, ne kelljen ehhez python kóba nyúlni, legyen yamlban.

**Comment by vmiklos** [comment]
Ja és még egy dolog: a sashegy példa nem jó, ebben az esetben az OSM DB is inkonzisztens (a way Zólyom köz, a házszámok Zólyomi köz, először ezt újra fel kéne mérni és kitalálni, hogy mi a jó).

Ez a mostani félkész megoldás ami az OSM név "Felsőhatár út"-hoz ref név "Felső határ út"-at rendel, ez melyik relációra érvényes? Utána akkor meg tudom nézni, hogy ez rendesen támogatva legyen.

**Comment by vasony** [comment]
1. igen, yaml szinten kellene, de latom mar elokeszitetted
2. Felsőhatár: írom fent: spanyolrét, de ott is különböző neve van a házszámoknak meg az utcának
3. Pont ezért jó példa a Zólyomi köz mert eltér a highway meg a number, nyilván felmérendő, de most jó tesztelni

ezért lett volna ez a struktúra:

spanyolret:
  osmrelation:
 ...
  streets:
     felsohatar_utca:  # highway neve
        ref_street = "Felső határ út"   # csv
        addr_street= "Felső határút" # addr:street

kérdés, nem lenne-e jobb helye a filterek között, ott a ranges: mellé jobban elfér, ott úgy is fel vannak sorolva az utcán, a relations-t meg megtartanánk rövidnek, ha itt sok relation lesz, akkor nem fogjuk tudni áttekinteni

  felsohatar_ut:
    ranges:
    - {end: '36', isOdd: 'false', start: '2'}
     ref_street = "Felső határ út"   # csv
     addr_street= "Felső határút" # addr:street

**Comment by vmiklos** [comment]
Oké, köszi, világos.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/669ef13d6e1ef730a8f7c827f9edacf4edb284e4

Ez a referencia generálás része. Egyelőre csak töröltem ezt a felsőhatárút dolgot, ezt ezt reláció-specifikusan akkor most már jól bele lehetne rakni. A zólyomos példa mégis jó lett, a mapillarys képek alapján az OSM DB egységesen az egyik nevet használja, a ref meg a másikat, szóval pont ezt akarjuk kezelni.

Azt bevettem az ötletedből, hogy ne egy yamlban legyenek ezek hanem a reláció saját yamljába, bár a szintaxis kicsit más lett (írtam kommentbe példát, hogy több elem esetén hogy néz ki). Remélhetőleg jó lesz ez így.

Kell majd még a másik része, hogy a suspicious_streets rész is kezelje az utcanév leképezést hasonló módon, különben ezekben az utcákban nem találunk semmit. (Addig az issue marad nyitva.)

**Comment by vasony** [comment]
Akkor mindkét írásmódot fel lehet venni? teszek egy próbát, rosszabb nem lesz :)

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/blob/master/data/housenumber-filters-sashegy.yaml#L77

Tetszőleges számú párt felvehetsz, mindegyik az OSM névből képez le a referencia nevére. Még megnézem este amit küldtél, de elsőre nem látok vele problémát, hogy több OSM név u.arra a ref névre képződik le.

**Comment by vmiklos** [comment]
A weboldal valahogy nem azt csinálja mint nálam helyben, hogy a /osm/suspicious-streets/sashegy/view-result talál Zólyom köz házszámokat, még nézelődöm, hogy mi a baja.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/sashegy/view-result

Jól van, megjelent a Zólyom köz, csak az újratöltést bénáztam el, úgy tűnik. Majd teszek valami verziót a láblécbe, hogy egyértelműbb legyen. :-)

**Comment by vmiklos** [comment]
Még mindig nem tökéletes, most meg a Zólyom köz 4-et se találja meg, pedig az megvan az OSM-en.

**Comment by vasony** [comment]
én nem látom a Zólyom közt a hibalistán

**Comment by vmiklos** [comment]
Na megvan, ez trükkös volt. :-)

https://github.com/vmiklos/osm-gimmisn/commit/c53139d544aec320966e964567a083530e34a327

Enélkül mindenütt a referenciára alakított utcanevekkel dolgoztam, ami hibás mikor overpass kimeneten megyek végig.

https://github.com/vmiklos/osm-gimmisn/commit/64ecc8511869512d5477ca95e1df7efab41d9bfe

Ez alantasabb volt, az aktuális könyvtár ha nem volt jó, akkor nem töltöttük be a leképezést.

Most már jó kell legyen a weboldal is.

**Comment by vasony** [comment]
a felső határút-hoz kell még valami? 
mert az nem jó még, nem jelenik meg a referenciában. (sem)

**Comment by vmiklos** [comment]
Hm, 'Felső határ út'-ra képezel meg, de TSV-ben nem szerepel ilyen utca. Hogy kéne ez menjen?

**Comment by vasony** [comment]
Felső Határ út

nagybetűvel van, javítom
