### ISSUE TITLE
Inaktív területek jelölése

### ISSUE THREAD

**Issue by vmiklos** [vmiklos/osm-gimmisn#161]
Van valamennyi ingyenes CPU használat kvóta (100 perc naponta azt hiszem) a PA instance-en ("a weboldalon"), utána belassítják a kiszolgálást. Pár napja ezt rendszeresen meghaladjuk, gondolom az elmúlt időben hozzáadott új relációk és a napi cronjob miatt.

Van erre több megoldás:

1. Az oldal így lassítva is használható, nem csinálunk semmit.
2. Inaktívnak jelölünk olyan területeket amik egyszer fontosak voltak (azért kerültek be), de alapvetően készen vannak, pocsékolás napi szinten monitorozni őket.
3. Más hostingot keresni ahol nincs ilyen kvóta / nem-ingyenes csomagra váltani.

Szerintem ebből a 2. a legjobb. Arra gondoltam, hogy először csak annyit csinálok, hogy lehessen inaktívnak jelölni területet, utána végigmegyünk a területeken és átnézzük őket. Jelenleg 63 reláció van, mondjuk ha a felét inaktívnak jelölnénk akkor az szerintem egy ideig elég.

(Engem most konkrétan pl a krisztinavároson kívül nem érdekel napi szinten semmi más, de nem kell ennyire drasztikusnak lenni.)

**Comment by vmiklos** [comment]
@vasony vélemény? Ha megcsinálom, hogy lehessen inaktívnak jelölni akkor hajlandó vagy kiírtani olyan relációkat amiket te vettél fel, de nem fontosak? (Célként mondjuk a fenti 50%os leépítést megjelölve, de lehet más is.)

Ilyesmire gondoltam, hogy ami inaktív azt a cron nem frissíti, főoldalon nem látszik, de mondjuk egy

https://vmiklos.pythonanywhere.com/osm/filter-for/all

azért mutatna mindent és lehetne is kézzel frissíteni.

**Comment by vasony** [comment]
Ha csak a frissítéssel van gond, akkor ahhoz mit szólnál, hogy a relation file-ban megadjuk a frissítési gyakoriságot napban? Default 0. Nézzük meg így mennyi a cpu.

Ugyanez, de legyen egy másik fájl, amiben ezeket leválasztjuk, akkor nem kell a filtereket piszkálni, és akkor meg lehet adni, hogy melyik mikor frissül

pl: cron.yaml
szentantalfa: {interval=0} # default
krisztinavaros: {interval=1}
kelenfold: {interval=1}
szentimrevaros: {interval=30, day=12} # minden 12. nap
szentimrevaros: {interval=7, day=1} # hetfonkent

btw: nekem van szerverem, vasony.hu mi kell ra? josz a meetupra akkor beszelhetunk rola.

**Comment by vmiklos** [comment]
> btw: nekem van szerverem, vasony.hu mi kell ra? josz a meetupra akkor beszelhetunk rola.

Lehet ez a legegyszerűbb, akkor egyelőre most nem lépek ezzel semmit csak nyitva hagyom, hogyne felejtődjön el. Végül is nem sürgős amíg nem panaszkodik valaki, hogy lassúúúúú. :-) De érzésre nem lassú, a lassítás után is 1-2 sec alatt betölt.

**Comment by vasony** [comment]
Ettől függetlenül, lehet hogy valamit szűrőt bele lehet tenni, hogy kevesebb terület legyen a terület a főoldalon. 

Van 1-2 terület ami nincs és valószínű nem is lesz scope-ban mostanában, de nem is akarom azért végleg letörölni: pl: felsotarkany, szilvasvarad, szentantalfa (itt az inaktív jól jönne, frissítés 0).

Aztán ott vannak a 100%-os területek, amiket nem kell állandóan frissítgetni, csak néha ránézni, hogy nem romlottak-e el. 
Ez utóbbival talán egyszerűbb kezdeni:
- átállíthatnád, hogy alapból a kész területek ne látszódjanak, tehát a https://vmiklos.pythonanywhere.com/osm/filter-for/incomplete lenne a default és a /all pedig kattintásra, a mostani szöveghelyén, itt még arra kell figyelni, hogy ha Budapestre szűrök, akkor is az incomplete jelenjen csak meg
- ha a terület 100%, akkor a cron nem futna rá csak minden elsején

**Comment by vmiklos** [comment]
Hülye vagyok, 100 (CPU) *másodperc*, nem perc jár ingyen. Szóval igen, valszeg akkor a tényleg a cronjob (ami 20 perc körül van, csak a nagy része hálózati várakozási idő) lesz az ami ezt elhasználja már reggelre.

Akkor csinálok majd ilyet, hogy lehessen inaktív, ami a frissítést kikapcsolja, de nem törli. Az oldalon megjelenítés az egyel bonyolultabb, lehet nem is kell még egy jó ideig ha csak a frissítést visszafogjuk. Thx az együtt gondolkodást. :-)

**Comment by vasony** [comment]
Lehet monitorozni, hogy hol tart a CPU használat?

**Comment by vmiklos** [comment]
Le lehet kérdezni, hogy hol tartunk most. Éppen ezt írja:

CPU Usage: You are in the tarpit. 100% used – 126.08s of 100s

Egyelőre megcsinálom, hogy lehessen inaktívnak jelölni, ami csak annyit csinál, hogy a cron nem fog automatikusan frissíteni. Utána lehet eldönteni, hogy mi legyen inaktív.

**Comment by vasony** [comment]
Be lehet tenni vmi rejtett oldalalra ezt az infót? mármint a cpu
használatot, vagy ez csak vmi admin oldalon jelenik meg?

Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. szept.
16., Hét 18:06):

**Comment by vmiklos** [comment]
Ja, ez csak a https://www.pythonanywhere.com/user/vmiklos/ alatt látszik. Viszont majd beszéljünk meetupon, ha látsz értéket abban,hogy az inaktív relációk is frissüljenek naponta akkor szívesen csinálok egy --all opciót a cron.py-nak és akkor pl egy nálad futó instance futtathatja azt naponta.

**Comment by vmiklos** [comment]
2abe223e0664a08750af98908189e4af0584bc31 a "saját" relációimból párat beraktam inaktívnak, ha tudsz olyanról amit te se követnél naponta és azt hasonló módon be tudod flagelni, azt megköszönöm. Mint látod, nem vagyunk sokkal a napi limit felett, ha mondjuk a relációk fele inaktív akkor teljesen jók vagyunk még egy jó ideig.

**Comment by vasony** [comment]
ezek szerint csak a következőn,  mert nem vagy itt :)

Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. szept.
16., Hét 18:20):

**Comment by vmiklos** [comment]
igen :)

**Comment by vasony** [comment]
beraktam még inaktívnak a vidékieket, bogács, keszthely plusz a sajátjaim jó részét

**Comment by vasony** [comment]
az install dokisban a linux-os rész elég hamar véget ér a make server-nél, és a windows alatt folytatódik a git-es lényeg, kicsit át tudnád szerkeszteni? Mert most nem tudom melyik részt is kell figyelembe venni egy linuxos telepítésnél.

**Comment by vmiklos** [comment]
Szinkronba hoztam a kettőt, ha még így se világos valami, szólj. De lényegében csak klónozod a repót, felteszed a függőségeket, make, make server, a többi csak sallang.

Az inaktív dolgokat köszi, meglátjuk holnap megmarad-e a limit alatt.

**Comment by vmiklos** [comment]
> CPU Usage: 64% used – 64.96s of 100s. 

Egyelőre megoldódott a dolog, keressünk bonyolultabb megoldásokat ha a nem-inaktív területek lesznek annyian, hogy csak ennyi trükközés nem elég.

**Comment by vasony** [comment]
Én még beletenném most, hogy a hónap elsején egy -all fusson le, ezzel vállalva, hogy aznap túllépjük.

**Comment by vmiklos** [comment]
Ja, ez jó középútnak tűnik.

**Comment by vmiklos** [comment]
^ kész :)
