### ISSUE TITLE
overpass query ha xml-t ad vissza, akkor ne frissítse, vagy próbálkozzon újra

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1664]
https://osm-gimmisn.vmiklos.hu/osm/streets/belso-ferencvaros/view-result

szerintem ha erre keresel, akkor kezelhető
```<p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.55_osm_base Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request. </p>```

**Comment by vmiklos** [comment]
Jogos

**Comment by vmiklos** [comment]
Bocs, elfelejtettem, hogy a github automagic a "resolves" kulcsszóra lezárja a bugot. :)

Lényeg, hogy a cron újrapróbálja az overpasst ha xmlt kap mostantól.
