### ISSUE TITLE
Referencia megtekintésének lehetősége

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#17]
Valahogy meg kellene oldani, hogy az adott relation referencia listáját
meg lehessen nézni (lst). 
pl:
/osm/suspicious-streets/farkasvolgy/view-query

**Comment by vmiklos** [comment]
Most már megy, pont ezzel a megnevezéssel amit írtál.

**Comment by vasony** [comment]
köszi, teszel még a tetejére egy last update dátumot?

**Comment by vmiklos** [comment]
Tettem. :-)
