### ISSUE TITLE
yaml checker: bezáratlan string

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#173]
Az alábbit nem jelezte hibának:
refstreets:
...
  'Tomori utca': Tomori Pál utca'

**Comment by vmiklos** [comment]
Tovább mennék: betöltés után ha az utca nevében ' vagy " marad, az hiba.

**Comment by vmiklos** [comment]
kész, a refstreets elemeinek mindkét oldalán a ' meg a " is most már hiba ha betöltés után benne marad.
