### ISSUE TITLE
street-housenumbers utcák figyelembe vétele

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#18]
Sajnos a várorrész határvonal nem mindenhol pontosan az utcán fut, viszont a házszámok már jók. azt javasolnám, hogy a street-housenumbers-ből is használjuk fel azokat az utcákat is amik nem szerepelnek a streets listában.

Konkrét példa az Örsöd részben az Alsó határút Budaörs és Budapest határán, a vonal az utca budaörsi oldalán fut. A streets-ben nincs, a street-housenumbers-ben van, ref-ben van.

**Comment by vmiklos** [comment]
Ezt azt hiszem megoldottam: https://vmiklos.pythonanywhere.com/osm/suspicious-streets/orsod/view-result Alsó határútra talál is egy hiányt.

> a street-housenumbers-ben van, ref-ben van.

Mondjuk más néven volt, így tettem rá leképezést, azért nézz rá, hogy erre gondoltál-e:

https://github.com/vmiklos/osm-gimmisn/blob/master/data/housenumber-filters-orsod.yaml#L55

**Comment by vasony** [comment]
Igen az Alsóhatár utca 5 elvileg az új 5 db ház, a terinfo.ujbuda.hu-n látszik, csak nincs rá kiírva. 
És a ref alapján is 5a,5b,5c,5d,5e épületek, ezek, csak ugye a forrás...
Az 1/c pedig rossz, javítom.(az utcának budapesti oldalon nincs neve a felső határúttal ellentétben)

**Comment by vasony** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/spanyolret/view-result

spanyolrét
itt most duplán van a felső határút mert nem tudod mappelni a jelenlegi struktúrában az osm streets és osm house numbert, ld. eredeti #16

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/fb1ea8e3c7fe26b395a3d71535a2ec4e97eb73a3

Szólj ha félreértelmeztem, ha jól értem az ötlet az, hogy több OSM-beli név u.azon a néven futhat a referenciában (de visszafele u.ez nem igaz). Tehát ha a filterek az OSM névvel dolgoznak, akkor minden jó lesz. Egyetlen filter volt ahol a két név eltért azt átírtam, most a

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/spanyolret/view-result

visszaállt az előző állapotra.

**Comment by vasony** [comment]
Közben gondolkoztam. Egyszerűen elnyomjuk az utcát a filterben egy üres range-el, és akkor jó lesz. A numbersben lévő formátumban meg marad a valóságos páros számok.

**Comment by vasony** [comment]
Még nem jó. 2est hibára hozza pedig van. Majd holnap még ragodunk.

Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. máj. 17.,
P 23:43):

**Comment by vmiklos** [comment]
Ez adatproblémának tűnik. :-)

A következők vannak megadva:
- housenumber-filters-spanyolret.yaml: 'Felsőhatár utca' -> 'Felső Határ út' leképezés
- streets-spanyolret: van ilyen utca, hogy Felsőhatár utca
- street-housenumbers-spanyolret: 0 Felsőhatár utca házszám (mert ugye Felső határút néven futnak)
- a referenciában Felső Határ út néven futnak

Ezek alapján szerintem jogosan hiányolja mind a kettest, mind a többit. A valós helyzetet úgy lehetne leírni, hogy a 'Felsőhatár utca' -> 'Felső Határ út' leképezést törlöd, nem is világos, hogy ez miért került bele. (A 'Felső határút' -> 'Felső Határ út' már leírja a spanyolret oldalát, a másikat majd valami Budaörsi relációhoz kéne csak felvenni, nem?)

**Comment by vasony** [comment]
Igen, közben megálmodtam én is, hogy jó lesz így, azért nem látszik semmit,
mert fel van véve az összes házszám, majd letörlöm a 36-ot próbából.
Eddig azért volt benne a másik, mert nem voltak benne a házszámok a
listában és ez a leképezés rendelte össze a ref-el.

**Comment by vasony** [comment]
Átírtam a 36-ot átmenetileg, és megjelent, úgyhogy működik.

**Comment by vasony** [comment]
QA-ra is jó, király lett.
egyből kihozott 2 kisbetűs utcát Terézvárosban :)
