### ISSUE TITLE
validator szóljon ha space van a szám után

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1815]
chatből:
ez lesz az: data/relation-balatonalmadi-budatava.yaml:36:      - {start: '18', end: '198    '}
egy issue-t megerne, hogy a validator szoljon erte ha kesobb megis baj a space a 198 utan

**Comment by vmiklos** [comment]
Jogos

**Comment by vmiklos** [comment]
@vasony  lehet tesztelni, ha akarod :)

**Comment by vasony** [comment]
nem akarom :)
