### ISSUE TITLE
főoldal: utca lefedettség frissítési dátum nem jó

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#183]
suspicious-relations: only típusnál nem jó a frissítési dátum a főoldalon. ld budapest 01-nél 1970, de a többi is szerintem a véletlenül legenerált hiányzó házszámos dátumot veszi.

most nézem ,hogy a többi "utca lefedettségnél" se jó a dátum, pl. biatorbagy

**Comment by vmiklos** [comment]
Azt hiszem erre a wsgi részre is kellenek majd tesztek. ;-)

**Comment by vasony** [comment]
Ha sok időd van... Ha hibás úgyis szólok :)
