### ISSUE TITLE
statisztika: irányítószám szerinti lefedettség

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1839]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/cityprogress mintájára
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/zipprogress

ugyanaz a logika mint a városonkénti lefedettség, csak nem városra hanem irányítószámra kell grouppolni

először kell hozzá a #1838

**Comment by vmiklos** [comment]
Bennevagyok

**Comment by vasony** [comment]
Ahogy néztem a város lefedettség statisztikának külön generáltam referenciát (varos_count*), akkor ezt most megtettem az irányítószámokra is: irsz_count_20211113.tsv

Egyelőre még 10000 cím hiányzik belőle, de ezzel neki lehet indulni a fejlesztésnek.

**Comment by vmiklos** [comment]
Köszi, jó lesz ez. Két részre lehet bontani a feladatot:

1. a cron gyártson a napi osm adatból .zipcount file-okat
2. a webes felület diffelje az általad adott referenciával

**Comment by vmiklos** [comment]
elkészült, lehet tesztelni

**Comment by vasony** [comment]
Vettem a 1112-es irányítószámot, és nekem is ezek a számok jöttek ki mint a statisztikában, zárható
