### ISSUE TITLE
Accept-Language támogatás

### ISSUE THREAD

**Issue by vmiklos** [vmiklos/osm-gimmisn#187]
Szeretném ha az oldal annak megfelelően beszélne angolul vagy magyarul, hogy hogy van beállítva a böngésző. Ez így gondolom nem bosszantana senkit, aki magyarul szeretni látni a UI-t az vélhetőleg már a böngészőjét is így állította be.

Kis szépséghibája a dolognak, hogy ezt szerintem csak úgy lehet megvalósítani, hogy először végigmegyek a kódon és *ideiglenesen* visszaírok mindent angolra, majd ez után jöhet a lokalizáció pl. gettext segítségével.

**Comment by vmiklos** [comment]
@vasony ellenvetés? :-)

**Comment by vasony** [comment]
Nekem mindegy milyen nyelvű :-) viszont arra figyeljünk, hogy a sort magyar maradjon akkor is ha angolra van állítva a nyelv. 
Mondjuk nekem pont angolra van állítva böngésző..

**Comment by vmiklos** [comment]
Ja, a sort locale-t nem akarom piszkálni, ez csak a stringeket érinti.

**Comment by vmiklos** [comment]
4ba3ce7ab2339fac6455c4cde07a8ff0a62ddfa8 óta a stringek meg vannak jelölve fordításra. Ezzel most az egész angol lett, de a következő lépés, hogy az accept-language alapján a magyar config esetén megint magyar legyen a felület.

**Comment by vasony** [comment]
vkit megkérünk, hogy átnézze az angolt? mert kicsit hungrish.

**Comment by vmiklos** [comment]
Nem vagyok semmi jónak az elrontója. :-)

**Comment by vasony** [comment]
@bkil légyszi fusd át az angol szövegeket az oldalon, hogy angolosabb legyen

**Comment by vmiklos** [comment]
Hmm, helyben működik, a PA instance-en viszont minden angol. Még keresgélek. ;-)

**Comment by vmiklos** [comment]
Mukodik! \o/

**Comment by bkil** [comment]
Hétvégén megpróbálom beütemezni, de mindig itt van @meskobalazs is ha nem jön össze!

**Comment by vmiklos** [comment]
Azóta a doksi is kétnyelvű lett:

- https://github.com/vmiklos/osm-gimmisn/tree/master/doc/ az angol
- https://wiki.openstreetmap.org/wiki/WikiProject_Hungary/osm-gimmisn a magyar

Ha van kedvetek + időtök hozzá, akár nyelvi, akár egyéb tartalmi javításokat szívesen veszek hozzá.
