### ISSUE TITLE
Házszámtartományok leképezésének támogatása

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#188]
Hasznos funkció lenne, ha a feldolgozó támogatná az X-Y típusú házszámokat, és ha több szám is beleesik az [X; Y] tartományba, akkor azt megtaláltként érzékelné, vagyis ilyesmi leképezéshez kellene támogatás: 2-12 → 2, 4, 6, 8, 10, 12

Példa erre a [Budafoki Szomszédok Piaca](https://www.openstreetmap.org/way/391305097), amelynek címe Játék utca 2-12. A feldolgozó jelenleg hiányzó házszámként tünteti fel a 4, 6, 8, 10 számokat.

**Comment by vasony** [comment]
támogatom, nekem is emiatt kell egy csomó filter csinálni

**Comment by vmiklos** [comment]
> Viszont az interpolation: 'all'-t is figyelni kell az ilyen leképezésnél.

Ez még hiányzik, addig nyitva hagyom az issue-t.

**Comment by vasony** [comment]
Van egy mellékhatása a dolognak, hogy leképezzük a köztes házszámokat mint referencia. Ha nem pontosan úgy vannak a tartományok mint a refben, akkor lesznek új hiányzók. Valószínű az üzleteket érinti elsősorban.

Pl. Budafoki út 209-215 van a refben, a térképen a 209 és 215 volt megadva, így nem volt hiány.
Viszont most kijön hibának a 211, 213 is. Jobban megnézve persze kiderül, hogy a Shell kút házszáma 209-215, ezt megadva el fognak tűnni a hiányzók.

**Comment by vasony** [comment]
@vmiklos Deák Ferenc tér 4-5 most nem jól megy, ez az interpolation: all típus, írtad nincs meg, lehet tesztelni majd vele. Meg van adva de mégis hiányzóra fut. (belvaros)

https://www.openstreetmap.org/node/6789202176
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/belvaros/view-result.txt
Deák Ferenc tér	[5]

**Comment by vasony** [comment]
még egy gond, a köztes generált házszámok nem veszik figyelembe a filtereket.

  Rátz László utca:
    ranges:
      - {start: '10', end: '76'}
      - {start: '80', end: '82'}
      - {start: '86', end: '86'}

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenfold/view-result.txt
Rátz László utca	[78, 84]

ref: Rátz László utca 72-86

**Comment by vmiklos** [comment]
> még egy gond, a köztes generált házszámok nem veszik figyelembe a filtereket.

Ez még hiányzik, addig nyitva hagyom az issue-t.

**Comment by vmiklos** [comment]
Azt hiszem minden megvan. Ha nem, akkor csináljatok hozzá másik follow-up issue-t, nem vagyok jó a sok probléma <-> 1 issue követésében. :-)
