### ISSUE TITLE
referencia lista frissítése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#19]
Referencia (lst) fájlok kézi frissítésének lehetősége.
Ehhez nem kell overpass lekérdezés, csak menjen végig még egyszer a már meglévő streets listán-n (és a numbers-en is, #18 ) és állítsa össze az lst fájt még egyszer. 

Akkor válik szükségessé ha az overpass eredménye bővült, de már korábban legenerálódott az .lst file. pl. a logika megváltozott, vagy valaki pontosította a kerület határokat.

Akár automatán is mehetne, mert ha már el van cache-elve a valasztas.hu-rol a lekérdezés eredménye utcánként, akkor valójában http kihívás csak a még le nem kérdezett utcákra lesz.

Jelenlegi problémák:
- terezvaros: Lehel utca
- magasut: Adorján út

**Comment by vmiklos** [comment]
A https://www.pythonanywhere.com/whitelist/ az overpasst explicite engedi, de mást nem. :( Amúgy menne a dolog.

**Comment by vmiklos** [comment]
Befrissítettem az összes referenciát kézzel (beleértve a fent emlegetett kettőt), illetve beraktam alá a cache-t, szóval hibát nem fog adni ha csak úgy kattingat a user. Ha pedig ténylegesen le akarna tölteni valamit, arra hiba lesz, de legalább a régi lista nem veszik el. Egyelőre legyen az, hogy kommentelj ide ilyen esetben.

**Comment by vasony** [comment]
Akkor eddig a localban állt elő a file és felmásoltad? Nem tudom hogy van összekötve a GitHub es ez.
Ez már csak azért is szívás mert találtam hiányt a return,majd megírom.

**Comment by vmiklos** [comment]
Jaja, a referenciát kézzel töltöttem alá. Majd még lehet, hogy nézelődöm, elképzelhető esetleg, hogy az osm.hu-ra át lehetne tenni a weboldalt, vagy ilyesmi.

**Comment by vasony** [comment]
Van valami automata frissítés most rajta? 
Mert főoldalon sasad 93%, rákattintok, aloldalon 94% és a tooltipben már látszik hogy frissült.

**Comment by vmiklos** [comment]
A főoldalon a legutóbbi futás eredménye van, tehát az előfordul, hogy rámész és kicsit változik.

Amúgy pedig köszi a tsv-segítséget, most már az a refrencia, így teljes értékűen tudsz magadnak generálni új referenciát ha szükséges. (Sasadnál kb 10 sec, és az eredmény megegyezik azzal amit eddig kézzel alá raktam.) Ha mégse, szólj.

**Comment by vasony** [comment]
Szét van dobva megyénkét, vagy felindexeli?
Vagy le van greppelve, mi a módszer?
Pl. egy 20-as megyekódnál is ilyen gyors?

**Comment by vmiklos** [comment]
Itt a kód:

https://github.com/vmiklos/osm-gimmisn/blob/master/get_reference_housenumbers.py#L114

> Szét van dobva megyénkét, vagy felindexeli?

Egyelőre mindig beolvasom az egészet, de építek belőle egy szótárat memóriában, utána már indexelt a keresés.

> Vagy le van greppelve, mi a módszer?

A szótárat úgy építem, hogy végigolvasom az elejétől végéig.

> Pl. egy 20-as megyekódnál is ilyen gyors?

Nem próbáltam, de elvileg majdnem konstans az idő, hiszen minden területhez végigolvasom az elejétől végéig, utána pedig csak a szótárban kereséssel a házszámig jutok.

(Ha később ez túl lassú, akkor lehet bonyolítani, hogy sqlben legyen a dolog, de egyelőre ez így jónak tűnik.)
