### ISSUE TITLE
Házszámtartományok leképezése #188 kapcsán

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#193]
#188 
Retek utca 21-2700 A-t nem kellene felbontani (orszagut), és még van pár ilyen

Szabályok Kossuth utca a-b

1) b > 1000 akkor kihagyjuk a közteseket
2) b-a > 24 , akkor szintén kimaradnak a köztesek, végignéztem kb jó a szám egy pár maradt ami ezen túl van de nem biztos, hogy azok valid számok. ha később kell, akkor majd paraméterből feloldjuk a yamlban.
3) ha a = 0, szintén kimarad a feloldásból ha nem szűrnénk ki

Volt még egy issue, de az megjavult
4) b<a: Schweidel utca 17-10  típusból a második szám nem kell, de úgy tűnik ezt magától tudja már.

**Comment by vmiklos** [comment]
Jogos, most látom, hogy krisztinavarosban is pl 482 hiányzó házszám lett egy 20-2200 miatt a referenciából.

**Comment by vasony** [comment]
A 2) -es pont a #195 függényében, ha az kifejlesztésre kerül, akkor ez nem kell.

**Comment by vmiklos** [comment]
Ez azt hiszem kész.
