### ISSUE TITLE
Házszámtartományok megjelenítése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#195]
Kicsit nagyobb lélegzetű meló, de célszerűbb lenne a tartományok megjelenítése a hiányzó házszám oldalon,ez segítené a helyszííni térképezést, hogy mit is keresünk, illetve a ref megbízhatóságát is könnyebb eldönteni, egy 11-35 típusnál.
Ez egyszerűnek hangzik, de a megvalósítás már bonyolultabb.

Most ezt látom:
**Kalotaszeg utca	[25, 27, 29, 31, 31\*, 33, 35, 37]**

A ref érintett szakasza:
Kalotaszeg utca 25
Kalotaszeg utca 27-37
Kalotaszeg utca 31*

Ehelyett ezt szeretném látni:
**Kalotaszeg utca	[25, 27-37, 31\*]**

A megvalósítást így képzeltem el:
- Az hiányzó házszám eredmény megállapításán nem változtatnék, az maradna a mostani logika
- Amikor sorra kerül egy házszám kiírása, akkor mielőtt kiírnánk megnéznénk, hogy létezik-e önállóan (pl Kalotaszeg utca 31), ha igen kiirjuk. Ha nem létezik, akkor megkeresnénk hozzá a range-et amiből jött, és azt írnánk ki helyette (Pl. Kalotaszeg utca 33 helyett 27-37).
- Kezelni kell, hogy 2x ne íródjon ki ugyanaz a range, pl. a Kalotaszeg utca 35-nél

Technikailag nem tudom, hogy lehet megoldani úgy hogy ne kelleje 2x felolvasni a ref-et.

**Comment by vmiklos** [comment]
Tovább bonyolítja a dolgot, hogy a tartományokat jelenleg nem csak a ref hanem az osm adatból is "kifejtjük" (2-6 -> 2, 4, 6) mert utána aránylag könnyű összehasonlítani. De amúgy persze, lenne értelme.

**Comment by vasony** [comment]
Azért írtam ,hogy a keresési algoritmus marad, tehát az mindegy hogy kifejtjük, ez már csak a megjelenítést érinti a keresést/összehasonlítást nem.

**Comment by vmiklos** [comment]
(Lesz még sok commit, látható eredmény meg csak a végén.)

**Comment by vmiklos** [comment]
Ezt azt hiszem kész. :-)

**Comment by vmiklos** [comment]
Ja igen, ennek lett egy olyan mellékhatása, hogy ha a refben pl 7/a volt, akkor azt a megjelenítés normalizalta 7-re, most viszont a 7/a-t mutatom. De ez sztem jó dolog.

**Comment by vasony** [comment]
Szuper, köszi, szerintem is jó.
Most a 7/a 7/b is hiányzik, akkor csak az egyik jön fel ugye?

**Comment by vmiklos** [comment]
Hmm, ezt most így fejből passzolom. :-) Annyit csinálok, hogy kijön, hogy "1", "2", "3" a hiányzó házszám, akkor ezekre most már tudom, hogy ez mondjuk egy "1-3"-ból jött, és a több "1-3"-ra fut egy unique sort, hogy csak 1x adja ki.

Eddig nem tudom mit csináltunk, ha a 7-et eddig 1x írtuk ki (de rákeresve, nem látom, hogy eddig csak 1x írtuk volna ki, explicit unique sort erre nem fut le), akkor sztem most is csak 1x lesz, mivel a házszámra mikor hasht számolunk (ami eldönti, hogy a unique sort mit dob el), akkor csak a "7"-et vesszük figyelembe, azt nem, hogy 7/a-ból vagy 7/b-ből jött.

Szóval ha gyakorlatban előjön és nem jó, akkor írj példát és ránézek.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/keszthely/view-result

Vaszary Kolos utca: refben 47/A és 47/B van, én meg csak a 47/A-t dobom fel. Közben megtaláltam, a __get_ref_housenumbers()-ben van egy set(), amiatt. ("sorted(set("-re keresve nem találja meg.) Szóval a kérdésedre igen a válasz.

**Comment by vasony** [comment]
ok. a meglévők és a hiányzók száma is drasztikusan csökkent, gondolom a uniqe dolog miatt, vagy hogy már a 72-74 csak 1-nek számít? Hogy számolod?
pl:
2019-11-01 23:20	OpenStreetMap nem tartalmazza a lenti 11 utcához tartozó 77 házszámot. (meglévő: **1053**, készültség: 93.19%)

2019-11-10 02:42	OpenStreetMap nem tartalmazza a lenti 11 utcához tartozó 72 házszámot. (meglévő: **1037**, készültség: 93.51%)

**Comment by vmiklos** [comment]
Így van, 2-10 egynek számít, nem tűnt logikusnak, hogy a szamossag páros utcánál 5, de csak 1 stringet írunk hozzá.
