### ISSUE TITLE
validátor nem fogta meg az üres filtert

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1950]
https://github.com/vmiklos/osm-gimmisn/pull/1948/commits/25742637c7d8a33c8a10304789cf758f829dbb7c

ennek nem szabadott volna átcsúsznia, összeomlott tőle az oldal

ez volt:
```
  Moha köz:

  Moha utca:
    # 4-6: csak 4 van kiírva
    # 33: 31 után 35
    invalid: ['6', '33']
```

**Comment by vasony** [comment]
Belső hiba a / kiszolgálása során
our_application() failed

Caused by:
    0: failed to parse 'relation-budapest_12.yaml'
    1: invalid type: null, expected struct RelationFiltersDict

**Comment by vmiklos** [comment]
Megnézem mit tehetek

**Comment by vmiklos** [comment]
Megtalálja a hibát, de az exit code 0, az a baj.

**Comment by vmiklos** [comment]
lehet tesztelni

**Comment by vasony** [comment]
megfogta a hibát, bár nem látszik mi az

**Comment by vmiklos** [comment]
ott van az csak kicsit fel kell görgetni:

https://github.com/vmiklos/osm-gimmisn/runs/4633439252?check_suite_focus=true

```
Error: while parsing a block mapping, did not find expected key at line 69 column 3

Caused by:
    while parsing a block mapping, did not find expected key at line 69 column 3
make: *** [Makefile:136: data/yamls.cache] Error 1
make: *** Waiting for unfinished jobs....```

**Comment by vasony** [comment]
úgy értem, hogy melyik fájlban van a hiba.

**Comment by vmiklos** [comment]
ja látom. előbb próbálja meg az összes .yaml file-t cache-elni, és ott nem írja a filenevet. most már igen:

```
target/debug/cache_yamls data workdir
Error: serde_yaml::from_str() failed for /home/vmiklos/git/osm-gimmisn//data/relation-budaors-hegyvidekek.yaml

Caused by:
    0: while parsing a block mapping, did not find expected key at line 69 column 3
    1: while parsing a block mapping, did not find expected key at line 69 column 3
make: *** [Makefile:136: data/yamls.cache] Error 1
```

ezt kapom helyben a #1957 után ha a b3dc911aff80bc1daa99f48ee2172122d76c74a2 -t revertelem helyben
