### ISSUE TITLE
Lefedettség statisztika csak Budapestre

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#2009]
A statisztikák oldalon az utolsó sávdiagram az OSM-en lévő házszámok készültségi arányát mutatja a referenciához képest. Ez egy kicsit demotiváló, hogy csak tizenakárhány százalékon áll. Jó lenne egy ugyanilyen diagram csak a budapesti házszámokra, mert:

- Budapesten tevékenykedik az aktív házszámozók többsége
- Budapesten van a referenciában lévő házszámok nagy része
- Reális esély van arra, hogy megközelítsük vagy elérjük a 100%-ot
- További motiváció lehet a 100% eléréséhez, ha látszik, hogy gyorsan nő és nem sok hiányzik már

Szerintem a többi diagramból nem kell csak budapesti változatot csinálni, de ebből az egyből jó lenne.

**Comment by vmiklos** [comment]
Lehet róla szó, 01-es megyére kell szűrni a referenciában, 1-es irányítószámra az osm magyar polygonban. És akkor a jelenlegi adatok alapján lehet számolni.

Azért a 100%ba ne éld bele magad, a statisztika nem bajlódik a szülőkkel, de a közel teljes lefedettség az jó cél :)

**Comment by vasony** [comment]
a statisztika érdeméből nem von le, de a mostani aktivitást nézve, ezek is tized százalékok lesznek

Budapest:
2020.07.01: 29,01% 
2021.01.01: 33.06%
2021.07.01: 38,42%
2022.01.01: 39,87%

**Comment by vmiklos** [comment]
Két részre lehet ezt osztani: 1) stats.jsonban legyen ilyen infó 2) a statisztika oldal mutassa.

**Comment by vmiklos** [comment]
A fentivel még csak a 1) készült el.

**Comment by vmiklos** [comment]
Elkészült, lehet tesztelni:

https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/#_capital-progress

@vasony érdekes, nekem kicsit kisebb százalék jött ki. Hogy számoltál?

Én a refdir/varosok_count_20220113.tsv budapest_ sorait szummázom, és hasonlítom össze a workdir/stats/2022-01-22.citycount budapest_ sorainak szummájával.

**Comment by vasony** [comment]
01-11-én nálam  85221/ 213229, összeadtam a budapesti területek számai, de még megnézem miért tér el ennyire.ú
valószínű azért mert nálam az egyik területben van `housenumberletters` stat a másikban meg nincs ezért kevesebb nálam a nevező. illetve a filterek.

**Comment by vasony** [comment]
Számláló:
Ez nem jön ki, gondlom ebben van már némi szűrés, mert nálam 97017-re jön ki ha a 2022-01-22.csv-t nézem.

Nevező:
Stimmel, db-ben megselectáltam úgy hogy 11 és 22. kerületben teljes házszám, a többiben csonkolja a betűt, akkor jön ki az én számom kb. (212206) Illetve ha nem trükközök, akkora te számod 256378, ez így teljesen valid.

Lesz majd egy ugrás a mostani ref-nél, ami hamarosan várható.

**Comment by vasony** [comment]
A unique lemaradt a countból nálam, most stimmel, részemről zárható.
