### ISSUE TITLE
Suspicious relations tag default

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#201]
meg kellene változtatni a default értéket no-ról.
Ha refmegye>01 akkor yes. Ha 01 akkor no marad.
most a balatoni területeknek csak azért kellene filter hogy ezt is bekapcsoljuk.

**Comment by vmiklos** [comment]
Vagy akár lehet fixen yes, csak beleírni a doksiba, hogy rész-település reláció esetén tipikusan no-t akar az ember. "Mindent kézzel kell" vs "túl sok varázslat" trade-off. :-)

**Comment by vmiklos** [comment]
Ja még az jutott eszembe, hogy a parser a relations.yaml-ban megadott kulcs-érték párokat meg a relation-foo.yamlban megadott kulcs-érték párokat u.úgy kezeli, tehát ez csak konvenció, hogy a suspicious-relations az a relation-foo.yamlban van megadva, nem közvetlenül a relations.yaml-ban, lehetne úgy is.

De ettől függetlenül nincs gondom a default átállításával.

**Comment by vmiklos** [comment]
Majd még le kell ellenőrizni, hogy mi van azokkal a relációkkal amiknek nincs saját relation yaml file-ja, utána mehet a default átírása.

**Comment by vmiklos** [comment]
Ez azt hiszem kész, a =yes sorokat most akár lehet is törölni, ha valaki akarja.

**Comment by vasony** [comment]
https://vmiklos.pythonanywhere.com/osm/filter-for/refmegye/14

szigetmonostornál nem kellene %-nak lennie?

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/blob/master/data/relation-szigetmonostor.yaml#L1

Ha azt az első sort törlöd vagy átírod, akkor lesz szerintem. :-)

**Comment by vasony** [comment]
nálam nem volt, most látom hogy belecsempészted közben a default 'no'-kat ahol nem volt :-)
