### ISSUE TITLE
Megye filter bővítés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#202]
Főoldalon a Megye filert bővíteni kellene.  Pest megye mellett a többi is kellene ami létezik a relations.yamlban.
Ehhez kell egy refmegye.yaml vagy más paraméter file amiben a Megye kódok es nevek szerepelnek.

**Comment by vmiklos** [comment]
Jogos, jó lenne ezt kiszervezni configba.

Addig is amúgy, a helpers.py legalján van egy refmegye_get_name(), abban egy sima python dictionary, az mondja meg, hogy az adott számú megyének mi a neve. Ebbe nyugodtan berakhatsz új értékeket. Ha elszúrod a szintaxist, akkor szól a CI. (Attól még maradjon így ez az issue, szebb lesz configban.)

**Comment by vmiklos** [comment]
Hmm, érdemes erre is írni ellenőrzőt? Maga az eredeti kérés kész.
