### ISSUE TITLE
Budapest kerület filter

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#204]
Már régebben írtam, de akkor még kevesebb jelentősége volt, mert nem tömtem teli a configot városrészekkel.

ideális így lenne a 11. kerületre szűrés
https://vmiklos.pythonanywhere.com/osm/filter-for/refmegye/01/011
persze lehet így is, csak így nem elég egzakt, persze belül még mehetne ugyanúgy, hogy csak Budapest-et szűri, merta többinek nem sok értelme
https://vmiklos.pythonanywhere.com/osm/filter-for/reftelepules/011

első körben elég a filter-for-t implementálni, aztán megoldani, hogy a Budapest szűrésnél megjelenjenek a kerület számok, helpersben beállított kerületekre

**Comment by vmiklos** [comment]
Ja, egy megyét tovább szűkíteni településre hasznos lenne.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/filter-for/refmegye/01/reftelepules/011

Majd csinálok hozzá kattintható linkeket is.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/filter-for/refmegye/01

A megyéhez hasonlóan azokat a "településeket" írjuk ki amiknek van neve, az új nevek a data/reftelepules-names.yaml file-ból jönnek. Ha van rá igény, nyugodtan bővítsd.
