### ISSUE TITLE
Hamzsabégi út 39

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#206]
Hamzsabégi út:
    interpolation: 'all'
    ranges:
      - {start: '22', end: '37'}
      - {start: '41', end: '64'}

Ennek ellenére megjelenik hiányzó házszámnak a 39.
#188

**Comment by vmiklos** [comment]
Ez nem jó, meg fogom nézni mi történik itt.

**Comment by vmiklos** [comment]
Nézem, de nem látom. :-)

Ez a filter a data/relation-kelenfold.yaml alatt van, de a https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenfold/view-result alatt nincs Hamzsabégi út.

Ez azóta megoldódott?

**Comment by vasony** [comment]
úgy tűnik valamelyik frissítés megoldotta.
