### ISSUE TITLE
Denevér köz 5-6

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#211]
Ez nem kerül be a meglévő házszámokhoz mert paritás nem egyezik:
https://www.openstreetmap.org/way/319228269

tudom, hogy baromságnak tűnik ez a házszám, de ez van kiírva.

ilyen esetben ha a < b de a paritás nem stimmel, akkor nem kell felbontani, de legalább mindkét tag kerüljön be. 

5-6: 5 és 6
11-2: 11

**Comment by vmiklos** [comment]
A "csak mindkét tag kerüljön be" volt a régi szabály a tartományok kifejtése előtt, szóval egyszerűen erre is kell egy tiltó feltétel.

**Comment by vmiklos** [comment]
Nem írtad, hogy melyik relációnál jött elő, de a helyzet elég egyértelmű + tesztet is írtam erre, szóval ez szerintem készen. De ha frissítés után nem oldódik meg akkor írj linket, hogy hol van még mindig gond. :-)

**Comment by vasony** [comment]
Írjál tesztet a 11-2 típusra is légy szíves.

**Comment by vasony** [comment]
itt jó:
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/martonhegy/view-result#

sajnos ahogy sejtettem itt nem:
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/gellerthegy/view-result
Schweidel utca 17-10

ld #193 4-es pont nem lett implementálva, mert impicit működött

**Comment by vmiklos** [comment]
Ja látom, jogos.

**Comment by vmiklos** [comment]
Schweidel utca eltűnt a fenti linkről, azt hiszem ez kész.
