### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#213]
Mi volt a cél? 
Desktopon nagyon rossz lett, most állítottam hogy desktopon maradjon az eredeti, de jó lenne ha tudnám mit akarunk elérni.

#212

**Comment by vmiklos** [comment]
Elsősorban csak az zavart, hogy mobilon a font méret nem fix, mint desktopon. Ezt a <head> részbe tett tag meg is oldotta, a többi csak jónak tűnt, de nem ragaszkodom hozzá. Nyugodtan szedd ki teljesen a CSS rule-t; annyira nem lényeges. (Ennyi volt csak az ötlet, hogy pl itt a githubon is az issue commentek nem használják ki a teljes szélességet, hanem van egy maximum a szélességre, talán így könnyíti az olvasást, de annyira nem gondoltam végig.)

Kiszeded a CSS rule-t vagy csináljam meg én?

**Comment by vmiklos** [comment]
![image](https://user-images.githubusercontent.com/13838/65822422-ee49a200-e243-11e9-8714-3094486ff870.png)
így nézett ki a head nélküli rész nélkül, a max szélesség az igazából lényegtelen

**Comment by vasony** [comment]
ahogy érzed, nekem már jó így :)
