### ISSUE TITLE
timestamp helyett human readable

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#22]
(updated on 2019-05-06T20:15:07.707063) timestamp helyett jobb lenne a CET időzóna szerint jobban olvasható formátum, pl: 2019-05-06 22:15 vagy 2019.05.06. 22:15

**Comment by bkil** [comment]
Ezen már én is gondolkoztam. Az lenne a legjobb ha a mai dátumokra csak az óra:perc jelenne meg, a régebbiekre pedig az év-hónap-nap!

**Comment by vmiklos** [comment]
Azt is figyelembe kell venni, hogy a szerver időzónája lehet CEST vagy UTC vagy bármi más. Szerintem az lenne a legjobb ha configban meg lehetne adni, hogy Europe/Budapest legyen a timestamp kimenet, és a többit konvertálnánk. tzlocal és pytz alapján talán össze lehet rakni valamit amit megoldja ezt.

Ha lehet elkerülném az egész DST és időzóna dolog saját kezelését. :-)

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/street-housenumbers/gazdagret/view-result

Most itt rányomtam, hogy frissítse be overpassból, és "Frissítve 2019-05-20 21:31"-et ír, ami a Bp-i időnek felel meg.
