### ISSUE TITLE
Felmérendő utcák letöltése GPX formátumban

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#224]
Jó lenne vizuálisan is megjeleníteni azokat az utcákat, amelyek még felmérendőek, azaz hiányzó házszámokat tartalmaznak. Ez lehetne GPX formátumban, napi frissítéssel. A GPX fájl eltárolható az adott napra, hogy ne kelljen minden alkalommal lekérni.

Próbálkoztam Overpass turbóval, és ez a fajta lekérdezés jó eredményt ad:

```
(highway=residential or heightway=tetriary) and (name="Utcanév 1" or name="Utcanév 2" or name="Utcanév N") in Terület
```
Például 3 utca lekérése Budafokon:

```
(highway=residential or heightway=tetriary) and (name="Katona utca" or name="Anna utca" or name="Kehely utca") in Budafok
```

Az első zárójelben fel kell sorolni az összes lehetséges úttípust, a második zárójelben pedig azokat az utcákat, amelyek még felmérést igényelnek. Az eredményt GPX-ként elmentve be lehet tölteni OsmAnd-ba, így láthatóvá válik, hogy hova kell menni.

**Comment by vmiklos** [comment]
Majd annak is utána kell járni, hogy pontosan az overpass-turbo mit küld az overpassnak, általában neveket a nyers overpass nem fogad el, előbb a név -> ID konverziót kell csinálni. A dolog pozitív része, hogy ezek a way id-k már megvannak nekünk, nem kell külön a nominatimtól lekérdezni őket.

Ja és a gpx generálás is hasonló: ha a turbo csinálja, akkor meg kell nézni, hogy hogyan. (Feltehetőleg JS-ből csinálja, mi meg nem akarunk nem-kényelmi funkcióra JS-t, hanem server-oldalon, valószínűleg.)

**Comment by vasony** [comment]
Lehet első körben elég lenne, hogy legenerálná az overpass query-t, ami be lehet másolni, és mindenki lefuttatja magának.

**Comment by vmiklos** [comment]
Ez is jó ötlet. Mindenesetre a http://overpass-api.de/output_formats.html amit mi használunk, ott közvetlenül gpx nincs.

**Comment by vmiklos** [comment]
Közben találtam ilyet:

https://wiki.openstreetmap.org/wiki/Overpass_turbo/Development#Query

A wizard nekünk nem lesz jó, mert a relációk nevét nem tudjuk, de a query verzió jó lehet. És akkor lehetne a /osm/suspicious-streets/budafok/view-result tetejére kirakni egy linket, ami egyből futtatja is a query-t, aminek az eredményét lehet menteni gpxbe.

**Comment by vmiklos** [comment]
https://wiki.openstreetmap.org/wiki/WikiProject_Hungary/osm-gimmisn#Halad.C3.B3bb_t.C3.A9m.C3.A1k itt megpróbáltam ledokumentálni, de a lényeg:

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/budafok/view-turbo

Itt van naprakész query, ezt overpass-turbóba bemásolva készíthető GPX. Azt hiszem ez készen van.

**Comment by vasony** [comment]
Ez nem akartad kilinkelni a fejlécre? 
Mondjuk szerintem nem kellene rá fejléc/lábléc, mert akkor crtl+a-val ki lehetne jelölni.

**Comment by vasony** [comment]
Ja látom, egyel lejjebb van, a doksit elolvastam :)

**Comment by vasony** [comment]
> 
> 
> Ez pár utcára jó lenne, de HTTP GET-ben nem lehet túl sok utcát megadni, pl Budafokra nem fut már le. Szóval maradni fog a Tamás által javasolt query generálás + átmásolás.

Postttal nem lehet egy oyan html textboxba, mint amibe most gépelem ezt a szöveget?

**Comment by vmiklos** [comment]
A UX nem az erősségem, de arra gondoltam, hogy azért jobb ha van rajta fejléc, mert akkor az overpass-turbó URL-jét nem kell megjegyezni, hanem ott van a toolbaron, onnan nyitható, és alul meg a query. Kicsit lábbal hajtós, de egyelőre megteszi.

HTTP POST-ot én is néztem, de "overpass turbo http post"-ra keresgélve nem nagyon találtam megoldást. De ezt static htmllel te is ki tudod próbálni, csinálj egy formot, link helyett egy gombot, ami gombnyomásra az overpass-turbónak valahogy beadja a query-t. Ha megy, akkor u.ezt tudom én is dinamikusan generálni. :-)

**Comment by vasony** [comment]
Nem megy sajnos, most próbáltam, get-ből erőlködik, postból nem vesz át semmit.

**Comment by vasony** [comment]
Kellene még annyi módosítás, hogy a buszmegállókat ne töltse be
nwr helyett szerintem elég a way úgyis utcákat keresünk

pontok biztos nem kellenek
relation-t néztem
tökvésznél nincs relation
budafokon van 1 de az is public transport, nem kell
nagytéténynél, budaörsnél szintén nincs relation

**Comment by vasony** [comment]
+ ki kell egészíteni, hogy a relation határán lévő neveket is hozza fel, ahogy az utcáknál csináltuk.

Pl: Felhévízi utca nem jelenik meg Szemlőhegynél

```
[out:json][timeout:425];
rel(3174398)->.searchRelation;
(
way(r.searchRelation)["name"="Felhévízi utca"];
way(r.searchRelation)["name"="Repkény utca"];
);
out body;
>;
out skel qt;

```

**Comment by vmiklos** [comment]
Tehát akkor minden utcára:

````
(way["name"="..."](area.searchArea);
way(r.searchRelation)["name"="..."];
````

Jól mondom?

**Comment by vasony** [comment]
valószínű igen, de a zárójel mehet mögé is, hogy egyforma legyen

én úgy próbáltam hogy az egész kupacot még egyszer a végére tettem

**Comment by vmiklos** [comment]
Ha már kipróbáltad, írj már ide egy teljes példát 1 vagy 2 utcával kérlek :-)

**Comment by vasony** [comment]
```
[out:json][timeout:425];
area(3603174399)->.searchArea;
(way["name"="Felső Zöldmáli út"](area.searchArea);
way["name"="Barlang utca"](area.searchArea);
way["name"="Csejtei utca"](area.searchArea);
way["name"="Zsindely utca"](area.searchArea);
way["name"="Alsó Zöldmáli út"](area.searchArea);
way["name"="Szépvölgyi út"](area.searchArea);
way["name"="Zöldmáli lejtő"](area.searchArea);
way["name"="Pusztaszeri út"](area.searchArea);
way["name"="Csatárka út"](area.searchArea);
way["name"="Zöldlomb utca"](area.searchArea);
way["name"="Ferenchegyi lépcső"](area.searchArea);
way["name"="Csalit utca"](area.searchArea);
way["name"="Lívia utca"](area.searchArea);
way["name"="Zuhany utca"](area.searchArea);
way["name"="Ferenchegyi út"](area.searchArea);
way["name"="Törökvész út"](area.searchArea);
way["name"="Pitypang utca"](area.searchArea);
way["name"="Zöldkert út"](area.searchArea);
);
out body;
>;
out skel qt;
rel(3174399)->.searchRelation;
(way["name"="Felső Zöldmáli út"](r.searchRelation);
way["name"="Barlang utca"](r.searchRelation);
way["name"="Csejtei utca"](r.searchRelation);
way["name"="Zsindely utca"](r.searchRelation);
way["name"="Alsó Zöldmáli út"](r.searchRelation);
way["name"="Szépvölgyi út"](r.searchRelation);
way["name"="Zöldmáli lejtő"](r.searchRelation);
way["name"="Pusztaszeri út"](r.searchRelation);
way["name"="Csatárka út"](r.searchRelation);
way["name"="Zöldlomb utca"](r.searchRelation);
way["name"="Ferenchegyi lépcső"](r.searchRelation);
way["name"="Csalit utca"](r.searchRelation);
way["name"="Lívia utca"](r.searchRelation);
way["name"="Zuhany utca"](r.searchRelation);
way["name"="Ferenchegyi út"](r.searchRelation);
way["name"="Törökvész út"](r.searchRelation);
way["name"="Pitypang utca"](r.searchRelation);
way["name"="Zöldkert út"](r.searchRelation);
);
out body;
>;
out skel qt;
```

**Comment by vasony** [comment]
Itt van kombinálva 1 utcára
```
rel(3174399)->.searchRelation;
area(3603174399)->.searchArea;
(way["name"="Felső Zöldmáli út"](r.searchRelation);
way["name"="Felső Zöldmáli út"](area.searchArea);
);
out body;
>;
out skel qt;

```

**Comment by vmiklos** [comment]
Elvileg megvan, írjatok ha ez így nem jó.
