### ISSUE TITLE
Házszám előtti felelsleges karakterek

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#2270]
Balatonszemesen megjelentek a következő **páros** házszámok: `/759`, `/774`

A Matrix-csatornán történt beszélgetés alapján a 774 és a 759 az első szám a stringben, az előtte lévő szemét eldobásra került. A következő kérdések merülnek fel:

1. Ha egy házszám string nem számmal kezdődik, akkor az tekinthető-e valós házszámnak? Ha nem, akkor az egészet dobni kellene, ha igen, akkor a megtalált első string valószínűleg hibás eredményt fog adni.
2. Gyakorlatban kezdődhet-e egy házszám nem számjeggyel? Ha nem, akkor mindent el kellene dobni az elejéről, ne kezdődjön `/` jellel a feldolgozott érték.

**Comment by vasony** [comment]
Ez referencia hiba, szerintem nem gimmisn oldalon kell kezelni

**Comment by vasony** [comment]
Lakótelepeknél van olyan házszám hogy A/1.
@vmiklos Ezeket nem tudom hogy a gimmisn tudja-e kezelni, ha nem, akkor inkább leírtom őket. (253 db, de ebben van szemét is)

**Comment by vmiklos** [comment]
Alapvetően nem tudja kezelni. A megközelítés az, hogy a házszám egy string, az elején számmal, utána esetleg valami szeméttel. Illetve ha külön kéred, akkor az egyszerű (a-z) vegzodesekkel még kezdünk valamit.

Ez alapján az is jó ha a /rel kezdődő hazszamokat kiszűröd a referencia ok, de emellett az is jogos, hogy a /abc meg a /123 mindkettő 0 kéne legyen ha szűrni akarod. Talán legjobb a kettő együtt.

Az hogy a "/123" most 123, semmiképpen se szándékos.
