### ISSUE TITLE
Fejléc menü link nem jó (overpass hívás)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#234]
"Frissítés Overpass hívásával másodpercekig tarthat" nem kattintható

`<a osm="" street-housenumbers="" kelenfold="" update-result="">Frissítés Overpass hívásával</a>`

**Comment by vmiklos** [comment]
Oops. Itt látható pl:

https://vmiklos.pythonanywhere.com/osm/street-housenumbers/krisztinavaros/view-result

**Comment by vmiklos** [comment]
Ha megvan a fix, akkor is maradjon nyitva ez az issue:

- akarok rá tesztet írni
- még nem végeztem a hiányzó html escape-ek átnézésével, ha valamit még elrontok, az jöhet ide

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/4a355b15389b03e8dc0fb92b68fff81f517ae352

Ez a vége, elkészült a mű.

**Comment by vasony** [comment]
Jó sokat kellett vackolni
