### ISSUE TITLE
Meglévő házszámok/utcák oldalon legyen link az osm objektumra

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#237]
Legyen kattinható az első oszlopban a szám

https://vmiklos.pythonanywhere.com/osm/street-housenumbers/gellerthegy/view-result

252077556 | Alsóhegy utca | 3
[252077556  ](https://www.openstreetmap.org/way/252077556) mutasson a https://www.openstreetmap.org/way/252077556 objektumra (új ablakba nyissa ki)

Kérdés, hogy hol tudjuk megfogni, hogy node way vagy relation jön, ehhez lehet az overpass query-t is át kell írni, mert most is csak tippelek.

**Comment by vmiklos** [comment]
Egyértelműen az overpass querybe kell valahol pár mágikus szót beleírni. :-) De tetszik az ötlet, nem is hiszem, hogy nehéz.

**Comment by vmiklos** [comment]
::id mintájára a ::type is megy \o/

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/street-housenumbers/gellerthegy/view-result kattintható, a többi is jó lesz ha lefut a napi cron.

Amúgy minimális munkával (csak az overpass queryt kell átírni) a létező utcák oldalt is lehetne linkesíteni ha valakit érdekel.

**Comment by vasony** [comment]
A meglévő utcákra is kiterjeszted?

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/streets/gellerthegy/view-result kattintható, többit majd megszereli a cron holnapra.
