### ISSUE TITLE
UX: kevesebb link & infó a főoldalon

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#24]
Valami olyasmire gondoltam a főoldalon, hogy:

    Where do you want to map today?
    Csillebérc [47% complete]
    Terézváros [68% complete]
    ....
    See [the guide|...#Új_reláció] if you'd like to add a new area to this list.

(A távolabbi jövőben egy százalék szerint színezett térképen lennének a linkek, MVP-ben akár egy statikusan update-elt PNG feletti img mapon)

Innen a linkek a view-result oldalra vinnének. Ott pedig az oldalon pedig a jelenlegi suspicious-street/view-result tartalma lenne, felette egy plusz link sávba ágyazva a többi információnkat (a linkek streets/house number view-result-ra vinnének):

`Click to see [all streets] and [house numbers] already mapped in OpenStreetMap in this neighborhood.`

Alatta a törzset valahogy így fogalmaznám meg:

    OSM may be missing some house numbers in the following 12 streets
    (74 house numbers missing from 142).
    See [the guide|...#Hibás_riasztás_hozzáadása] if you see a false alarm.
    21 Konkoly-Thege Miklós út
    [...]
    12 Magas út
     ....

A streets és house numbers view-result oldalának fejlécébe raknék hivatkozást a view-query és rerun query oldalakra (még az is lehet, hogy a view-query oldalon belül raknám a rerun query-t, hogy még kevésbé kattintsanak félre).

`Data updated: 2019-05-06. [Click to update using overpass] (may take a few seconds) [See update query]`

Rád bízom, hogy mi milyen nyelven lesz.

Vélemény?

**Comment by vmiklos** [comment]
Ha a doksira linkelünk akkor szerintem jobb ha a UI is magyar. A többivel nem látok semmi problémát ha meg is csinálod. :-)

A jelenlegi UI az pont olyan ahogy egy programozó elképzeli 0 gondolkodással, szóval csak jobb lehet.

**Comment by vasony** [comment]
támogatom, illetve adok egy 2. verziót

szerintem jó lenne az egészet egy táblázatba tenni, hogy a %-ok egymás alatt legyenek, és én mellé tenném a frissítés dátumát.
illetve meghagynám a relation-re mutató osm linket (nem ragaszkodom hozzá)
pl:

1. verzió
| Csillebérc                 | 47% | 2019-05-06 |
| Hosszúnevűrelation | 68% | 2019-05-06 |

2. verzió
| Csillebérc                 | 47% | 2019-05-06 | hiányzó házszámok | utcák  | házszámok |
| Hosszúnevűrelation | 68% | 2019-05-06 | hiányzó házszámok | utcák  | házszámok |

maradnék a magyarnál, elsősorban nekünk készül, a frissítés maradhatna az aloldalon az update mellett
Data updated: 2019-05-06. [Click to update using overpass]

**Comment by bkil** [comment]
Nos, akkor kezdjük a második verzióval - az a kevesebb munka és még mehetünk tovább az első irányába.

A táblázatot támogatom, bár ha nem baj egyelőre table-tr-td lesz fapadosan.

A terület relation link jó ötlet, tényleg kimaradt. Viszont a főoldalon a névre linkelni kicsit félreérthető, így inkább máshová raknám, akár az aloldalra (hogy melyikre azt még nem tudom, vagy az összesre vagy az utcásra és hiányzó házszámosra). Már csak azért sem linkelném, mert ez az első szó amit meglátnak és sokan rá akarnak kattintgatni, de mi a hiányzó házszámokra szeretnénk terelni a látogatókat elsősorban, nem relation-re. Valójában a meglevő utca/házszám is másodlagos, de mivel az később szerepel, az kevéssé viszi el a fókuszt (bár egy kicsit elviszi az is).

Valószínűleg az aloldalak egymásra is linkelhetnének.

A frissítés dátuma nem rossz ötlet, bár kicsit zavarosítja az áttekintést. Vagy az aloldalra raknám, vagy tooltipbe. Ez egyébként is "csak" egy technikai információ - elvileg az a backend belügye, hogy mit mennyire cache-el, és akár naponta (hetente?) tudnánk frissíteni a háttérben. Illetve mivel a frissítésre amúgy is csak az aloldalon van lehetőség, ezért ott relevánsabb ez az információ. Azt meg jó lenne nem elvárni a látogatóktól, hogy kézimunkával kattintgassák végig a táblázat alapján a régi dátumú kimeneteket pár naponta ahogy erre járnak.

    | Csillebérc | 47% kész | meglévő utcák | meglévő házszámok |
    | Hosszúnevű | 68% kész | meglévő utcák | meglévő házszámok |

**Comment by vmiklos** [comment]
Meg lehet csinálni az automatikus frissítést csak okosan kell. Ha ész nélkül lefuttatod az összes overpasst lekérdezést, akkor a többség nem fog lefutni mert kitilt a szerver. Ha viszont túl sokat sleepelsz közöttük akkor meg nagyon sokáig tart. Ezért van ez jelenleg, hogy kézzel kattingatunk.

**Comment by vmiklos** [comment]
A doksinak jelenleg 3 része van: 1) optimális eset mikor csak overpasst kell futtatni felmérés után 2) hiányzó terület 3) false positive.

A 2) és 3)-ra linkelünk most de az 1)-re nem, https://github.com/vmiklos/osm-gimmisn/tree/master/doc/hu#hi%C3%A1nyz%C3%B3-h%C3%A1zsz%C3%A1mok-naprak%C3%A9sz-list%C3%A1ja lenne a link. 

@bkil ha van ötleted, hogy ezt hova lehetne belinkelni, szerintem érdemes lenne. Sikerült egyből a problémákra fókuszálni (mit tegyél, hogy jobbá tedd a szolgáltatást), nem arra, hogy hogy használja a user. :-)

**Comment by bkil** [comment]
A főoldalra egy első bekezdésként lehetne linkelni, és/vagy a suspicious oldal tetején. Valami olyasmi szöveget tudnék elképzelni, mint `"Tudnivalók a szolgáltatásról"`, `"Segítség a használathoz"`, `"Bevezetés"`, `"Első lépések"`, `"Tutorial"`...

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/934f09eead6d4073431ebeb80f37a2c0c9a5937c

Ha már a főoldal alján volt link, akkor odaraktam ezt is, a "Segítség a használathoz" tetszik, köszi.
