### ISSUE TITLE
Meglévő házszám=0 kezelése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#241]
nádorkert 0/0-s, mert a ref nem ismeri még, pedig már vannak számok.
Aloldalon N/A%, de a főoldalon "hiányzó házszámok link" jelenik meg a % helyett

Szerintem csalhatunk, nyugodtan tekinthetjük 100%-nak ha a meglévő házszám=0, mert nincs vele teendő, úgyszólván kész van.

**Comment by vmiklos** [comment]
Legyen, végül is a 0-val való osztásról nem érdemes vitatkozni. :-)

**Comment by vmiklos** [comment]
Elkészült.
