### ISSUE TITLE
refstreets: 1 utca 2 név (Rezső tér)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#252]
Alap probléma, hogy Rezső térnek 2 új neve lett, ld. alább.

- Utca oldalon
https://vmiklos.pythonanywhere.com/osm/suspicious-relations/budapest_08/view-result

OSM
Magyarok Nagyasszonya tér
Szenes Iván tér

REF:
Rezső tér
Magyarok Nagyasszonya tér
Szenes Iván tér

Szerintem exception-re fut, mert a Nagy Fuvaros utca-t sem találtja meg utána, pedig most már jó van mappelve.

Mondjuk így valószínű el tudjuk nyomni a Rezső teret, de benne hagyom, hogy kiderüljön ilyenkor mi van.

- Házszám oldalon
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/budapest_08/view-query
(így lehet meghágni a suspicious-only felületet :-) )

Itt most nincs issue, mert A Rezső téri házszámok a Magyarok Nagyasszonya tér-hez tartoznak és a másik fele újra lett számozva ahogy nézem a nagy testvérnél:
https://www.google.hu/maps/@47.4802402,19.0947456,3a,22y,310.96h,96.69t/data=!3m6!1e1!3m4!1scqic07AL5EeQi7sBvjWvlA!2e0!7i13312!8i6656

**Comment by vasony** [comment]
persze lehet megoldás a wontfix, ha túl bonyolult kezelni és nem éri meg, de legalább ne szálljon el.

**Comment by vmiklos** [comment]
Az 1:N reláció melyik irányban kell itt? 1 név az OSM-ben, és azt akarjuk megadni, hogy ez a referenciában 2 névnek felel meg, ugye?

**Comment by vasony** [comment]
Mind a kettő lehet, de itt most 1 név a referenciában és 2 név az osm-ben. A másik irány szerintem megy.

**Comment by vmiklos** [comment]
Hmm. Azért kérdezem, mert pont a másik irány szerintem a problémás. Lásd például data/relation-sashegy.yaml, az osm név az egyedi kell legyen (az a kulcs), de 2 OSM nevet simán fel tudsz venni és ugyanarra a ref névre képezed le.

Pontosan mit jelent a "ne szálljon el"? (Értsd: valami ilyesmit írj: lépés1, lépés2, lépés3, ez történik, ennek kéne történnie. :-) )

**Comment by vmiklos** [comment]
Ok, így konkrét példával érthetőbb, maradjunk az elsőnél. A ref-ben van Rezső tér is meg Magyarok Nagyasszonya tér is. Az osm -> ref utca leképezés azt mondja, hogy az OSM-es Magyarok Nagyasszonya tér az a ref-ben Rezső tér lesz. Ez után viszont az összehasonlításkor az OSM-es Magyarok Nagyasszonya tér Rezső térnek számít, tehát mikor a ref-ben előjön a Magyarok Nagyasszonya tér, azt hiányzónak mutatjuk.

Ebből nekem az jön le, hogy mégis a másik irány kéne ide, hogy van 2 név a referenciában (Rezső tér, Magyarok Nagyasszonya tér), ami 1 név az OSM-ben (Magyarok Nagyasszonya tér). Jól gondolom?

Szenes István tér dettó. Nagy Fuvaros utca szintén.

Megoldásként ilyesmire gondoltam. Ez van most:

````
refstreets:
  'Magyarok Nagyasszonya tér': 'Rezső tér'
````

Ehelyett az kéne, hogy meg lehessen adni, hogy a Magyarok Nagyasszonya teret nem *lecserélni* akarod Rezső térre, hanem ilyen néven *is* fusson. Például így:

````
refstreets:
    'Magyarok Nagyasszonya tér':
        refname: 'Rezső tér'
        additive: 'yes'
````

Tehát marad a string-string map, de ha additívet akarsz, akkor az érték string helyett egy map, ahol a név mellett meg tudod adni, hogy ezen a néven *is* fusson az OSM-beli név (az összehasonlítás szempontjából). Vélemény?

**Comment by vasony** [comment]
Ja már értem, 2 van mindegyikből a mapppelt meg az eredeti. ennyit munkát nem ér az utca rész, mert arra elég hogy megnézzük jó e így is. ha a házszámnál is lesz gond, akkor újra nyitom.
