### ISSUE TITLE
új területekre a cron mindenképp fusson

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2592]
cron futtassa meg az új területet (ha még nem volt egyszer sem) akkor is ha az inactive: false

ld. Polgár

**Comment by vmiklos** [comment]
Lehet róla szó. Kézi teszt: ha az `ls workdir|grep -w polgar` üres, akkor az `osm-gimmisn cron --mode relations --refcounty 09 --refsettlement 062` először végig kell menjen Polgáron, de másodszorra már nem.

**Comment by vmiklos** [comment]
@vasony szeretnel ezen valamit tesztelni?

**Comment by vasony** [comment]
nem
