### ISSUE TITLE
Rename `*.expected-data` to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [vmiklos/osm-gimmisn#2628]
… as suggested in https://github.com/vmiklos/vmexam/issues/10:

> `*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*
> 
> I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.
> 
> Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by vmiklos** [comment]
I don't really mind either way, but clearly .expected-data is a silly extension, so why not.

**Comment by vasony** [comment]
If you change the naming convention of any part of the data directory, will break the 7.2 version.
Need some ln -s, or backport

**Comment by vmiklos** [comment]
This is just for testcase data, it should be fine, I think.
