### ISSUE TITLE
Betűs házszámok kimaradnak, ha a normál rögzítve van

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#267]
A probléma: a program csak a számot nézi, így ha már van egy egyező házszám, akkor a betűs bontását nem dobja fel hiányzónak.

Példa: Kertész utca
OSM-en szerepel: 1 - https://www.openstreetmap.org/way/300597173
Referenciában szerepel:
- Kertész utca 1
- Kertész utca 1/C

Látható a térképen, hogy a Kertész utca 1-től délre lévő épületnek nincs házszáma, az lesz a Kertész utca 1/C, viszont a hiányzó házszámok listájában nem ajánlja fel a program.

Javaslat:
Maradjon meg a mostani ``ranges`` szűrő a YAML fájlban, így a tartományokon kívül eső házszámok nem érdekesek. Viszont a tartományon belülre eső *összes* házszám jelenjen meg hiányzóként, és ha egy házszám nem valós, akkor azt egy külön szűrővel dobjuk.

Példa: tegyük fel, hogy a referenciában ilyenek házszámok lennének:
1, 3, 5, 7, 7/A, 7/B, 9, 9 AB, 11, 11 ABC, 151, 153
Ezt így szűrnénk ki:
`{start: '3', end: '11'}` ami kidobná a nem létező 1, 151, 153 számokat
`invalid: ['9 AB', '11 ABC']` ami kidobná a nem létező 9 AB és 11 ABC számokat
A megjelenített hiányzó házszámok listája így ez maradna:
3, 5, 7, 7/A, 7/B, 9, 11

**Comment by vmiklos** [comment]
Kicsit ingoványos terület ez. Ugye a házszám szám kéne legyen, de a gyakorlatban örülök neki ha ez legalább egy olyan string aminek az elején szám van, aztán mindenféle szemét.

Ettől függetlenül megvalósítható a dolog: most a HouseNumber az 2 dolgot követ: egy 2-10 range feldarabolódik 2, 4, 6, 8, 10-re, de mindegyik tudja, hogy 2-10-ből jön. Ez úgy megy, hogy a "-" mentén darabolunk, és ha a "2" az "2a" lenne, akkor a "2" utáni részt eldobjuk. Ezt ki lehetne terjeszteni, hogy a 2 meg a "2a-10" mellett a "2a" is tárolódjon, és ezt is vegyük figyelembe amikor megy a unique sort a kimenetre.

Viszont mielőtt bármi lenne, el kéne dönteni, hogy akarjuk-e ezt. @vasony korábban kérdezte itt:

https://github.com/vmiklos/osm-gimmisn/issues/195#issuecomment-552235030

"Most a 7/a 7/b is hiányzik, akkor csak az egyik jön fel ugye?"

Ez úgy hangzik, mintha pont jó neki a mostani viselkedés. Szóval jussunk egyetértésre itt, hogy akarunk-e ilyesmit, aztán lehet nekiesni a hakkolásnak.

(Nekem nagyjából mindegy, talán hajlok egy kicsit arra, hogy nagyobb bajunk is van jelenleg a lefedettséggel mint az 1 vs 1/a jellegű problémák.)

**Comment by vasony** [comment]
Nekem tetszik az ötlet, csak nagyon át kell gondolni a megvalósítást. Szerintem elég nagy meló rendesen megcsinálni,

Az invalid filter ezen kívül is tetszik, mert ha csak 1 számot kellene kiszűrni, akkor most bénázni kell a range-el, ez azt is megoldaná, ez lehetne implementálni először.

Mivel a referenciában nagyon sok a szemét, elírás, mindenképp legyen állítható, hogy akarunk-e ilyen viselkedést a körzetre / utcára vagy sem, és először csak egy 100%-os körzetre állítsuk be, hogy tesztelhető legyen a viselkedése.

Ezzel valószínű a mostani 100%-os körzetek is leromlanak, de legalább nem fogok unatkozni.

Példák a ref-ből
Sasad, csak hogy egyszerűbb legyen:

**pl 1:**
**Brassó út 138**
Brassó út 138-14
Brassó út 138-140
Brassó út 138-140 A

OSM-en 138, 140 külön, akkor fel fogja hozni hibának az utolsó 3-at, de ha külön van?

**pl 2.** 
ez rengeteg invalid filtert fog jelenteni, vastaggal a validok, a többi kuka

a problémák amit látok
+ osm 69-179dII vs. ref 169-179 D2 (a spacek leszedése, ignore case, ignore /, római to arab fv)
+ működési sebesség? (cache?)
+ a text kimenethez hasonló felület, ahonnan copyzható legyen egy utca invalid egyszerűen, most: [19, 21 A] filterben meg ['19', '21 A'] kellene. most levágjuk az aposztrofokat, amit én kértem.



Brassó út 165-179 F
Brassó út 166-179 D2
Brassó út 167-179
Brassó út 169
Brassó út 169 A
Brassó út 169 A 1
Brassó út 169 B
Brassó út 169 C
Brassó út 169 E
Brassó út 169 F
Brassó út 169 H
Brassó út 169-177
Brassó út 169-178
Brassó út 169-178 A1
Brassó út 169-179
Brassó út 169-179 1
Brassó út 169-179 1 D
Brassó út 169-179 6
**Brassó út 169-179 A**
Brassó út 169-179 A 1
Brassó út 169-179 A A1
Brassó út 169-179 A B
Brassó út 169-179 A C
Brassó út 169-179 A1
Brassó út 169-179 A1 2
**Brassó út 169-179 B**
**Brassó út 169-179 C**
Brassó út 169-179 C D
Brassó út 169-179 C E
Brassó út 169-179 D
Brassó út 169-179 D 1
Brassó út 169-179 D 2
Brassó út 169-179 D D
**Brassó út 169-179 D1**
**Brassó út 169-179 D2**
**Brassó út 169-179 E**
**Brassó út 169-179 F**
**Brassó út 169-179 G**
**Brassó út 169-179 H**
Brassó út 169-179 H 2
Brassó út 169-179A
Brassó út 169-179B
Brassó út 169-179D
Brassó út 169-179F
Brassó út 169/179 H
Brassó út 169/179 H 4
Brassó út 169/A
Brassó út 169/B
Brassó út 169/C
Brassó út 169/D
Brassó út 169/E
Brassó út 169/F
Brassó út 169179 H
Brassó út 1698-179
Brassó út 1698-179 G

**pl 3.**
Most nincs példám, de:
REF-ben 2-10, valóságban 2,4,6,8,10 ,mert a bejártatok vannak számozva nem a ház egyben.

Akkor ezt hiánynak fogjuk feltüntetni, odamegyünk, közben valójában ott vannak a számok. Ha invalidra tesszük, akkor nem fog megjelenni, viszont a statisztikát csorbítja, mert 5-el kevesebb házszám lesz.

**Comment by vasony** [comment]
> (Nekem nagyjából mindegy, talán hajlok egy kicsit arra, hogy nagyobb bajunk is van jelenleg a lefedettséggel mint az 1 vs 1/a jellegű problémák.)

igen, ezzel egyetértek, sokkal alacsonyabb %-aink lesznek és nagyon részletekbe megyünk, sok meló kiszűrni a szemetet. de az ki be kapcsolhatósággal ezt elvileg megoldjuk, default a mostani viselkedés maradna.

**Comment by vmiklos** [comment]
Hmm. 2 rész zavar ebben nagyon:

1. osm 69-179dII vs. ref 169-179 D2 -- ezt meg lehet csinálni, de ritkán jól jön és elég sok macera
2. 169-179 B -- ezt meg egyszerűen képtelenség eldönteni megbízhatóan, hogy "(169-179) B"-ként vagy "169-(179 B)"-ként kell-e értelmezni. Local knowledge-ből tudom, hogy előbbi, de fordítva is lehetne.

Amint engedek akár csak egyetlen betűt a szám mögött egy " " vagy "/" szeparátorral, ilyen "179 B"-k meg fognak jelenni false positive-nak, amik eddig nem voltak.

Hajlok arra, hogy jobb kevesebb hintet adni a térképezőknek, de azok legyenek jogosak, mint többet, amit aztán sok munkával ki kell szűrni. (Relation szinten opt-in tényleg lehet egy megoldás, de még akkor is kétes az egész.)

**Comment by vasony** [comment]
Mi lenne, ha első körben csak a legegyszerűbbekkel foglalkoznánk, és a dupla házszámok logikáját nem bántanánk? Szigorúan csak a 99a 99/a típusúakat engednénk be, egységesen. 90% úgyis ilyen.
Én is jobban szeretem a fontolva haladunkat.

169-179 D2 maradna úgy ahogy eddig, minden levágódna a végéről.

A példánál maradva
1, 3, 5, 7, 7/A, 7/B, 7a, 7b, 9, 9 AB, 11, 11 ABC, 13, 13-15, 13-15 B

Eddig
1, 3, 5, 7, 9, 11, 13, 13-15

Új logika szerint (egységesítve)
1, 3, 5, 7, 7/A, 7/B, 9, 11, 13, 13-15

**Comment by vmiklos** [comment]
Oké, az opt-in && csak "99a", "99/a" és "99 a" && tartományoknál ne szűkítéssel ez jobban vállalható.

**Comment by vasony** [comment]
invalid: ['15a'] legyen a formátum egységesen, szűrje ki a 15 a, 15/a, 15A-t.

**Comment by vmiklos** [comment]
Legközelebb ez is megérne egy saját issue-t. :-) De mostmár hagyd, mindjárt megnézem. (Először ezt, a https://github.com/vmiklos/osm-gimmisn/issues/267#issuecomment-553385335 sincs elfelejtve, de az nagyobb falat.)

**Comment by vmiklos** [comment]
@vasony a tesztjeim alapján ez megvan, de azért majd valami életszagúbb helyzetben próbáld is ki. :-)

Marad nyitva, az eredeti problémához még nem nyúltam hozzá.

**Comment by vasony** [comment]
> @vasony a tesztjeim alapján ez megvan, de azért majd valami életszagúbb helyzetben próbáld is ki. 
működik.

**Comment by vmiklos** [comment]
@urbalazs elkészült, ha gondolod budafokra kapcsold be. :-) (`housenumber-letters: true` a `data/relation-budafok.yaml` végére.) Egyelőre csak a mesterséges gh267 relációval teszteltem.

> Ezzel valószínű a mostani 100%-os körzetek is leromlanak, de legalább nem fogok unatkozni.

@vasony ha unatkozol, nyugodtan kapcsold be más relációra is, de szerintem csak egyesével érdemes, ha van energia a kihulló csontvázak javítására is.

**Comment by vasony** [comment]
ok, akkor kezdjük madárhegyen :-)

**Comment by vasony** [comment]
nem gondoltam volna, hogy pont a mi házunk jön ki, mint invalid, ezt egyszerű ellenőrizni  :-)

**Comment by vmiklos** [comment]
Nézd végig, false positive is lehet benne...

**Comment by vasony** [comment]
Igen nézem majd, egy része biztos az, mint ahogy a mienk is.
A története az ,hogy a szomszéd ilyen bénán jelentette le a cégét, csak mert G épület ki van írva, de az nem a házszám része csak az építtető jónak látta betűvel ellátni az épületeit, és gondolom nem egyedi eset.
Láttam saját szememmel is az önkormányzatnál a lakcímnyilvántartóban, amikor kálváriát jártam a gyerek születésénél a lakcímkártyámmal....
