### ISSUE TITLE
invalid tag implementálás a filterek közé

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#269]
#267 -ből áthozva

invalid: ['9', '11'] kidobná a nem létező 9 és 11 számokat, nem kell range az egyszerűbbekre.

**Comment by vmiklos** [comment]
És akkor ez a ranges szűrés után futna le, azt tovább szűkítve.

**Comment by vasony** [comment]
A sorrend mindegy, ugyanaz az eredmény, mehet utána is.

**Comment by vmiklos** [comment]
Ja, közben rájöttem én is. :-)

**Comment by vmiklos** [comment]
Ez azt hiszem kész.
