### ISSUE TITLE
yaml-filter isOdd propery automatikus megállapítása ha nem szerepel

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#27]
@bkil ötlete alapján isOdd: 'true', isOdd: 'false' kiirtása a filterekből.  Magától találja ki 
mod(start,2) alapján

yaml check
+ ki kell venni a yaml checkből
+ mod(start,2) == mod(end,2) ellenőrzése
+ end >= start ellenőrzése

folyamatos házszámozású utcákat most hagyjuk a távoli jövőre, de megoldhatók azok is páros páratlannal.

**Comment by vasony** [comment]
@vmiklos ez tud lenni a következő, legalább az true/false megállapítás, mert már nem előszőr rontom el

**Comment by vmiklos** [comment]
Úgyis gyereknap van az oviban, legyen itt is. :-)

**Comment by vmiklos** [comment]
Kivettem, a start páros/páratlansága alapján automatikusan állapítja meg.

@bkil emlegette, hogy egyébként is írna saját (python) yaml lintert ami többet tud ellenőrizni, majd abba lehetne ilyen nyalánkságokat, hogy az end páros/páratlansága u.az legyen, illetve, hogy az end ne legyen kisebb, mint a start.

**Comment by bkil** [comment]
Így van, tervezek. Készítek egy Scala változatot, de a Python átiratot az olvasóra bízom. ;-)
