### ISSUE TITLE
Helyrajzi számok szűrése egyesével

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#2728]
vmiklos:

> A validator a / után nem enged több számot, de sztem ezt lazítani kéne, jogos az igény, hogy hrszeket lehessen szűrni egyesével is.

Jelenleg az 1234/12, 1234/23 stb. hrsz-eket csak a `1234` szűrővel lehet kiszűrni, amely az összes 1234 kezdetű hrsz-t kiszűri, így nincs lehetőség egyesével szűrni azokat. Ezen lehetne lazítani.

**Comment by vmiklos** [comment]
Hm, túl hamar hirdettem eredményt. A doksibol:

> Az egytagú betűjelet és számot megtartja (47a, 47/a, 47 a, 47/1), a többit levágja (47/abc).

Szóval jó az, hogy nem engedi a validator a tobbtagut, mert amúgy is az egyszerűsített formát kell megadni a /12 vég esetén.

**Comment by vmiklos** [comment]
Egyelőre nem szükséges
