### ISSUE TITLE
numeric sort nem megy rendesen - interpolation all

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#274]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/lipotvaros/view-result#

Itt rossz
Szabadság tér | 6 | 10, 11, 15, 17, 5-6, 8-9 (ezt közben eltüntettem)
Széchenyi rakpart | 3 | 12/B, 3, 6
Szent István tér | 4 | 17-18, 2, 25, 7-11

Itt jó:

Zoltán utca | 4 | 1/A, 9, 1518

a numeric sortnak kellene tudnia a 5-6 ás 5/B típust is, mert most nem jó, string sort van a hiányzó hászámoknál ezekre.
úgy nézem csak interpolation: all-nál rossz

**Comment by vmiklos** [comment]
Széchenyi rakpartot látom most is.

**Comment by vmiklos** [comment]
> 3, 6, 12/B

Lett belőle, így már jobb lesz.

**Comment by vasony** [comment]
txt kimeneten is legy szives

**Comment by vmiklos** [comment]
Ja látom.

**Comment by vmiklos** [comment]
Ez is megvolna.
