### ISSUE TITLE
Rename `*.txt` to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [vmiklos/osm-gimmisn#2806]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*
Also, it is the most widely used extension on GitHub, see https://github.com/users/FloEdelmann/projects/2/views/2

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by vmiklos** [comment]
Doable, but a manual review is needed, not all .txt files in this repo are sent to overpass, see e.g. data/robots.txt.

**Comment by FloEdelmann** [comment]
Of course not all `*.txt` files should blindly be renamed, only those that contain Overpass QL syntax.

Sorry, I didn't notice I already created a similar issue before: #2628
Is [this comment](https://github.com/vmiklos/osm-gimmisn/issues/2628#issuecomment-1306219985) still valid?

**Comment by vasony** [comment]
> Of course not all `*.txt` files should blindly be renamed, only those that contain Overpass QL syntax.
> 
> Sorry, I didn't notice I already created a similar issue before: #2628 Is [this comment](https://github.com/vmiklos/osm-gimmisn/issues/2628#issuecomment-1306219985) still valid?

Yes is is, I've made the ln -s for these files locally, and works fine.
