### ISSUE TITLE
text kimenet formázása betűjelesnél

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#285]
Most ez van:
Fatörzs utca	[8/A, 8/B]

Ezt szeretném
Fatörzs utca	[8a, 8b]

mert akkor be tudom copyzni innen az invalid filterbe, csak aposztof kell, és nem fogom elfelejteni leszedni a perjelet.

**Comment by vmiklos** [comment]
Nem volna értelme akkor a 42a alakra normalizálni html esetén is? Konzisztencia miatt.

**Comment by vasony** [comment]
de volna, csak ez a forma olyan "tájidegen" Magyarországon, és nehezen veszi be az ember gyomra.

**Comment by vmiklos** [comment]
Ja értem, akkor legyen. Nekem nincs semmilyen GIS hátterem, szóval nem tűnik fel a tájidegenség. :-)

**Comment by vasony** [comment]
A szememnek tűnik fel, hogy a táblán 17/a van nem 17a :-)

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/madarhegy/view-result.txt

Ez most már jónak tűnik.
