### ISSUE TITLE
Királyleányka utca 10/B

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#286]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/madarhegy/view-result

Királyleányka utca	[10/A, 10/B]

10/B létezik és mégis kihozza. 10/A valóban nincs.

**Comment by vmiklos** [comment]
Igen, ez nekem is annak tűnik.

**Comment by vmiklos** [comment]
Fenti linken most már nincs 10/B; a '10 B' vs '10/B' párosítás nem ment.
