### ISSUE TITLE
Régi URL-ek kipucolása cronból

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#291]
https://vmiklos.pythonanywhere.com/osm/missing-streets/budapest_09/view-result

itt: ALBERT FLÓRIÁN út

filterekben mappelve van de nem veszi figyelembe

  \# 'OSM Name 1': 'Ref Name 1'
  'Albert Flórián út': 'ALBERT FLÓRIÁN út'

**Comment by vasony** [comment]
user error, átneveztem ez a régi URL...
itt már jó:
https://vmiklos.pythonanywhere.com/osm/missing-streets/ferencvaros/view-result

**Comment by vmiklos** [comment]
:-) A cron mondjuk kipucolhatná ezeket a régi URL-eket, hogy elavult adatot ne szolgáljunk ki.

**Comment by vasony** [comment]
Akkor legyen.

**Comment by vmiklos** [comment]
Az is gond volt, hogyha elírtad a nevet akkor meg egy nyers python traceback jelent meg, mindkettőt megoldja ha nem létező relációkat nem mutatunk.
