### ISSUE TITLE
Rétköz utca 9 A 1

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#296]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/gazdagret/view-result

Rétköz utca	[9 A 1]

ez itt valami nem várt mellékhatás.

Tegnap ez volt: Rétköz utca [9], kiszűrtem a 9-et, erre megjött a fenti, de csak ez az 1. Amit ki is kellett volna szűrni, mert nem egyszerű formátumú.

Ez van a refben:
Rétköz utca 9
**Rétköz utca 9 A**
Rétköz utca 9 A 1
Rétköz utca 9 A 2
Rétköz utca 9 A 3
Rétköz utca 9 B
**Rétköz utca 9/B**

**Comment by vmiklos** [comment]
Látom, megnézem ez mi.

**Comment by vmiklos** [comment]
Azért van ott a '9 A 1', mert range szinten stimmel a 9 miatt és az invalid az jelenleg csak a referenciát szűri, normalizálás előtt. Nem túl logikus, meg fogom cserélni, hogy az invalid is a normalizált adatot szűrje, így a "9" ki fogja szűrni a "9 A 1"-et, mert annyi marad belőle (mert nem "egyszerű").

**Comment by vasony** [comment]
Vagy a a"nem egyszerű" tételeket kidobjuk teljesen, nekem ez volt a fejemben, nem konvertálgatunk sehova.

**Comment by vasony** [comment]
De lehet az meg egy csomó hasznosat elveszt, akkor legyen a csere.

**Comment by vmiklos** [comment]
Jah, legyen csere, így a ranges és az invalid konzisztens, mind a kettő a normalizált adaton működik.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/gazdagret/view-result eltűnt innen a Rétköz utca, jók vagyunk azt hiszem.
