### ISSUE TITLE
Érvénytelen addr:city értékek lista bővítése timestamp és fixme mezőkke

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2985]
::timestamp, fixme mezők a végére

**Comment by vmiklos** [comment]
Az overpass egy stringet ad timestampnek, azt mutassam egy az egyben (egyszerűbb) vagy ertelmezzem és mutassam helyi idozonaban (bonyolultabb)?

A fooldal figyelembe veszi a helyi idozonat.

**Comment by vasony** [comment]
Elég a string, nem kell értelmezni, csak a sortolás miatt kell

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/invalid-addr-cities lehet tesztelni.

**Comment by vasony** [comment]
fixme magyarítása kicsit fura. de jó lesz

**Comment by vmiklos** [comment]
Ha van jobb javaslat, át lehet írni, ezt most az iDből vettem :)
