### ISSUE TITLE
Érvénytelen addr:city értékek lista számosságának statisztikázása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2986]
Jó lenne egy T-14 vagy T-30 napos (esetleg heti, havi ahogy céleszerű) grafikon, ami az addr:city értékeinek számosságát ábrázolja az idő függvényében

**Comment by vmiklos** [comment]
OK, lehet róla szó. Kell neki egy sql tábla, azt naponta töltögetni cronból, aztán ha már van elég gyűjtött adat, kaphat egy webes felületet. Első körben a T-14 nekem tetszik, a "New house numbers" diagram is ennyi ideig "néz vissza".

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/#_stats-invalid-addr-cities de várjunk vele még 3 napot, hogy látszódjon, hogy tényleg az utolsó 14 napot mutatja.

**Comment by vmiklos** [comment]
Jónak tűnik. Vélemény?

**Comment by vasony** [comment]
Igen, már néztem.
Most látom hogy pont 14 egység van, még várhatunk holnapig, hogy marad-e.
Tegnap nem jegyeztem meg mi volt az első, most 2023-06-14 35 db

**Comment by vasony** [comment]
A 14 nap is rendben.
