### ISSUE TITLE
Érvénytelen* ellenőrző eszközök kiszervezése új menübe

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2987]
Az alábbiak kikerülhetnének egy új menübe, mert már nem statisztikák
[Érvénytelen területi beállítások](https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/invalid-relations)
[Érvénytelen addr:city értékek](https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/invalid-addr-cities)

vagy ha úgy kényelmesebb, még várhatunk hozzá egy harmadikat

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/ lehet tesztelni.

**Comment by vasony** [comment]
:)
