### ISSUE TITLE
Érvénytelen területi beállítások figyelembe vétele napi frissítésnél

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2988]
Az alap szitu:
1) https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/invalid-relations
2) Kijavítom
3) Nálad még ott van hónap végéig.

Javaslat:
1) cron futtassa ezt meg, és generálja le a területek listáját egy temp objektumba
2) vegye be a lista eredményét a napi frissítésbe akkor is ha inactive: true

**Comment by vmiklos** [comment]
Úgy is meg lehet közelíteni, hogy mikor leszűkítem a relációk listáját az aktív relációkra, akkor ezek a területek is maradjanak benn a listában.

Tudsz mondani commitot ami ilyesmit javított, hogy helyben reverteljem? Remélik, hogy volt 2 ilyen terület, de aztán most a július 1-i frissítés persze "megoldotta" a dolgot.

**Comment by vasony** [comment]
solymar most rossz, ráfrissítettem így már nálad is

**Comment by vmiklos** [comment]
OK. És erre hol lesz a javítás, data/, referencia vagy OSM? Ha jól értem akkor a data/ most is instant és a javítás az lesz, hogy a referencia vagy OSM esetén se kelljen a hónap végéig várni.

**Comment by vasony** [comment]
data vagy osm általában. konkrét esetben osm-en már javult

**Comment by vmiklos** [comment]
Igen, látom, szuper, most tudom reprodukálni a dolgot.

**Comment by vmiklos** [comment]
Most épp balatonfokajar és solymar látszik invalidnak, mindkettő a referenciában lett javítva. Helyben nálam egy:

```
cargo run -- cron --mode relations --no-overpass --refcounty 19 --refsettlement 025
cargo run -- cron --mode relations --no-overpass --refcounty 14 --refsettlement 121
```

után már jó. Lehet tesztelni, hogy holnap a https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-relations megjavul-e.

**Comment by vasony** [comment]
megjavult
