### ISSUE TITLE
betűjeles üzletek: formázás és figyelembe vétel

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#299]
#285 

A csillagosok nem lettek átformázva a text kimeneten (mivel eddig nem is voltak)

https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/kelenfold/view-result.txt

Ez van
Bártfai utca	[9, 35b, 49b, 59b], [2a, 8, 12, 22, 26b, 38b, **52/B***]

Ez kellene
Bártfai utca	[9, 35b, 49b, 59b], [2a, 8, 12, 22, 26b, 38b, **52b***]

**Comment by vasony** [comment]
https://www.openstreetmap.org/node/3136661536

És igazából a helyes az lenne ha meg se jelenne, mert létezik.

**Comment by vmiklos** [comment]
Igen, látom.

**Comment by vmiklos** [comment]
A két problémának u.az volt a gyökere.

**Comment by vasony** [comment]
Most már csak egy gond van, hogy leszedi a csillagot a betűjeleseknél

https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/kelenfold/view-query
Sopron út 21/A*

https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/kelenfold/view-result.txt
Sopron út	[21a]

nem csak a text kimeneten

**Comment by vmiklos** [comment]
Igen, erre a viselkedésre még tesztet is írtam tegnap:

https://github.com/vmiklos/osm-gimmisn/blob/b9659ed56b033939e9d32e54885ddff4f21022a3/tests/test_util.py#L282

Ettől függetlenül jogos, '42a*' miért lenne'42/A' és nem '42/A*'. Valamiért ez logikusnak tűnt akkor.

**Comment by vmiklos** [comment]
Próbáljunk ki egy új worflow-t, rakok rá needs-verified címkét és ha jűnak tűnik, akkor vedd le a címkét és zárd le az issue-t. Hátha ez jobb, mint a close + reopen, aminek kicsit edit war szaga van. :-)

**Comment by vasony** [comment]
Nekem mindegy a workflow, ha téged zavar a reopen, akkor legyen így :) de nem garantálom, hogy elsőre észreveszem és nem nyitom újra :-))
Egyébként ez új bug, csak nem volt kedvem ezért új issue-t nyitni.
