### ISSUE TITLE
Ref hibás mapping nem mindig jelenik meg az érvénytelen területi beállításokban

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#2994]
https://github.com/vmiklos/osm-gimmisn/commit/69cce0eb0040c1358262b1b7c20b901a56c35f2a

refstreets:
  'Báthory utca': 'Báthori utca'

osm: Báthory utca
ref: Báthory utca

https://github.com/vmiklos/osm-gimmisn/commit/78298b3d68021a2e961474dca8a15c2e50c4c91d
refstreets:
  'Díszfű utca': 'Diszfű utca'  # Budaliget (Pesthidegkút)

osm: Díszfű utca
ref: Díszfű utca

**Comment by vmiklos** [comment]
Ah, itt azt kéne észrevenni, hogy a ref név az nincs benne a referenciában. De jelenleg csak ezeket az eseteket vesszük észre:

- osm név nincs osm listában
- ref név van osm listában

Ezt írja is a doksi közvetlenül a lista alatt:

> Note: an OSM name is invalid if it's not in the OSM database.A reference name is invalid if it's in the OSM database.

Szóval az a teendő, hogy a "ref listában nincs ref név" hibákat is gyűjtsük, ez megoldható.

**Comment by vmiklos** [comment]
Lehet tesztelni :)

**Comment by vasony** [comment]
jobb lenne, ha külön kategória lenne neki.
Most Alsóörs, Köcsi tó utcát hibásnak jelzi, ami nem tudom, hogy miért van. Nem találok hibát. 
A refben `Köcsi tó `utca osmben `Köcsitó utca .
Mapping:   'Köcsitó utca': 'Köcsi tó utca'

**Comment by vasony** [comment]
valószínű ez a bug lezárható, ha nem vesszük külön, de előbb ezt kell tisztázni, addig nem lehet tisztázni:
https://github.com/vmiklos/osm-gimmisn/issues/3028

**Comment by vasony** [comment]
csak Érd maradt, ez jónak tűnik
