### ISSUE TITLE
Utcatöblet letöltése gpx-ben

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3018]
Szükség lenne az overpass funkciók eredményének exportálására, hogy mobilról is terepen lehessen kezelni a dolgokat.
Most mobilról nehézkes kimásolni a query-t és kiexportálni kattintgatással, csak asztali géppel kezelhető.

Az alap ötlet A) opció
1) Van a https://osm.vasony.hu/additional-streets/balatonakarattya/view-turbo oldal, ez visszaadja a query-t

2)  Kéne egy link az alájra, és a meg kellene futtatni a háttérben overpass-szal és generálni belőle egy letölhető gpx-et 

B) opció
Erőforrás igényesebb, hogy cron frissítésnél alapesetben állítsa elő a gpx-et minden frissítendő területre, ahol az utcatöblet > 0

**Comment by vasony** [comment]
valami ilyesmi kéne
```
<?xml version='1.0' encoding='UTF-8'?>
<gpx version="1.1" creator="osm gimmisn xmlns="http://www.topografix.com/GPX/1/1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <desc>Budapest 01</desc>
    <time>2023-05-24T19:09:03.202511200Z</time>
  </metadata>
  <wpt lat="47.488240949989844" lon="19.041867398688243">
    <name>Antal lépcső</name>
  </wpt>
  <wpt lat="47.49026797096594" lon="19.03883181217385">
    <name>Nelson Mandela park</name>
  </wpt>
</gpx>
```

**Comment by urbalazs** [comment]
Mivel ez településeként jó esetben csak néhány pontot eredményezne, én azt javaslom, hogy készüljön egyetlen GPX-fájl, amely tartalmazza a gimmisn **összes** utcatöbbletét, de településenként külön GPX-fájl legyen. Ez jelenleg 200 pontot jelentene, egyáltalán nem tűnik kezelhetetlen mennyiségnek, ha egy fájlon belül vannak.

Ha elkészül a https://github.com/vmiklos/osm-gimmisn/issues/2987 megvalósítása, akár mehet oda is a letöltési link.

**Comment by vmiklos** [comment]
Első körben annak kéne utánajárni, hogy az overpass-turbo hogy csinálja ezt. Tudjuk, hogy az overpassql bemenetet bemásolva és tőle gpx kimenetet kérve megkapjuk amit szeretnénk. Ki kéne deríteni, hogy ezt hogy csinálja. Remélhetőleg valamilyen JS libet használ erre, és akkor a mi webes felületünk is tudná u.ezt csinálni. Ha egy mód van rá, jó lenne nem kézzel generálni a gpxet. Persze ha az derül ki, hogy ez az overpass-turbó része (nem külső js lib), az érv lehet amellett, hogy mi is saját kódból csináljuk u.ezt.

Haladjunk lépésenként, egyelőre legyen az a cél, hogy ez megy egy relációra.

**Comment by vasony** [comment]
Az overpass gpx generáló nem túl hasznos mobilon, ezért a waypointos kézi megoldás célravezetőbb, nem annyira bonyolult összerakni ezt a gpx-et.
Fix fejléc (max a dátumot be lehet tenni de anélkül is megy)  a többi meg már csak gyakorlatilag az utca 1 koordinátája.

**Comment by vmiklos** [comment]
> Az overpass gpx generáló nem túl hasznos mobilon

A kimenettel is van baj, vagy csak az overpass-turbo felülete béna mobilon? Magát a kimenetet szeretném újrahasznosítani, ha egy mód van rá.

**Comment by vasony** [comment]
A kimenettel is baj van. Illetve a kimenet nem hibás, csak a feladatra nem használható, mondhatnám, hogy más fajta kimenet kell ezért nem tudod újrahasznosítani.

Az overpass kimenet vonalakat tartalmaz, ami az osmandban nem annyira jól kezelhető, ha waypointként generáljuk le, akkor rendesen látszik, mert markert lehet belőle csinálni, amihez aztán lehet navigálni illetve megjelölni ha már útba ejtetted.

**Comment by vmiklos** [comment]
Ja értem. Azt hittem az overpass-turbó amit ad az csak a felülete miatt nem jó mobilon. Akkor tényleg jobb nekünk generálni.

**Comment by vmiklos** [comment]
Oké, az overpass JSON válaszában ott vannak a way összes node-ja, koordinátával. Ebből kéne egyetlen koordináta.

@vasony erre van preferenciád, hogy hogyan számítsuk? Sima átlagolás megfelel? Vagy bounding box közepe?

**Comment by vasony** [comment]
> De talán ami még egyszerűbb: a node lista középső eleme szerintem elég jó közelítés.

ez. 
az átlag nem jó, mert ha L vagy kanyarodik akkor nem lesz az úton a pont

**Comment by vasony** [comment]
de lehet első vagy utolsó pont is, mert az utcatáblákat az utca végére teszik

**Comment by vmiklos** [comment]
A KRESZ táblát viszont elképzelhető, hogy csak az elejére, akkor az első node lesz a nyerő.

**Comment by vasony** [comment]
előfordulhat, hogy 2 utcának közös az első pontja ekkor torlódás lesz a GPX-ben és nem kezeljető, az javaslom toljuk el a pontot 10%-kal a 2. pont irányába, írhatnék súlyozott átlagot is:

PONT.X=(PONT1.X*9+PONT2.X)/10
PONT.Y=(PONT1.Y*9+PONT2.Y)/10

**Comment by vmiklos** [comment]
> előfordulhat, hogy 2 utcának közös az első pontja ekkor torlódás lesz

Ez egyelőre kimaradt, de ha előjön a gyakorlatban akkor jelezd és megoldható.

> Még 1 szívás van, hogy egy utca több szakaszból is állhat

Ezzel nem tudom pontosan most mi van, szerintem a /additional-streets/balatonakarattya/view-result se tartalmaz erre az esetre explicit kódot, talán minden szakaszra külön sort kapsz. Minden esetre a GPX is u.ezekkel az építőkockákkal dolgozik, tehát ami eddig a HTML oldalon volt 1 sor, az lesz most a GPXben 1 WPT.

**Comment by vasony** [comment]
Overpass kell, az asztali gépen úgy jobb, illetve hosszú távon a gpx-be kell majd duplikátum szűrés, az overpassba meg nem

Az előbb még ment, most ezt dobja:
```
Belső hiba a /osm/additional-streets/balatonakarattya/view-result.gpx kiszolgálása során
our_application() failed

Caused by:
    0: failed to parse overpass result as json
    1: expected value at line 1 column 1
```

**Comment by vasony** [comment]
úgy néz ki nem determinisztikus, van valahol timestamp kezelés benne, mert hol error-t dob, hol működik

**Comment by vmiklos** [comment]
Ebbe a nem-determinisztikus hibába én is belefutottam. Ha maga az overpass elhasal, html hibát ad, mikor jsont várunk. Ha z.overpass-api.dere váltok helyben, akkor nem csinálja ezt. Váltsak arra defaultból?

**Comment by vasony** [comment]
Nem kell, csak kezeld le az exception, hogy legyen vmi értelmes üzenet. Egyénként jónak tűnik, zárható.
Ahogy vártam az utcák egy részénél a "rossz" végén van a jegyzet, de az az osm-ben az utca irányváltásával megoldható. Így jó, mert egyirányúnál a kezdeténél van.

**Comment by vasony** [comment]
Akkor ahogy írtad, még nézzük meg másik mime-type-pal, hogy androidon is ne átnevezős legyen.
