### ISSUE TITLE
Utcalista nem frissül a frissítés referenciából gombra

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3028]
utcalista nem frissül a frissítés referenciából gombra, csak a cronból, ezért az inactive:true területek hibásak 

https://osm-gimmisn.vmiklos.hu/osm/missing-streets/budapest_19/view-query#
vs.
https://osm.vasony.hu/missing-streets/budapest_19/view-query#

```
< Ferihegyi repülőtérre vezető út
> Ferihegyi reptérre vezető út

```

**Comment by vmiklos** [comment]
Az sqlben indexelt teljes utca-referenciában is repülőtér van:

```
$ sqlite3 workdir/state.db 
sqlite> select * from ref_streets where county_code = "01" and settlement_code = "019" and street like 'Feri%';
01|019|Ferihegyi repülőtérre vezető út
```

Ezzel lesz a gond, utána a gomb (ami az sqles nagy táblából gyártja a reláció .lst file-ját) már valószínűleg jó lesz.

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
A frissítés jó, még a ref-et frissítsd meg és ha Érd eltűnik, akkor zárható.

**Comment by vmiklos** [comment]
Eltűnt, úgy látszik

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/whole-country/invalid-relations üres.
