### ISSUE TITLE
Pontosvesszős betűjelek parszolása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#303]
Ezt is ki kellene tudni parszolni:
https://www.openstreetmap.org/node/6852648009

Albert utca 43/B;43/C

Kijön hiányban:
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/kelenfold/view-result.txt
Albert utca	[43a, 43b, 43c, 43d, 43e, 43f, 43g]

hasonló volt:
#112

**Comment by vmiklos** [comment]
Na megnéztem, és közben rájöttem, hogy ez így rendben van. Itt volt erről szó:

https://github.com/vmiklos/osm-gimmisn/issues/267#issuecomment-553385335

És ott arra jutottunk, hogy tarományoknál mindenképp eldobunk mindent a szám után, különben nem lehet megállapítani, hogy a "169-179 B" esetén a B az mindkettő, vagy csak a második elemhez tartozik. Szóval nem nagyon van itt mit javítani, ezt kézzel ki kell szűrjed, vagy kivenni a `housenumber-letters: true`-t. Ez így érthető?

**Comment by vasony** [comment]
Ez nem ugyanaz az eset. Itt nem 1 házszám van több részből, hanem 2 házszám van pontosvesszővel elválasztva. Ez valid is formailag, egy háznak lehet több házszáma.

Tudom, hogy ugyanaz fut a ref-en meg az osm oldalon is, de ez itt nem jogos, osm oldalon lehetnek pontosvesszővel elválasztott értékek, amiket teljesen külön kell kezelni, a nem egyszerű házszámoktól.

Az osm beolvasáskor kellene főlé tenni valamit, ha van benne pontosvessző, akkor kiszedi egy tömbbe, és utána már mehet a mostani logika a tömb elemekre.

Most azt hiszem egybemostuk a 169-179 és 169;179-et, pedig nem ugyanaz.

**Comment by vmiklos** [comment]
Igen a - meg ; ugyanúgy volt eddig kezelve, mert nem fogtam fel, hogy a ; OSM jelölés :-) Köszi, így már értem.

**Comment by vmiklos** [comment]
Elvileg javítva.

**Comment by vasony** [comment]
Nem tudom van-e összefüggés a mai javítással, de nem tudom elnyomni a Tétényi út 98-102-t.
Most ez van filterben:

Tétényi út:
    invalid: ['3', '21', 71b, '98', '101', '102', '111a', '115', '117', '126b']

**Comment by vmiklos** [comment]
A 98-102-t kifejtjük 98, 100, 102-re; OSM-ben csak 100a, 100b van, és a relációra be van kapcsolva a `housenumber-letters: true`, tehát a 100a nem egyenlő 100-zal. Szerintem ezért szól, nekem úgy tűnik, jogosan. Ha a 100-at is felveszed invalidba akkor nekem helyben már nem szól érte.

**Comment by vasony** [comment]
Ja tényleg a 100. Lassan már nem látom a fától az erdőt :-)
