### ISSUE TITLE
Csorbai utca 5/E 1

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#305]
Ezt hogy kellene kiszűrni?

Csorbai utca	[5/E 1]

Most így van
  Csorbai utca:
    invalid: ['2', '2a', '3', '5/E 1', '13a', '16c', '18', '22', '28a']

**Comment by vmiklos** [comment]
Simán '5', #296 óta először lefut a normalizálás ('5/E 1' -> '5', mivel ez nem egyszerű házszám), és csak utána szűr az invalid.

**Comment by vasony** [comment]
Akkor gondolom a 18-22 is 18 és 22 külön

**Comment by vmiklos** [comment]
Igen, ez a szándék.

**Comment by vasony** [comment]
így jó
