### ISSUE TITLE
UX kiegészítés a hiányzó házszámok oldalon

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#31]
#24 kiegészítés

- a frissítés dátumát csempésszétek vissza az oldalra, alulra.
- az oldalon magán is kellene 'terület határa' link

**Comment by vmiklos** [comment]
Ennél bonyolultabb kérés sose legyen. :-)

**Comment by vasony** [comment]
Nem úszod meg ennyivel :)
Kérhetem a frissítési dátumot inkább az oldal aljára, mert így meg
összeizéli a menüt...
A <hr/> fölé

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/0ff1d83586456a26ba8bf1061ffe6bb70cd13a11

**Comment by vasony** [comment]
köszi, jó lett. látom általánosan minden oldal aljára bemegy.
a suspicious/view-query-ben viszont akkor most dupla onnan már ki lehet szedni

updated on 2019-05-12T19:56:24.219558

Frissítve 2019-05-12T19:56:24.219558

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/9a4f017296cd5ecf6ce0f95c2c05a210c1236584
