### ISSUE TITLE
Kettőzött bejegyzés a /streets/TELEPÜLÉS/view-result listában

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#3106]
Lásd: https://osm-gimmisn.vmiklos.hu/osm/streets/martonvasar/view-result

Az [Emlékezés tere](https://www.openstreetmap.org/way/314747012) egyszerre park és tér is. Talán ez okozhatja a kettőzött bejegyzést?

```
leisure=park
name=Emlékezés tere
place=square
```

Csak egyszer kellene szerepelnie a listában.

**Comment by vasony** [comment]
Az overpass queryn kell javítani, az duplázza

**Comment by vasony** [comment]
szerintem már jó, nézd meg azt zárd le ha szerinted is

**Comment by urbalazs** [comment]
Szerintem is jó. Köszi a javítást!
