### ISSUE TITLE
Szemere [utca 16]

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#312]
https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/lipotvaros/view-result.txt

Ha el van írva az utcanév, akkor ez jön:

Szemere	[**utca 16-18, utca 3-5**]
Szemere utca	[9, 17, 19, 21, 23], [8, 10, 16-18]

Ez a rossz:
https://www.openstreetmap.org/way/753691090

Mielőtt az OSM-ben javítom, lehet meg kellene nézni.

**Comment by vmiklos** [comment]
Szabad feltételezni, hogy a házszám 0-9cel kezdődik?

**Comment by vasony** [comment]
Szabad, sőt 1-9-cel. Egyet nem értek, honnan szedte össze az utcát? A kötőjeles felbontó a hibás?

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/blob/1a17b12a0d6262456f9b669d3919194bea4e098d/util.py#L638 a szám utáni szemetet dobom csak el, előtte eddig nem merült fel, hogy lehet szemét. De akkor majd javítom.

**Comment by vasony** [comment]
ez nem szemét szerintem, csak más az utcanév.
Ki se kellene jönnie, mert "Szemere" típusú utca nincs a ref-ben csak "Szemere utca" típusú. Ez itt nyilván osm hiba, de van vidéken olyan nagyritkán, hogy
Hosszúrét 42, meg Hosszúrét utca 42 és a kettőt nem kellene kevernie.

Valószínű a koncepciót nem értem, és előbb fut a tördelő függetlenül az utcanévtől?

**Comment by vmiklos** [comment]
Az országos .tsv esetén az utcanév meg a szam tabbal van szeparalva, a relacio referenciája a .lstnel viszont információt veszít, ott már space a szeparator. Ez eddig nem volt gond, de most kibukott. Valszeg az a jobb ha ezt megoldom, nem ha csak eldobom ezt az utca "prefixet". :)

**Comment by vmiklos** [comment]
Kész: a relációra generált ref házszám lista formátuma változott, szóval csak holnapra (illetve jan1-re) lett volna jó automatikusan a fenti URL kimenete, de azt most elvileg kézzel újrageneráltam.

**Comment by vasony** [comment]
ok
