### ISSUE TITLE
data: ha a filter részben az utca alatt nincs semmi csak comment, akkor elhasal

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3174]
Tesztet kell bővíteni, hogy fogja meg:

Balatonszemes, Szabadság utca a hibás
```
  Szabadság utca:
    # 32/1: nincs ilyen, csak 32 és 32/b van.
    # 32/a: nincs ilyen, csak 32 és 32/b van.
  Széchenyi utca:
    # 2/1: nincs ilyen, csak 2 és 2/a van.
    # 6/a: nincs ilyen, csak sima 6 van. A 10-es házon van festékkel 6/a, de az nem illik a sorba.
    # 52/b: nincs ilyen, csak sima 52 van.
    # 56: nincs ilyen, az 54 után az 58 következik.
    invalid: ['2/1', '6a', '52b', '56']
```

**Comment by vmiklos** [comment]
lehet tesztelni

**Comment by vasony** [comment]
> expected at least one sub-key for 'filters.devnull utca'

ez így jó.
viszont ha csak filters: van bármi érték nélkül, akkor átmegy

**Comment by vmiklos** [comment]
Megnéztem, hogy mit tehetek, de egyrészt az üres tartalom a `filters:` alatt nem okoz olyan hibát mint az eredeti probléma (főoldal be se jön), másrészt amit kapok a YAML parsertől ott nincs is különbség aközött, hogy a `filters:` meg van adva, csak üres vagy meg sincs adva (mindkettőt úgy kapom mintha meg se lenne adva).

Így azt javaslom, hogy ezt zárjuk: az eredeti probléma megoldva, és az extra ötlet jól hangzik, de nem lenne könnyű megvalósítani. Az a felesleges `filters:` annyira nem fáj, gondot meg nem okoz.

**Comment by vasony** [comment]
ok
