### ISSUE TITLE
Aliasok kezelése kompatibilitási okokból

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#322]
ha átnevezzük a relationt, a wiki-ben és könyvjelzőkben maradhatnak régi hivatkozások, ezt tudnánk egyszerűen kezelni

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/budapest_06/*
redirect, vagy url rewrite
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/terezvaros/*-ra

(átnevezés után pedig majd fordítva)

kezelése relations-ben, 

terezvaros:
    osmrelation: 3229919
    refmegye: "01"
    reftelepules: "006"
    **alias: ['budapest_06', 'budapest06']**

csak a minta kedvéért tettem bele két félét

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/blob/5bd3b4c7de29c0d90aa15e6561653e5cc952e505/wsgi.py#L673-L677

Már most is van ilyen, mikor megelégeltem, hogy képtelen vagyok typok nélkül leírni, hogy suspicious. :-) Jogos, hogy legyen hasonló relációkra is. Ez azt csinálja, hogy redirect nélkül elfogadja a régi módot; ha linkeken kattingatsz akkor amúgy is csak az újat kapod.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/missing-streets/ujbuda/view-result

Ilyen lett, ez most egy alias, a főoldal nem linkel rá.

**Comment by vasony** [comment]
Jó ez.
A pucolós viszont nem tökéletes, mert átnevezés után a budapest_08 és 09-nek megvoltak a százalékai és az utcanevei még régről.

**Comment by vmiklos** [comment]
Nincs pucolás :-) Csak annyi van, hogy kapsz hibaüzenetet ha nem beregisztralt relacio nevét adod meg. Ha egyszer majd probléma lesz a foglalt hely, csinálok pucolast a cronba. Most 200mb körül járunk, elfér.

**Comment by vasony** [comment]
Ja, jó, akkor zárom a másikat, azt hittem ez már meg lett csinálva.

**Comment by vmiklos** [comment]
Ja most látom, hogy lett rá külön issue. Ok, majd megnézem :-)

**Comment by vmiklos** [comment]
Jól elchatelünk itt. :-) Még jobb, akkor egyelőre nem csinálok semmit. Szerintem nem túl fontos téma
