### ISSUE TITLE
Üres meglévő házszám- és utcalista, ha nincs hiányzó házszám

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#3244]
Azoknál a területeknél, ahol 100% a házszámlefedettség, az alábbi két fájl is üres:

- /street-housenumbers/TELEPÜLÉS/view-result.txt
- /streets/TELEPÜLÉS/view-result.txt

A weben megjelenik a táblázat, csak az egyszerű szöveges változat marad üres. Az egyszerű szöveges változatnak tartalmaznia kellene a meglévő házszámokat és utcákat.

Példa, Uny, itt üres fájlok jönnek:

- Uny (**100%**): https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/uny/view-result
- Üres fájl (ez jó): https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/uny/view-result.txt
- Meglévő házszámok: https://osm-gimmisn.vmiklos.hu/osm/street-housenumbers/uny/view-result
- **Üres fájl:** https://osm-gimmisn.vmiklos.hu/osm/street-housenumbers/uny/view-result.txt
- Meglévő utcák: https://osm-gimmisn.vmiklos.hu/osm/streets/uny/view-result
- **Üres fájl:** https://osm-gimmisn.vmiklos.hu/osm/streets/uny/view-result.txt

Példa, Újszilvás, itt jó fájlok jönnek:

- Újszilvás (**85,23%**): https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/ujszilvas/view-result
- Nem üres fájl (ez jó): https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/ujszilvas/view-result.txt
- Meglévő házszámok: https://osm-gimmisn.vmiklos.hu/osm/street-housenumbers/ujszilvas/view-result
- **Nem üres fájl:** https://osm-gimmisn.vmiklos.hu/osm/street-housenumbers/ujszilvas/view-result.txt
- Meglévő utcák: https://osm-gimmisn.vmiklos.hu/osm/streets/ujszilvas/view-result
- **Nem üres fájl:** https://osm-gimmisn.vmiklos.hu/osm/streets/ujszilvas/view-result.txt

**Comment by vasony** [comment]
a view-result.txt nem az aminek látszik, ez egy nem implementált feature a meglévő utcák/házszámokra

**Comment by urbalazs** [comment]
Ezt a funkciókérést azért nyitottam, hogy egyszerűen össze lehessen hasonlítani naponta a változásokat. Időközben vasony megoldotta az összehasonlítást, így számomra ennek a funkciónak már nincs értéke.

Ha nem bonyolult megvalósítani az egyszerű szöveges kimenetet a meglévő utcákra és a meglévő házszámokra, akkor maradjon ez a funkciókérés nyitva. Ha bonyolult vagy sok munkát igényelne, akkor lezárható.

**Comment by vasony** [comment]
A workdirből kéne kiajánlani a streets-relation.txt és street-housenumbers-relation.txt fileokat  szerintem és kész is vagyunk.

**Comment by vmiklos** [comment]
A létező utcákat és házszámokat most .csv formátumban kérem le az overpasstól, bár ez a jövőben változhat, ld #3105.

De ha annyi egyelőre a elég, hogy a .csv jelenjen meg weben 1:1ben, az tényleg megoldató.

**Comment by vasony** [comment]
szerintem a diffel ez az issue már okafogyott.
