### ISSUE TITLE
további utcák gpx hibára fut ha node is van a listában

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3288]
Belső hiba a /osm/additional-streets/balatonfuzfo/view-result.gpx kiszolgálása során
our_application() failed

Caused by:
    street 6697355203 has no nodes

**Comment by vmiklos** [comment]
Ki gondolta volna hogy egy pont is lehet utca. :-) Jogos.

**Comment by vasony** [comment]
relation is lehet (multipolygon), akkor azon se szálljon el

**Comment by vmiklos** [comment]
Tudsz erre példát? Utána kéne járni, hogy a relációra az overpass milyen jsont ad vissza. Elvileg nem túl bonyolult, vannak benne valahogy dolgok (node, way, stb) és abból az első érdekel minket.

**Comment by vmiklos** [comment]
Lehet tesztelni, node és way van kezelve, a relációra kéne példa, hogy lássuk hogy néz ki.

**Comment by vasony** [comment]
> relation
https://osm-gimmisn.vmiklos.hu/osm/additional-streets/balatonalmadi/view-result.gpx

internal server error

**Comment by vmiklos** [comment]
A reláció kezelés hiányzott, most már azt is lekezelem azzal, hogy az első taggal dolgozok. Lehet újra tesztelni. :)

**Comment by vasony** [comment]
Teszteltem, jónak tűnik
