### ISSUE TITLE
Vadlidátor hiba, dupla filternél nem jelez

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3290]
Duplán volt a Vöröskúti határút filter, a validátor nem szólt érte

Ebben még rossz
```
  Vöröskúti határsor:
    # XI. kerületi oldalon hrsz.
    invalid: ['152/7']

...

  Vöröskúti határsor:
    # 15x/y helyrajzi számok, sima nincs
    invalid: ['151', '152/7']
```

**Comment by vmiklos** [comment]
Úgy tűnik a yaml spec nem tiltja a duplikált kulcsokat, mi meg a default viselkedést kapjuk, ami szerint az utolsó kulcs nyer.

https://docs.rs/serde_with/latest/serde_with/rust/maps_duplicate_key_is_error/index.html

De ha jól értem lehet kérni, hogy hiba legyen helyette, és egyetértek, hogy ilyen duplikált kulcsot szándékosan sose akartunk.

**Comment by vmiklos** [comment]
Most látom, hogy ezt triviálisan lehet bővíteni, és akkor más kulcs-duplikációt is megtalálok. A refstreets alatt is volt duplikáció. A #3321 javítja ezeket (adat, nem kód). Szerintem mindkét eset egyértelmű, de azért nem árt ha ránézel.

Maga a javítás is jön majd, de az még félkész.

**Comment by vmiklos** [comment]
#3323 után már szól a duplikált kulcsokért a validátor. Lehet tesztelni.

**Comment by vasony** [comment]
Igen, kérek

**Comment by vasony** [comment]
szerintem jó lesz, majd ha megvan az exe, akkor zárd le

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/releases/tag/v24.2-rc1 ide feltöltöttem.
