### ISSUE TITLE
Pösingermajor ref hiba

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#33]
Felveszem inkább újnak, nem tudom mi okozza a problémát

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/posingermajor/view-query

csak 3 határoló utca van benne

itt meg nem 3

https://vmiklos.pythonanywhere.com/osm/streets/posingermajor/view-result

**Comment by vmiklos** [comment]
Ez nem amiatt lesz, hogy a data/relations.yaml szerint a posingermajor reftelepulese 012, míg 011 kéne legyen?

**Comment by vasony** [comment]
de. akkor en rontottam el.
