### ISSUE TITLE
Új terület: meglévő házszám linkre error-t dob

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#336]
Ha még nincs legenerálva a meglévő házszám, error jön.  Ide is be kellene tenni a feliratot, hogy nincsenek meglévő házszámok, mint a hiányzó hászámok oldalon.

Reprodukció
1) Új terület hozzáadása, relations-ben
2) Meglévő házszámok-ra kattintás

Ez jön:
Belső hiba a /osm/street-housenumbers/budaors-kamaraerdo/view-result kiszolgálása során
Traceback (most recent call last):
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 774, in application
    return our_application(environ, start_response)
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 759, in our_application
    doc.asis(handler(relations, request_uri).getvalue())
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 105, in handle_street_housenumbers
    with relation.get_files().get_osm_housenumbers_stream(mode="r") as sock:
  File "/home/vmiklos/git/osm-gimmisn/areas.py", line 62, in get_osm_housenumbers_stream
    return cast(TextIO, open(path, mode=mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/vmiklos/git/osm-gimmisn/workdir/street-

**Comment by vmiklos** [comment]
Ha a workdir/street-housenumbers-budaors-kamaraerdo.csv hiányzik, akkor tényleg ezt adja.

**Comment by vmiklos** [comment]
Most kiírja, hogy "No existing house numbers", és a menüben kérheted, hogy induljon az overpass, gondolom ez így elég.

**Comment by vasony** [comment]
igen, pont erre gondoltam.
