### ISSUE TITLE
checklist txt output

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#344]
Már régebben említettem, valami ilyesmire lenne szükségem

https://vmiklos.pythonanywhere.com/osm/missing-housenumbers/budaors/view-result.chkl
mime type mint a .txt

[ ] Beregszászi utca	[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 49, 51, 53, 57, 59, 61, 63, 71, 73, 75, 77, 79, 81, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 109, 129]
[ ] Beregszászi utca	[4, 6, 8, 10, 12, 16, 18, 20, 24, 28, 30, 32, 34, 38, 40, 42/A, 46, 48, 50, 54, 58]
[ ] Besztercei utca	[1, 7, 9], [4, 12]
[ ] Búzavirág utca	[1, 3, 5, 7, 9, 11, 13], [2, 4, 6, 8]
...

- a kapcsos zárójelek között 1 space és utána is egy space
- ha az elemek száma több mint 20 akkor 2 sorba lenne jó a páros páratlan (nem baj ha configban van ez a limit)

**Comment by vmiklos** [comment]
OK, ez nem túl bonyolultan megoldható. A fenti "eszköztár" linkeljen erre?

**Comment by vasony** [comment]
Igen, ha befér oda még 4 karakter a txt mellé

**Comment by vmiklos** [comment]
Nézd meg, hogy ilyesmire gondoltál-e.

**Comment by vasony** [comment]
A formátum tökéletes, már csak keresem a megoldást, hogy lehetne minél kevesebb iterakcióval megnyitni telefonon

teszünk egy próbát azzal, hogy egyből letöltené? most a .chkl-t nem ismeri fel a telefon, de megosztással megy.

vmi ilyesmi:
Content-Type: application/octet-stream
Content-Disposition: attachment;filename=\"budaors.txt\"

**Comment by vmiklos** [comment]
Megnézem, megoldhatónak tűnik.

**Comment by vmiklos** [comment]
Elvileg kész, kérlek teszteld.

**Comment by vasony** [comment]
Kösz, jó lesz. Samsung browserben szuperül megy. Chromeban még vmit állítani kell, még nem jöttem rá mit, de már így is jobb mint volt.
