### ISSUE TITLE
Város ellenőrzésnél legyen case sensitive

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3456]
KÜbekháza

https://www.openstreetmap.org/way/1221822582

Nem szerepel a hibás településeknél

**Comment by vmiklos** [comment]
Ez a https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-addr-cities oldal, ugye?

**Comment by vasony** [comment]
> Ez a https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-addr-cities oldal, ugye?

igen az, most direkt nem javítottam ki.

**Comment by vmiklos** [comment]
Az érvényes városneveket a tőled jövő `varosok_count_<dátum>.tsv` adja, már abban is kisbetűsek a nevek. Ott meg tudod oldani, hogy megmaradjanak a nagybetűk? Ha igen, akkor amint átvettem, én is el tudom dobni a kisbetűsítést az osm oldalon és akkor ez megoldható.

**Comment by vasony** [comment]
Nincs Initcap() a rustban? :) 
Kapott még egy oszlopot a budapest_01 miatt, ott akkor Budapest lesz

**Comment by vmiklos** [comment]
Ja persze lehet tákolni, csak gondoltam, hogy neked megvan valahol jól is és akkor minek izzadni, hogy előállítsak valami infót amit korábban eldobunk. :)

Köszi, így már megoldató az én oldalam is.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-addr-cities lehet tesztelni

**Comment by vasony** [comment]
Ezeket vártam
