### ISSUE TITLE
Vesszővel elválasztott házszámok hibás felismerése

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#3558]
A [wiki](https://wiki.openstreetmap.org/wiki/Key:addr:housenumber) szerint:

> The number may contain non-digits and if recording multiple house numbers separate them by "," (e.g. "12b,12c").

A gimmisn csak a pontosvesszővel elválasztott értékeket ismeri fel különböző házszámként:

- a `12b,12c` feldolgozás után `12`-ként van felismerve
- a `12b;12c` feldolgozás után `12b`-ként és `12c`-ként van felismerve

**Comment by vasony** [comment]
@urbalazs melyik területen van minta erre?
@vmiklos kéne hint nekem is,  hogy a pythonban hol kell modositani

**Comment by urbalazs** [comment]
Úgy látom, hogy csak akkor jön elő a hiba, ha:

- Betű is van a házszám mindkét tagjában.
- Be van kapcsolva a `housenumber-letters`.

Példa a hibás felismerésre: Budapest XXII., Füttyös utca

- OSM-en: [Füttyös utca 14/A,14/B](https://www.openstreetmap.org/way/53864608)
- A gimmisn-ben [mégis hiányoznak](https://osm.vasony.hu/missing-housenumbers/budapest_22/view-result).

Példa a helyes felismerésre: Budapest XXII., Naphal utca

- OSM-en: [Naphal utca 27,29](https://www.openstreetmap.org/way/525147334)
- A gimmisn-ben [nem hiányoznak](https://osm.vasony.hu/missing-housenumbers/budapest_22/view-result).

Érdemes lenne az összes lehetőségre tesztesetet írni: `12,14`, `12a,14`, `12,14a`, `12a,14a`, `12,14,16`, `12a,14a,16a`.

Ha a wiki szerint vessző kell és nem pontosvessző, akkor jó lenne, ha a gimmisn se fogadná el pontosvesszővel. Akkor azonnal látnánk a hiányzó házszámoknál, ha valami pontosvesszővel lett megadva.

**Comment by vmiklos** [comment]
A https://github.com/vmiklos/osm-gimmisn/issues/613 óta van vessző alapon bontás, és a https://github.com/vmiklos/osm-gimmisn/issues/112 óta van pontosvessző alapon bontás. Korábban javított issue-t nem csinálnék vissza, kivéve a szerző (itt: @vasony ) szerint már nem kell a pontosvessző.

A vessző szerint alapból próbálunk bontani, valószínűleg itt a housenumber-letters beállítással való kombinálás lesz a gond, majd igyekszem megnézni, hogy miről van szó.

@vasony a python is bont vessző mentén általában, itt csak valami corner case hibázik szerintem.

**Comment by vasony** [comment]
> Ha a wiki szerint vessző kell és nem pontosvessző, akkor jó lenne, ha a gimmisn se fogadná el pontosvesszővel. Akkor azonnal látnánk a hiányzó házszámoknál, ha valami pontosvesszővel lett megadva.

Nem a gimmisn-t használjuk QA cuccra, maradjon csak meg a pontosvessző is. A házszám ott van, értelmezhető, tehát nem hiányzik, nem kell kimenni és felmérni csak attól, hogy az általános elválasztó pontosvessző is van benne vessző helyett.
Én nem lennék ennyire szigorú, ahogy az se zavar annyira ha  40a vagy 40/A van a 40/a helyett.

Ha zavar, akkor kérdezd le overpass-szal az összeset és írd át, problem solved.

Térjünk vissza itt az eredeti problémára, a 12a,12b típusra.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_22/view-result lehet tesztelni.

**Comment by vasony** [comment]
Füttyös jó mindkét helyen, zárható
