### ISSUE TITLE
Érvénytelen szűrők kiegészítése, új szintaxis javaslata

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#3562]
A jelenlegi `ranges` szűrők használata körülményes, ha csak az egyik oldalon lévő túl nagy számokat szeretném kiszűrni. Ebben az esetben meg kell adni a másik oldal számait is, mert ha csak a páros oldalra adok meg tartományt, akkor az összes páratlan szám is ki lesz szűrve (ilyenkor használjuk a `{start: '1', end: '999'}` értéket kerülőmegoldásként). Akkor is körülményes a használata, ha egy hosszú utca egy vagy több szakaszát szeretném kiszűrni, mert meg kell adni a kiszűrendő szakasz előtti és utána lévő tartományokat. A helyszínen térképezve azonban csak az adott szakaszt látom, nem tudom, hogy előtte és utána hogyan alakulnak a számok.

Ugyanakkor a `ranges` szűrők használatával egyszerűbben ki lehet szűrni nagyobb tartományokat, mint felsorolni a számokat az `invalid` szűrőben.

Össze lehetne vonni a két szűrőt és egyesíteni az előnyeit az alábbi szintaxissal:

- `invalid: ['1', '5', '20']`: ahogy jelenleg működik, kiszűri a megadott három számot.
- `invalid: ['1', '5-9', '20']`: új szintaxis, tartományok használata az érvénytelen szűrőben, amely kiszűri az 5, 7, 9 számokat.
- `invalid: ['1', '5', '20-']`: új szintaxis, nyílt végű tartomány, amely kiszűri a 20-at és minden nagyobb páros számot (illetve minden számot az `interpolation: all` esetén).
- `invalid: ['-5', '20']`: új szintaxis, nyílt elejű tartomány, amely kiszűr minden páratlan számot 5-ig, azt is beleértve (illetve minden számot az `interpolation: all` esetén).

Ezzel a módosítással nem lenne szükség a `ranges` szűrőre, hanem a funkciója beépítésre kerülne az `invalid` szűrőbe.

Mi a véleményetek erről?

**Comment by vmiklos** [comment]
A range volt előbb, az invalid mint ötlet később jött. Nekem tetszik az a megközelítés, hogy minden gimmisn találat vagy osm szerkesztéssel vagy invalid felvételével oldódik meg. Ez alapján én hajlanék arra, a ranges valamiféle címkét kapjon, hogy az elavult, új relációnál ne használd. Az invalid mostani szintaktikája a fenti megközelítésre elég, szerintem van abban érték, hogy nincsenek benne tartományok, pont azért mert így az egész páros/páratlan/csak egy oldalon vannak házszámok problémakör fel se merül.

Volt már erről szó, sok utca végére idővel kerülnek fel új házak, ha így vagy úgy tartományokkal szűrünk, akkor az egészet fel kell mérni újra és újra ahogy bővül egy település, ami elég macerásan hangzik.

De lehet, hogy valami fontosat szem elől tévesztek. :)

**Comment by vasony** [comment]
Nem teljesen haszontalan a ranges. Nagyon sok utca már teljesen beépített és definit az eleje vége, én nem látom értelmét az ész nélküli kigyomlálásnak. Sok számozási hiba jött ki úgy hogy fel volt véve egy ranges és kilógott belőle a szám és kiderült, hogy nem is arra az utcára van számozva.
Viszont az invalid újra definiálása eltöri a 7.2-es verziót az biztosan, és nekem semmivel nem tud több funkcionalitást mint amit a ranges-zel meg lehet adni több sorban, max szebben néz ki. Nekem az 1..999 is teljesen megfelel a célnak.

**Comment by urbalazs** [comment]
Akkor ezt most lezárom, mert a jelenlegi funkcionalitás megfelelően működik. Ha később mégis akarunk változtatni rajta, akkor majd újranyitjuk.
