### ISSUE TITLE
PA nem frissült pull request után

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#360]
Tegnapi budaors-belvaros nem látszik, és a verzió is egy régebbi commitot mutat.

**Comment by vmiklos** [comment]
Mindjárt ránézek

**Comment by vmiklos** [comment]
pyyaml régi volt a PA instance-en, míg a CI a requirements.txt-ben lévő verzióból dolgozott, most már mennie kell.

**Comment by vasony** [comment]
ok
