### ISSUE TITLE
X, X/1 és X/2 típusú házszámok azonosan vannak értelmezve

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#363]
Úgy látom, hogy az X, X/1 és X/2 típusú házszámok nincsenek megkülönböztetve. Ha egy ilyen házszám szerepel az OSM-en, akkor nem foglalkozik a program ezek megkülönböztetésével.

Jelenlegi helyzet Budafokon:

Referencia:
Liszt Ferenc út	19
Liszt Ferenc út	19/B

OSM (és a valóság):
Liszt Ferenc út	19/1
Liszt Ferenc út	19/2

Hiányzó házszámként jelezve:
19/B

Vagyis a referenciában lévő 19 leképezésre kerül, ha 19/Y meg van adva, ahol Y egy szám.

Elvárt működés:
A hiányzó házszámoknál jelezze a 19-et is, mert az OSM-en nincs 19, csak 19/1 és 19/2.

**Comment by vasony** [comment]
Szerintem anno tettünk egy egyszerűsítést hogy csak a /a típusúak kerülnek be, a többit levágja. ezt ki lehet egészíteni most a /1 típusúakra is. szerintem csak 1 karakteren, a /11 maradna úgy ahogy most.

**Comment by vmiklos** [comment]
Ez így szerintem jogos kérés. A trükk az, hogy míg a betű előtt lehet semmi, space vagy per, addig itt csak per lehet, különben az 1/1 is 11-re normalizálódik, azt meg nem akarjuk.

**Comment by vasony** [comment]
Az invalidnál akkor ['36a', '1/1] vagy egységes lesz?

**Comment by vmiklos** [comment]
150+ invalid van yaml file-okban, én nem bántanám őket. Sok zaj kevés haszonért.

**Comment by vmiklos** [comment]
@urbalazs kérlek próbáld ki, én csak a teszt relációt néztem, remélhetőleg valami valós adaton is majd megy úgy ahogy kell neki

**Comment by vasony** [comment]
megjelentek a /1-ek, a 100% területeimnek megint annyi  :) már vagy harmadszor.
