### ISSUE TITLE
Travis nem fut

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#366]
nem indult el a travis a PR-nél, nem tudtam ellenőrizni

**Comment by vmiklos** [comment]
Írj linket kérlek, hogy hol. Lehet, hogy csak lassú

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/pull/365 ja látom ez lesz az. valószínűleg csak lassú, mindjárt kiderül

**Comment by vmiklos** [comment]
https://travis-ci.org/github/vmiklos/osm-gimmisn/jobs/668298689 elindult az, csak mire odaért, már lezartad :)
Szólj ha máshol is előjönne
