### ISSUE TITLE
Üzletek részletes címeinek megjelenítése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#372]
A "kék" házszámok kattinthatóak lennének, minden házszámhoz tartozik egy id a referenciában.
Ezzel az ID-vel kell átmenni egy másik referenciára és kiírni mindazt ami az adott id-n van.

Pl:
Krisztina 51-53 
ehhez tartozó id: 7000374419

másik referencia, az első oszlop a kulcs, a többit ki kellene raktni egy táblázatba.
```
7000374419	Budai Herbárium	1013 Budapest Krisztina körút 51.	ToDaNet Szolgáltató Korlátolt Felelősségű Társaság	1021 Budapest Budakeszi út 77.	2013.01.01	2017.06.20
7000374419	Budai Herbárium Gyógynövénybolt	1013 Budapest Krisztina körút 51.	Nagy Mária	1116 Budapest Sáfrány utca 42. ix/90.	2009.07.04	
7000374419	Használt Ruha Kereskedés	1013 Budapest Krisztina körút 51.	LADO Általános Kereskedelmi és Szolgáltató Betéti Társaság	1104 Budapest Szentimrey utca 23. B. ép. fszt. 1.	2002.06.10	2017.01.01
7000374419	Ruházati Szaküzlet	1013 Budapest Krisztina körút 51-53.	Ciklonker Kereskedelmi és Szolgáltató Korlátolt Felelősségü Társaság	1013 Budapest Krisztina körút 51-53.	2009.01.01	
```

első kérdés, ez belefér-e, hogy publikáljuk a cégadatokat
második megvalósítható-e

**Comment by vmiklos** [comment]
Hááát :) a govcenter.hu nem ad olyan linket amibe csak be kell helyettesíteni a 7000374419-et? A konkrét nem-hazszam adatokat nem szeretném tartozni, macerás. GDPR, stb.

**Comment by vasony** [comment]
GDPR nem játszik, mert céges nyilvános adat, nem személyes, de rendben, azért is kérdeztem.
Viszont az eredeti házszámok jó lennének, minimális tartalommal.

ez?
```
7000374419	1013 Budapest Krisztina körút 51-53.	2009-	kiskereskedelem
7000374419	1013 Budapest Krisztina körút 51.	2002-2017	kiskereskedelem
7000374419	1013 Budapest Krisztina körút 51.	2009-	kiskereskedelem
7000374419	1013 Budapest Krisztina körút 51.	2013-2017	kiskereskedelem
```

**Comment by vasony** [comment]
Vagy egy cím csak egyszer:
```
7000374419	1013 Budapest Krisztina körút 51-53.	2009-	kiskereskedelem	1
7000374419	1013 Budapest Krisztina körút 51.	2009-	kiskereskedelem	1
```

**Comment by vasony** [comment]
govcenterre úgy lehet csak linkelni ha post kérés megy.

**Comment by vmiklos** [comment]
OK, mi van a házszám TSV-ben bevezetünk egy 5. "megjegyzés" oszlopot, és oda rakhatsz amit jól esik? És tooltipben tudnánk mutatni ezt az infót. Annyi a korlátozás, hogy 1 soros kell, hogy legyen és ne legyen benne tab.

https://stackoverflow.com/questions/1055581/how-do-i-add-a-tool-tip-to-a-span-element

Nem kattintható, de segítséget u.úgy ad a kereséshez.

**Comment by vasony** [comment]
meg több sorra is, akkor jó lesz ez, csak a teljes címet rakom bele, főleg akkor van értelme amikor ilyen 2/Q-ra képzem le a címet, akkor jobb látni mi van

https://stackoverflow.com/questions/3340802/add-line-break-within-tooltips

**Comment by vmiklos** [comment]
Ja, ha &#013; a linebreak és nem tényleges \n akkor jók vagyunk. Majd gimmisn oldalán kell odafigyelni, hogy ne legyen escape-elve. :-)

**Comment by vasony** [comment]
Itt egy teszt html oldal:
http://www.vasony.hu/temp/teszt.html

**Comment by vasony** [comment]
csak azoknál kel title ahol van érték, nem tudom a title="" milyen hatásal jár

**Comment by vmiklos** [comment]
Világos, azt egyszerű kiszűrni.

**Comment by vmiklos** [comment]
Ez egy nagyobb falat, első lépés, hogy a workdir/street-housenumbers-reference-NEV.lst tartalmazza ezeket a részleteket, aztán onnan lehet tovább haladni.

**Comment by vmiklos** [comment]
@vasony ha pullozol, majd a refdirből a .pickle cache-eket (file-okat) töröld, változott a formátum.

A UI még hiányzik, szóval látható változás még nincs. :-)

**Comment by vasony** [comment]
ok, bekerültek, megnéztem :)

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/orbanhegy/view-result Fodor utca 32-34-nél lett pl tooltip. Jó lesz?

**Comment by vasony** [comment]
megnezem desktopon.
mobilon is jó lenne
itt egy minta nem tudom megy e ez az abbr tag

https://codepen.io/hershkirsh/pen/wvamaGw

**Comment by vmiklos** [comment]
Abbr további előnye, hogy ha 10 szám között mozogsz, akkor van vizuális visszajelzés, hogy melyik hazszamhoz tartozik a tooltip.

**Comment by vmiklos** [comment]
Vélemény? :-)

**Comment by vmiklos** [comment]
Ja most látom, hogy abbr esetén is kell CSS, hogy menjen mobilon

**Comment by vmiklos** [comment]
Na most!

**Comment by vasony** [comment]
alapvetően jó, még kísérletezek hogy lehetne (mobilon) a tootlipet bal oldalra rendezni

**Comment by vasony** [comment]
(mobilon kell nézni)
http://www.vasony.hu/temp/osm.html
``position: relative``-val nem tudom megoldani, hogy jobb oldalra kihúzza. ha flex-end-re veszem, akkor meg levágja az elejét.

itt egy másik próbákozás, itt fixen lejjebb teszem 20px-lel, szerintem ez nálam nagyjából jó
http://www.vasony.hu/temp/osm2.html

az biztos, hogy le kell rövidíteni a szöveget, mert a 1124 Budapest kiírása csak a helyet veszi el.
a másik hogy csak a ``&#10;˛`` megy a sortörés, át kell alakítanom a kimenetet.

az abbr-hoz lehet tenni kék szinezést a css-ben és akkor nem kell span
de ha meg nincs abbr akkor meg kell, végül is mindegy.

**Comment by vmiklos** [comment]
Ha &foo;-t teszel bele, az escape-elve lesz, a &#013; az kivétel, azt explicite cserélem \n-re.

Az abbr és szín dolgot én nem bántanám, a megjegyzés, meg hogy mi a forrás elvileg ezek független dolgok.

Az, hogy a CSS pontosan milyen legyen, az nekem kb mindegy. :) Jó az, hogy kipróbálod az instance-eden, hogy neked mi tetszik és PR-be beküldöd a CSS változtatást? És  akkor ezt le lehet zárni. 21 comment után kezd áttekinthetetlen lenni. :)

**Comment by vasony** [comment]
dehogy, mindig csak az utolsót kell olvasni :) egyébként ok.
