### ISSUE TITLE
Cron frissítés terület név alapján

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3744]
osm-gimmisn cron --help

Options:
      --refcounty <refcounty>          limit the list of relations to a given refcounty
      --refsettlement <refsettlement>  limit the list of relations to a given refsettlement

emellé kellene egy terület név szerinti opció is, pl:
     --refarea=alsoors

**Comment by vmiklos** [comment]
Lehet róla szó

**Comment by vmiklos** [comment]
Tesztelhető.

**Comment by vasony** [comment]
kíváló
