### ISSUE TITLE
Invalid addr cities frissítése kézzel

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3768]
https://osm.vasony.hu/lints/whole-country/invalid-addr-cities

Szeretnék egy gombot, hogy kérje le újból az összes házszámot és vizsgálja meg újra. Sokszor van, hogy egyes elemek már ki vannak javítva, és nem lehet tudni, hogy kimaradt-e valami.

b) opció, hogy csak a listában lévő id-kre frissít be

**Comment by vmiklos** [comment]
Lehet róla szó, csak ki kell találni a módját. Jelenleg ez úgy megy, hogy naponta a cron frissíti a workdir/stats/whole-country.csv-t, és abból számol még mindig a cron, feltölti a stats_invalid_addr_cities sql táblát, majd ezt mutatja a webes felület.

Az sql tábla tartalmát újraszámolni nem nagy gond, de gondolom te azt szeretnéd, hogy a whole-country.csv is frissüljön. Viszont akkor a whole-country.csv már nem a napi fix időpontban lekért snapshot lesz. Ez belefér?

**Comment by vasony** [comment]
Szerintem most menjünk az egyszerűbb irányba akkor.
stats_invalid_addr_cities táblából csináljon egy overpass lekérdezést (id szerint gyorsan lefut), és ennek eredményén futtassa le az ellenőrzést. Így most nem lesznek benne az újak, de most nem is ez a cél, majd szövegben akkor nem az kell hogy frissítés, hanem újra ellenőrzés vagy vmi ilyesmi.

**Comment by vmiklos** [comment]
Az egyszerűbb irány nekem az lenne ha csak azt az építőkockát vezetném ki egy gombra ami már most is megvan, hogy lefrissítem a létező overpass query alapján a whole-country.csv-t, és az alapján újrafuttatom a lintet. Ez ugye megtalálná az új esetelket is.

Ha jól rémlik, akkor ezt a whole-country.csv-t te szoktad diffelgetni: ha annyit meg tudsz tenni, hogy a cron futás után csinálsz róla másolatot és azt diffeled akkor elvileg ez a megoldás egyszerű (nekem) és hozza is amit kértél. Szóval már csak az a kérdés, hogy részedről van-e bármi gond azzal, ha nap közben random alkalommal is frissül a whole-country.csv, ami eddig mindig csak naponta 1x frissült? Ha nincs, akkor szerintem legyen ez.

**Comment by vasony** [comment]
Csinálok róla másolatot, ezzel nincs gond.

**Comment by vmiklos** [comment]
A fenti után a lényeg megvan, az URL végére egy `/update-result` és akkor lehet csak a .csv-t meg ezt a lint eredményt frissíteni.

Kell még linkelni ezt az oldalt a lint oldalról.

Gondolom szép lenne ha erre is menne a szokásos JS loader, mint a házszámok frissítésénél, ugye?

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-addr-cities most már van update from osm gomb is.

**Comment by vasony** [comment]
> Gondolom szép lenne ha erre is menne a szokásos JS loader, mint a házszámok frissítésénél, ugye?

igen, de nem kritikus, a lényeg már megvan.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/lints/whole-country/invalid-addr-cities lehet tesztelni, JS esetén most már a szokásos loader jön be (per pill üres a lista, update után lesz pár találat).

**Comment by vasony** [comment]
Szuper.
