### ISSUE TITLE
Validátor továbbfejlesztése összetett házszámokra

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#380]
ezekre kellene szólnia, mert ez így hatástalan
invalid: ['1c 1']
invalid: ['19-21']

lehet a másik irányból kell megközelíteni
csak a ['1', '1c', '1/1'] típusok engedélyezettek

**Comment by vmiklos** [comment]
> csak a ['1', '1c', '1/1'] típusok engedélyezettek

Igen, ez a megközelítés tűnik jobbnak.

**Comment by vmiklos** [comment]
Jó lesz így? Talált is két hibát, javítottam őket best-effort jelleggel. CC @urbalazs

**Comment by vasony** [comment]
ha megtalálta ezeket, akkor jól működik :)
