### ISSUE TITLE
Stat trendline

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#381]
Emailből átemelve

> Ez a grafikon készítő nem tud mozgó átlagot, vagy trendet?
> Valami ilyesmi nézne ki jól:
> https://github.com/chartjs/Chart.js/issues/458

Ha jól látom az csak egy kombinált chart típus.
"chart.js trendline"-ra keresve ilyesmit találtam pl:

https://github.com/Makanz/chartjs-plugin-trendline

**Comment by vmiklos** [comment]
Nem próbáltam a fentit, de ha működik, akkor kicsit körbe kéne járni a témát: melyik chartokra érdemes ezt bekapcsolni, milyen paraméterekkel ad értelmes eredményt, ilyesmi.

Ezzel te is tudsz kísérletezni, elég hozzá static htmlbe lementeni a stat oldalt.

**Comment by vmiklos** [comment]
Lehet tesztelni:

https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/#_monthly

Ez egész biztatóan néz ki amúgy :)

**Comment by vasony** [comment]
tényleg ez a "linear trendline", és jó is

Már csak az a kérdés, hogy vannak-e opciói ennek a trendline-nak, mert excelben van olyan, hogy x period moving average. (van olyan, hogy mi adjuk meg a második vonal értékeit), mert az egyel jobban nézne ki ott ahol oszlop diagramok vannak, az adataink megvannak hozzá elvileg.  

pl 3 period:
https://d295c5dn8dhwru.cloudfront.net/wp-content/uploads/2018/09/15030404/Screen-Shot-2018-09-15-at-9.54.24-AM.png

Ha nincs ilyen, akkor zárható.

**Comment by vmiklos** [comment]
https://github.com/Makanz/chartjs-plugin-trendline/blob/ff87e891cf5327bb3946301160fe80aafe1e42bc/src/chartjs-plugin-trendline.js ezt a 3 opciót tudja, nem túl bonyolult. :-)

A "period moving average" érdekes lenne, de sztem ha ilyen kell, akkor először ebbe a fenti pluginbe kéne belefejleszteni, és ha oda bekerült, akkor lehet itt is használni. (De így elsőre ez engem most ennyire nem izgat.)
