### ISSUE TITLE
Érvénytelen addr:city értékek története utólag frissül

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3818]
https://osm.vasony.hu/housenumber-stats/whole-country/#_stats-invalid-addr-cities

Érvénytelen addr:city értékek története statisztika nem az éjszaki frissítési dátumot tárolja el, hanem az utolsó frissítéskori dátumot veszi.

Tegnap este 
2023-03-29-re: 2 db volt

Rányomtam este a frissítésre
Ma reggel
2023-03-29-re: 55 db volt
2023-03-30-ra: 55 db volt

Mentse el az első alkalommal egy stat táblába az értéket aznapra, és az már ne frissüljön az oldal frissítésénél.

**Comment by vmiklos** [comment]
Megoldható, ha jól tippelek, akkor annyi az egész, hogy itt:

https://github.com/vmiklos/osm-gimmisn/blob/bde38be33a411553eb5add062fbaf949d66401a3/src/stats.rs#L595-L599

Az on conflict rész kuka, és ha hibát dob az insert akkor nem csinálunk semmit. (De azért ezt ki is kell, próbálni.)

**Comment by vmiklos** [comment]
lehet tesztelni, nekem jónak tűnik

**Comment by vasony** [comment]
jó
