### ISSUE TITLE
osm-gimmisn sync-ref funkció bővítés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3826]
target/release/osm-gimmisn sync-ref --mode download --url https://osm.vasony.hu/data/

a config rendben, a fájlok a helyükön, a letöltést nem kell elvégezni, csak a táblák ürítését és a friss ref betöltését

target/release/osm-gimmisn sync-ref --mode local vagy
--mode refresh

**Comment by vmiklos** [comment]
Megoldható

**Comment by vmiklos** [comment]
`osm-gimmisn sync-ref --mode local`, lehet tesztelni.

**Comment by vasony** [comment]
működik, kösz
