### ISSUE TITLE
Stat - havonta

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#383]
Új házszámok, havonta - 2019-04-nél indul
Minden házszám, havonta - 2019-05-nél indul

lehet csak engem zavar :)

**Comment by vasony** [comment]
tudom mi a baj, csak a felirat rossz a "Minden házszám, havonta"-ban, igazából a mostani 244553 a március 31-ig állapot, szerintem ezt nem kellene 2020-04-nek hívni, ha mindegyikből levonsz 1-et, akkor egyforma lesz.
Illetve ide is be lehet tenni a lezáratlan hónapot.

**Comment by vmiklos** [comment]
Eredetileg 2020-04-01 volt, ezt egyszerűsítettük 2020-04-re. Ami jó ötletnek tűnt, de persze így már annyira nem egyértelmű, hogy a 2020-04 az a hónap elejét, vagy végét takarja. Egész pontosan 2020-04-01 00:05-öt takar. Lehet a "All house numbers, monthly" esetén mégis vissza kéne rakni azt a napot a címkébe, hogy egyértelmű legyen?

**Comment by vasony** [comment]
ne, ne rakjuk vissza, akkor maradjon így.
Futtasd 23:59-kor és akkor elégedett leszek 😄 nyilván first world problem.
igen, nekem a hónap végét takarja alapból, mert a "2020-03" = márciusban keletkezett házszámok és az nem hónap eleje, de ez igen, nézőpont kérdése. az hogy 0:05-kor fut, az meg csak technikai.

**Comment by vasony** [comment]
zárd le ha nem akarod átírni wontfixel.

**Comment by vmiklos** [comment]
2 részt szerintem érdemes megvalósítani:

- a yyyy-mm-dd -> yyyy-mm rövidítés óta nem egyértelmű, hogy mit jelöl egy oszlop, ezt el lehetne jobban magyarázni, ott van rá az x tengely felirata

- az "All house numbers, monthly" utolsó oszlopa most ápr 1, utána még lenne értelme a legújabb napi adatnak.

Maradjon ez nyitva amíg ezek nem készülnek el.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
monthly_total: include today's count as well: én ezt nem látom 244e van 2020-04-nél

**Comment by vasony** [comment]
na most megjelent a frissítés után, szerintem zárhatjuk
