### ISSUE TITLE
invalid tag - simplify

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#385]
Az alap szituáció, hogy nincs 37/B, ezt el tudom nyomni 
```invalid['37']```-tel, ha ```housenumber-letters: false```  
```invalid['37b']```-vel, ha ```housenumber-letters: true```  

ha átfutna a simplify rajta, akkor nem kellene kétféleképp megadni, elég lenne a teljes házszám, és ha később bekapcsolom true-ra, akkor is jó lesz.

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenvolgy/view-result#
Kővirág sor	[3, 9/B, 37/B..

filter:
```
  Kővirág sor:
    invalid: ['37b']
```

**Comment by vmiklos** [comment]
Ezzel nem lesz olyan baj, hogy 37/C hiányzik, bekapcsolod a housenumber-letters: true-t, és a 37 továbbra is kitakarja, és jön az issue, hogy miért nem találta meg a hiányt?

**Comment by vasony** [comment]
csak a false-nal kell futtatni.

**Comment by vmiklos** [comment]
Ah, így már volna értelme, igen.

**Comment by vmiklos** [comment]
Lehet tesztelni :)

**Comment by vasony** [comment]
Eltűnt a 37b úgyhogy jó :)
