### ISSUE TITLE
refstreets ellenőrző bővítése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3850]
'Kiscséri új telep': 'Kiscséri új telep' típusú mapre dobjon hibát (osm=ref)

https://github.com/vmiklos/osm-gimmisn/commit/2257816967e8af7697a316c7dd2e74a33779a539

**Comment by vmiklos** [comment]
Lehet róla szó

**Comment by vmiklos** [comment]
Ez a kettő ugyanaz, a validátor is tud érte szólni, ott jobb lenne, nem?

**Comment by vmiklos** [comment]
lehet tesztelni

**Comment by vasony** [comment]
@vmiklos csinálsz windows binárist?

**Comment by vmiklos** [comment]
Persze, https://github.com/vmiklos/osm-gimmisn/releases/tag/v24.8-rc1

**Comment by vasony** [comment]
"csak" :) fél évente 1x inkább megkérlek :)
