### ISSUE TITLE
cron.py loggolás

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#388]
```
update_osm_housenumbers: try #11
update_osm_housenumbers: http error: HTTP Error 429: Too Many Requests
update_osm_housenumbers: try #12
update_osm_housenumbers: http error: HTTP Error 429: Too Many Requests
update_osm_housenumbers: try #13
```

1) cron console: kérhetnék ugyanazt ami a cron.log-ba is került? itt nincs dátum

2)  itt már volt szó. #228

itt nem kapjuk vissza, hogy mennyit kell várni, hogy ne legyen 429-es error? mert úgy tűnik néha nem, akkor mennyit vár?

3) 
```
update_osm_housenumbers: try #19
update_osm_housenumbers: end: budapest_13
```
ha 19x megpróbálta újra, akkor lép a következőre?

**Comment by vasony** [comment]
4. esetleg másik overpass instance
pl: https://overpass.kumi.systems/api/status

Connected as: 1608056550
Current time: 2020-04-11T13:24:03Z
**Rate limit: 0**
Currently running queries (pid, space limit, time limit, start time):

még nem próbáltam

**Comment by vmiklos** [comment]
> 1. cron console: kérhetnék ugyanazt ami a cron.log-ba is került? itt nincs dátum

Persze.

> 2. HTTP Error 429: Too Many Requests

Ez elvileg két okból fordulhat elő: vagy az overpass hülyeséget mond (várj 4 secet, vársz, majd panaszkodik) vagy a cronon kívül az adott IP-ről más is csinál overpass lekérdezéseket, ilyenkor nem meglepő, ha 4sec várakozás után továbbra se szolgál ki téged az overpass. Ez utóbbit próbálom most is kezelni, ha azt kapjuk, hogy várni kell, akkor nem csak várunk, hanem újra megnézzük, hogy kell-e várni és csak akkor megy a tényleges request ha már 0-t kapunk a várakozásra.

> 3. ha 19x megpróbálta újra, akkor lép a következőre?

Igen. Lásd:

https://github.com/vmiklos/osm-gimmisn/blob/d55833aa2d31a7b494d6129cdebb25f25a0362c4/cron.py#L43-L53

A sikeres és a sikertelen csak annyiban különbözik, hogy sikeres esetén a többi próba kimarad és nem jut el 20-ig.

Amúgy érdekes, én nem szoktam errorokat kapni, de itt is ~50p körül van egy teljes futás (inaktívokat ha beleveszem).

TLDR: a dátumot majd berakom a konzolos kimenetre is, a többi úgy tűnik megy ahogy kéne neki.

**Comment by vasony** [comment]
ok, néztem 429 közben az /api/status azt adta vissza hogy 2 available, valami nem stimmel azzal a szerverrel. errő ip-ről nem próbálkozik senki, ez egy business fix ip, hétvége kutya nincs bent.
na mindegy, a másik szerverrel nem volt gond, akkor marad az 1)

**Comment by vmiklos** [comment]
Lehet tesztelni. :-) Ha már ez volt a téma, akkor a konzolos kimenetből a loglevel is hiányzott, most az is konzisztens.

**Comment by vasony** [comment]
szuper, fogynak az issuek :)
