### ISSUE TITLE
overpass api instance paraméterbe

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#389]
overpass szerver nevét lehessen megadni paraméterben.
ld #388

**Comment by vmiklos** [comment]
Persze, miért ne. Nem tudtam, hogy van más instance is.

**Comment by vmiklos** [comment]
Jó lesz?

**Comment by vasony** [comment]
vissza kellett térjek a standardhoz, órák múlva sem volt ott a friss adat a kumi-s overpasson. sajnos nem találtam meg sehol, hogy mennyi a frissülése.
