### ISSUE TITLE
invalid:[] szűrési lehetőség bővítése tartományokkal

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#3892]
Az eddigi szűrési lehetőségek bekapcsolt letters esetén néha nehézkesek. 

Jelenleg az engedélyezett értékek:

['14', '14a', '14/1', '16', '18, '20']

javasolt bővítési lehetőség:

['14-24', '102b-104', '104b-c']

Úgy kéne módosítani a ref felolvasást, hogy első körben az invalid tömbből ki kellene venni azokat, amikben kötőjel van, ezek lennének az első szűrők, ezzel szűrnénk meg a ref-et. Parseolni nem kell, a refből viszont a szűrésnél a perjeleket ki kell szedni és a kisbetűsítést meg kell tenni.
Ebből előállt ref listával mennénk tovább a meglévő módszerrel.

Minta: 
**Refben**

**42**
44-46
**48**
48/A
**40-60**
50/A
**50/A-B**

**invalid szűrő**
invalid: ['42', '40-60', '48', 50a-b']

**1. körben szűrt, konvertált ref**
**42**
44-46
**48**
48a
50a

**2. körben szűrt, parse-olt ref**
44
46
48a
50a

**Comment by vmiklos** [comment]
Ok, ez megoldhatonak tűnik

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
Budafoki út 59-63-at megadtam, jó szűr, viszont itt még fixálni kell, mert fals pozitív
https://osm.vasony.hu/missing-housenumbers/budapest_11/view-lints

**Comment by vmiklos** [comment]
Megnézem.

Addig is új validator exe itt: https://github.com/vmiklos/osm-gimmisn/releases/tag/v25.2-rc1

**Comment by vmiklos** [comment]
Próbáld meg most, a mínuszosokból most már csak azokért szól, amiket tényleg nem használ.

**Comment by vasony** [comment]
Szerintem az additionalt nem veszi figyelembe: Budaörsi út 172-188 bent van a filterben, nem szűri ki és az ellenőrzésen is ott van hogy törölve a referenciából

**Comment by vmiklos** [comment]
Azt hiszem nem tudlak követni :)

Írsz linket, és hogy ott mi nem jó és mit szeretnél helyette?

**Comment by vasony** [comment]
https://osm.vasony.hu/missing-housenumbers/budapest_11/view-result#

Budaörsi út 172-188 megjelenik mint hiányzó, pedig itt szerepel a szűrú
https://github.com/vmiklos/osm-gimmisn/blob/1d6fa1ed6f04d883ee5b377e389d54b89b20d22c/data/relation-budapest_11.yaml#L385

**Comment by vmiklos** [comment]
OK, látom, meg fogom nézni.

**Comment by vmiklos** [comment]
@vasony nálam most már jó, nálad kell egy `touch data/relation-budapest_11.yaml`, hogy ne a cache-ből jöjjön az eredmény. Lehet tesztelni.

**Comment by vasony** [comment]
szerintem most már jó lesz, ugyan a 100/c-102/a típust nem teszteltem, ha beakad vhol majd felveszem külön.
