### ISSUE TITLE
cron.all

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#390]
```
    # Query inactive relations once a month.
    relations.activate_all(time.localtime(start).tm_mday == 1)
```
ide szeretnék kérni valamit, hogy tényleg cronól tudjam vezérelni, hogy mikor kérek teljest és mikor csak a paraméterezettet.

Most kézzel lemásoltam a cron.py-t egy cron.all.py-re és erre átírtam:

    relations.activate_all(True)

de luxus 2 ugyanolyan python ami 99%-ban egyezik, ötlet? lehet adni paramétert egy python file-nak? pl: cron.py -all?

**Comment by vmiklos** [comment]
Igen, a `cron.py --all` jó javaslat. Ez, hogy elsején máshogy fut, mint a többinapon csak egy pythonanywhere-es workaround, más instance esetén érdektelen, és inkább az a kérdés, hogy mindig így vagy úgy fusson.

**Comment by vasony** [comment]
nos ide még szeretnék újabb paramétert ha már hozzányúlsz.
--filter=01  -- csak Budapest
--filter=01/011 -- csak Budapest/11

persze lehet más szintaxis is
--refcounty=01
--refsettlement=011

**Comment by vmiklos** [comment]
Fogok csinálni config opciót, hogy az inaktív relációk frissüljenek-e. A `--all` mégse jó elnevezés ha később lesz stat meg hiányzó házszám/utca mód, hiszen akkor az az "all" félrevezető lenne.

Utána jöhet a szűkítés refcount/refsettlemenetre.

A "csak azt ahol nincs generált adat" mód is lehet, de inkább `--no-update`-nek hívnám, megint a "missing" elnevezést kerülendő (stat vs missing mód ami vagy egyszerre fut, vagy csak a kért rész).

**Comment by vasony** [comment]
a config azért nem jó hosszú távon, mert ha 2x akarom egy napon belül meghívni kétféleképp, akkor nem fogom tudni, ezért kellett volna paraméterben.
persze most épp nem akarom.

**Comment by vmiklos** [comment]
Rendben, ha lesz ilyenre szükség, akkor majd lehet csinálni cmdline opciót is ami felülírja a config-ból jövő defaultot. :-)

Most ezt az issue-t limitáljuk arra, hogy legyen még `--refcounty`, `--refsettlement` és `--no-update`, ne bővítsük tovább.

**Comment by vasony** [comment]
ok, lehetne kezdeni a `--no-update` paraméterrel? persze csak ha külön akarod őket fejleszteni.

**Comment by vmiklos** [comment]
Jó lesz?

**Comment by vasony** [comment]
doc?

**Comment by vasony** [comment]
egyébként tökéletes. kipróbáltam minden kombinációban.

**Comment by vmiklos** [comment]
`--help` értelmes eredményt ad, írtam minden switchhez helpet :)

**Comment by vasony** [comment]
és ha nem tudja valaki hogy vannak paraméterek? :) lehet csak annyit kellene írni a dochoz hogy `--help`

**Comment by vmiklos** [comment]
Az mondjuk jogos.
