### ISSUE TITLE
invalid szűrje a *-osokat is

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#396]
valószínű a 1/1 típusnál valami gebasz van az invalid filterrel

https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/kelenfold/view-result.txt
Etele út	[67/5*]

pedig:
```
filter:
  Etele út:
    invalid: ['32', '58b', '67/5']
```

**Comment by vmiklos** [comment]
Igen, ez tényleg nem tűnik jónak.

**Comment by vmiklos** [comment]
Jó lesz?

**Comment by vasony** [comment]
Megjelent egy csomó korábban elnyomott házszám.

Fraknó utca	[10/6, 10/9]

Valószínű eddig volt rossz, mert nem volt elnyomva.
    invalid: ['4a', '6', '8', '10', '10h', '12', '14', '16', '16d', '18', '18c', '20', '22', '22d', '24', '26', '28', '30', '40']

**Comment by vasony** [comment]
Remélem ez is valami KCR faszság lesz, mert most rémlik, hogy új táblát tettek fel a Nagyszőlős 21/1-re
Még megnézem más területre is, mielőtt lezárjuk.

**Comment by vasony** [comment]
szerintem ezt lezárom, ha van valami lesz saját issue.
