### ISSUE TITLE
wsgi több szálon

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#398]
hol van megszabva, hogy a wsgi 1 szálon fut csak? mert eddig a PA miatt gondoltam, hogy így van, de a most is így van, amíg az egyik request nem végez, addig nem megy más.

**Comment by vmiklos** [comment]
A wsgiref nem tudom, hogy tud-e több szálon futni, de amúgy se tudja automatikusan újratölteni a kódot, szóval helyi fejlesztésre jó, meg egyszerű a kódja (könnyű tanulmányozni), de amúgy ahogy tudom ennél sokkal többre nem jó.

Ha a `cherry.py`-n keresztül indítod az appot, annak kéne tudnia több szálon futnia, jelenleg ez be van drótozva 8-ra, de ha ez segít, akkor megoldható, hogy automatikusan annyi szálat használjon, amennyit a HW enged, vagy akár config opció is lehet.

A PA-t most nem tudom fejből, a mostani VM-en 1 logikai CPU van, szóval az én instance-emen csak annyi értelme van a többszálúsításnak ha valaki nagyon lassú kapcsolattal próbál meg elérni egy nagyon sok kimenetet generáló oldalt, valós HW thread csak 1 lesz mögötte.

**Comment by vasony** [comment]
király, a wsgi-hez képest ez egy 🚀
