### ISSUE TITLE
https://osm-gimmisn.vmiklos.hu nem frissül

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#401]
nem vette fel az új relációkat a listába a te példányod. 
Az osm.vasony.hu-n megjelentek.

Pedig mindkettő a 5.0.13-at ír.

**Comment by vmiklos** [comment]
Jól látom, hogy a relations.yaml nem hivatkozza az új relaciot? Nem azért hiányzik?

**Comment by vmiklos** [comment]
Ja nem, látom, hogy a webhook elhasalt félúton (a verzió frissült, az adatok nem). Fogok csinálni logolást a webhookba és akkor többet tudunk, most csak ennyit kaptam, hogy

```
subprocess.CalledProcessError: Command '['make', '-C', '/home/osm-gimmisn/git/osm-gimmisn/', 'deploy-pythonanywhere']' returned non-zero exit status 2.
```

Ami nem elég infó.

**Comment by vmiklos** [comment]
Rájöttem, hogy nem kell logolás, a systemdnek volt logja, és az volt a baj, hogy nem találta a virtualenvből a modulokat. balatonalmadit most beraktam és szépen bekerült automatikusan. Jó lesz?

**Comment by vasony** [comment]
azóta jött más is és bekerült.
