### ISSUE TITLE
budapest_12 invalid filterek átemelése területekből

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#404]

**Comment by vasony** [comment]
hát ez sok meló, viszont már találtam egy pár hibát a filterekben.

**Comment by vmiklos** [comment]
Amúgy a 12. kerület összes városrésze már eddig is fel volt véve? Nem tudom, én csak ad-hoc vettem eddig fel relaciokat.

**Comment by vasony** [comment]
igen, felvettem őket korábban. 01-11-12-22 az teljes, a 02-nek a belső része, a többi adhoc.

**Comment by vasony** [comment]
@vmiklos Sashegy és Krisztinaváros is szenvedett olyantól, hogy nem volt megosztva az út. kerületek között.
Pl. Krisztina körútra nem volt filter, mert az egész Krisztinavárosban volt, de így csak az 1. kerületi részt vette figyelembe.
Felkészül Újlak

**Comment by vmiklos** [comment]
Aha, szuper. Azon gondolkozom, hogy van-e értelme koordinálni, hogy egy kerületen belül melyik relációt ki próbálja meg felhúzni 100%-ra.

https://osm-gimmisn.vmiklos.hu/osm/filter-for/refcounty/01/refsettlement/012

Ebből én most csinálom az Orbánhegyet a magam tempójában, de ha többen nekiállunk véletlenszerűen kiválasztott relációknak, akkor egymás lábára lépés lesz belőle, mint ahogy a xi. kerületben volt is ilyen (ezért is mentem el a xii ker irányába). Ha csinálunk ilyesmit, hol érdemes ezt megtenni? Sztem ez nem ide (gimmisn issue tracker) tartozik; de mondjuk a magyar osm wikibe egy táblázat? Vagy van ez a grin-féle task manager amit én sose használtam, de ha azt mondod az jobb erre, az is megfelel. Vélemény?

Hasonló helyzet a xi. kerület is, ott is közel a 100%, valszeg koordinálni kéne a maradék munkát.

**Comment by vasony** [comment]
Én nem látom ezt olyan súlyosnak, mielőtt elindulok megnézem mi hiányzik még, azzal dolgozom.
Veled ellentétben én egyszerre 3-4 területtel dolgozom, és nem akarnám lefoglalni egyiket se magamnak, épp merre járok, van 3 fix porgram a héten, az 3 terület :-)

Wiki táblázat elég lehet, hogy kiderüljön ha valaki kitűzte célul az egyik terület 100%-ra húzását, de lehet csak akkor ketten fogunk szerepelni benne, nem tudom beírnák-e magukat
Task managerben csak 2 órára lockolod a területet az nem túl jó.

A nagyobb kérdés, hogy bárki megnézné-e mielőtt elkezd dolgozni ha külön oldalon van
Mondjuk ha a wiki-ben lenne egy táblázat, és azt behúznánk automatikusan a gimmisn-be
adott reláció elejére, és ott (is) megjelenne egy 1 soros üzenet, akkor egyértelmű lenne:

pl:
http://www.vasony.hu/temp/warning.html

**Comment by vmiklos** [comment]
Ah, értem. Ha a wiki meg a task manager nem segít ilyesmiben akkor sztem felejtsük el a dolgot, annyit nem ér. Köszi az ötletelést. :-) És bocs, igazából ez az egész nem nagyon tartozik ide ebbe az issue-ba.

**Comment by vasony** [comment]
részek összessége: 1450 db hiányzó házszám (72,24% kész)
budapest_12: 1269 db hiányzó házszám (76.67% kész)
még nyomozom a különbséget.

mellesleg
budapest_11:  762 db hiányzó, aminek egy része hrsz.

**Comment by vasony** [comment]
Azt hiszem még a filterekkel kell dolgozni:

Svábhegy:
Agancs út	[25/B], [18, 24, 36, 40]
Széchenyihegy:
Agancs út	[25/B], [4, 12, 16 B, 18, 20/A, 24, 26, 28-30, 30-32, 36, 40]

**Comment by vmiklos** [comment]
Gondolom olyan lehet ahol egy út merőleges a városrész határára, és így kerület szinten nincs fals hiányzó házszám, városrész szintén viszont ezeket el kell nyomni filterrel.

**Comment by vasony** [comment]
Ezek ilyen összevissza utcák, ahol lemaradt az egyik területről a filter. 
Egy pár javítva ``A-G``, a többi majd később, majd egyben töltöm fel, Orbánhegy is érintett, hétvégéig meglesz.

**Comment by vasony** [comment]
Elkészült, 2. kör. 
suburb sum: 1450 db -> 1261 db + sashegy 14 + krisztinavaros 2 = 1277 db
budapest_12: 1269 db ->1276 db

most már csak azért is megnézem azt az 1 különbséget

@vmiklos bocs lefeleztem Orbánhegy hiányzókat, de pont nem voltak jók a filterek.

**Comment by vasony** [comment]
3 különbség volt:
- bp12: Stromfeld Aurél kimaradt az 5 kiszűrése
- városrészek: 1-1 házszám átlógott: Költő utca, Szilágyi Erzsébet fasor

**Comment by vmiklos** [comment]
A 12. kerületben összesen 1073 hiányzó van, eredetileg a kerületet azért bontottuk, mert több mint 2000 volt és túl nagy volt. Mi lenne ha a jelenlegi állapotra való tekintettel a 12. kerületi városrészeket felszamolnank?

2 előnyt látok: ha van ilyen, több városrész határ miatt szükséges filtert nem kell feltenni, illetve akkor a kerület VS városrész duplikacio megszűnne, a jövőben nem tud eltérni egymástól.

Vélemény?

**Comment by vasony** [comment]
Mehet tőlem, azt a pár újat Svábhegyből még be kell rakni.

**Comment by vasony** [comment]
csinálom

**Comment by vmiklos** [comment]
Köszi!

**Comment by vasony** [comment]
budakeszierdo marad, de 2. kerület lett belőle, oda átlóg.

**Comment by vasony** [comment]
most jöttek jól az aliasok
