### ISSUE TITLE
gyógyszertár címek beemelése referenciába

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#405]
https://ogyei.gov.hu/?url=gyogyszertarkereso

**Comment by vasony** [comment]
kész. 
@vmiklos: majd ref frissítés szükséges
hazszamok_kieg_20200727.tsv
utcak_20200727.tsv

**Comment by vmiklos** [comment]
754fc17d659b09e6c7a686ca9f8aff0c07d680d9

Mindkettő befrissítve.

**Comment by vasony** [comment]
lemardtak a /a-k a házszámokból
Balatoni út 2/a -> Balatoni út

**Comment by vasony** [comment]
@vmiklos megint, majd, de lehet érdemes megvárni a #406-ot, akkor változik megint

**Comment by vmiklos** [comment]
676ede7b4bf1d3d5f559e9fe1559ab5bfe4acb61

Nem kerül semmibe :)
