### ISSUE TITLE
Nébih címek átemelése referenciába

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#406]
https://portal.nebih.gov.hu/termelo-kereso

**Comment by vasony** [comment]
curl "https://portal.nebih.gov.hu/termelo-kereso" egyben letölti, nincs rajta így lapozó

**Comment by vasony** [comment]
még nem került kiadásra

**Comment by vasony** [comment]
@vmiklos frissítsd a refet légy szíves, aztán ezt zárd le.

**Comment by vasony** [comment]
ezzel a duplázással akarunk valamit kezdeni, vagy maradjon
letters: off
Kálvária utca	[..., **12, 12/A***, ...]

**Comment by vmiklos** [comment]
> ezzel a duplázással akarunk valamit kezdeni, vagy maradjon
> letters: off
> Kálvária utca [..., **12, 12/A***, ...]

Én nem foglalkoznék vele, térjünk rá vissza mikor 80%-nál állunk országos szinten :)

**Comment by vasony** [comment]
akkor marad a ref frissítés és close :)

**Comment by vmiklos** [comment]
3701a9181d76ca5f257919d8b38976de988bda29
