### ISSUE TITLE
hiányzó házszámok kimenet nem determinisztikus vagy megváltozott a logika

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#4088]
Ha nincs bekapcsolva a housnumbers-letters, akkor a hiányzókból csak 1 számot dob fel, ez eddig a listából az első volt, most az utolsót dobja fel.

Minta terület, pl baja. text kimeneten nézem, de a html is ezt mutatja:

20240807:
Rudnay utca	[1, 3, 5, 7, 9, 11, 13, 15, **17**, 19, 21, 23, 25], [2, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
20240809:
Rudnay utca	[1, 3, 5, 7, 9, 11, 13, 15, **17d**, 19, 21, 23, 25], [2, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

ref:
Rudnay Gyula utca	17	
Rudnay Gyula utca	17/B	
Rudnay Gyula utca	17/D	

A teljes diff ebből képezhető:
[baja-20240807.txt](https://github.com/user-attachments/files/16559232/baja-20240807.txt)
[baja-20240809.txt](https://github.com/user-attachments/files/16559233/baja-20240809.txt)

**Comment by vmiklos** [comment]
Lehet tesztelni:
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/baja/view-result.txt

Helyi teszteléshez: `sqlite3 workdir/state.db`, majd:

```sql
delete from missing_housenumbers_cache where relation = 'baja';
delete from mtimes where page = 'missing-housenumbers-cache/baja';
```

Utána már jó kell legyen a txt kimenet, mert nem a cache-ből veszi az eredményt.

**Comment by vasony** [comment]
így jobb
