### ISSUE TITLE
Rendezési probléma a hiányzó házszámok oldalon

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#414]
Ez egy nagyon alacsony szintű hiba, de azért leírom. A [hiányzó budafoki házszámok](https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budafok/view-result) oldalon az utcák elvileg aszerint vannak rendezve, hogy hány házszám hiányzik. Jelenleg a Dévény utca van az első helyen 57 hiányzó házszámmal, ezt követi a Pannónia utca 63-mal. Ez így nem jó, a Pannónia utcának kellene első helyen lennie.

A Dévény utcában van több tartományként megadott házszám is (például 17-23) és olyanok is, amelyek meglévőket fednek le (például 42, 42-44, 44). Talán valahol errefelé lesz a probléma a darabszám és a sorrend megállapításához.

**Comment by vmiklos** [comment]
Én arra tippelnék, hogy az okozza az anomáliát, hogy mikor rendezünk akkor a 2-4-6 még 3 házszám, de aztán ez van, hogy összevonódik 1db 2-6-ra, ha a referenciában is így, tartományként volt. De amúgy jogos, már én is észrevettem máshol. :-)

**Comment by vmiklos** [comment]
Most már a 63 van az elején.
