### ISSUE TITLE
referencia előállításnál házszám szűrés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#42]
**Referencia generálás**nál szűrni kellene a helyrajzi számokat és a 0 házszámot, mert a legtöbb filterezést ez generálja. Általánosságban a házszám 1 ... 999 közé kell, hogy essen, ha ettől el akarunk térni, akkor meg lehet adni.

Az implementálás az lenne, hogy a a relation.yaml-ban alkalmazunk egy ranges: relation szintű filtert, ami default 1..999 lesz, ha nincs megadva. 
Ez lehetővé tenné a tanyáknál a 999-nél nagyobb számok megadásának lehetőségét is, ha később szükséges.

pl.

biatorbagy:
    osmrelation: 113461
    refmegye: "14"
    reftelepules: "011"
    ranges: {start: '1', end: '199'} # páros-páratlan szűrés nincs

default érték, ha nincs megadva
    ranges: {start: '1', end: '999'}

ez az alábbiakat szűrné ki Biatorbágyon pl:
Móricz Zsigmond	0
Vasút	0 1  # szerintem ebből sem kell Vasút utca 1-et generálni
Ritsman Pál	0 A # na ez eltérő írásmódú, egyből nincs is benne
..
Kossuth Lajos	240
Ferenc	296
Gábor Áron	377
Kálvária	392/37
Határ	553/2
Deák Ferenc	1186/55

számításom szerint a 4133-ról 3726-re megy le a referencia egy ilyen szűrővel Biatorbágynál.
itt kicsit mások lesznek a számok, mert az én számításom nem tudja a 5-7 típust kezelni most hirtelen, és az eltérő írásmód miatt nem maradnak ki utcák.

**Comment by vmiklos** [comment]
Mielőtt túlbonyolítom a dolgot: van most olyan reláció ahol 999-nél van nagyobb érvényes házszám? Gondolom nincs.

Szerintem első körben egyszerűen szűrjünk ki mindent ami nem 1-999 közé esik, és majd ha lesz, akkor csinálok rá lehetőséget, hogy adott relációnál más legyen a limit.

**Comment by vasony** [comment]
ok, legyen így.

**Comment by vmiklos** [comment]
Biatorbágyot néztem, ha a Forrás utca explicit filterét kiveszem akkor így változik a fenti hatására:

Régi:

````
Forrás utca   22
['5', '7', '11', '13', '14', '15', '17', '18', '20', '25', '30', '3407', '3414', '3423', '3426', '3451', '3457', '3462', '3463', '8909', '8919', '9006']
````

Új:

````
Forrás utca     11
['5', '7', '11', '13', '14', '15', '17', '18', '20', '25', '30']
````
