### ISSUE TITLE
Frissítés gomb átértelmezése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#426]
A listáról

>Miklós, kicsit félrevezető, hogy a hiányzó házszámok nézetben csak a Frissítés referenciából gomb van ott, és át kell menni a meglévő házszámok nézetre az Overpass frissítéshez.

Szerintem elég lenne 1 frissítés gomb, ami meghívja a 2 funkciót egymás után:
http://osm.vasony.hu/street-housenumbers/albertfalva/update-result
http://osm.vasony.hu/missing-housenumbers/albertfalva/update-result

**Comment by vmiklos** [comment]
Ha van utca meg házszám keresés is, akkor 4 frissíthető forrásunk van relációnként: osmből utca, osmből házszám, refből utca, refből házszám. Ha jól értem a listán emlegetett szándék az osmből a házszám listát frissíteni, de a UX fail miatt refből lesz a házszám frissítés. Ez alapján a fenti nem fogja megoldani a problémát. :)

Viszont ha a Frissítés referenciából mellé kerül egy Frissítés OSM-ből gomb is (sőt, talán azt elsőnek, hiszen tipikusan az változik), akkor remélhetőleg megfelel a célnak.

**Comment by vasony** [comment]
igen, utóbbi jó lesz

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
A frissítés ok.

Szerintem a "másodpercekig tarthat" szöveg nem kell, nálam már nem fér ki egy sorba, esetleg a doksiban meg lehet említeni, de szerintem az első kattintás után mindenki rájön.

A másik ami már kevésbé fontos, hogy előrébb vinném a frissítés blokkokat egyből a hiányzó után.
``Hiányzó házszámok (txt, chkl) ¦ Frissítés OSM-ből ¦ Frissítés referenciából | Meglévő házszámok``

**Comment by vmiklos** [comment]
Ezek megoldhatók.

**Comment by vmiklos** [comment]
Második teszt :)

**Comment by vasony** [comment]
Jó lesz
