### ISSUE TITLE
hiányzó és eltérő írásmódú utcák felderítése új funkció

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#43]
A hiányzó házszámhoz hasonlóan hiányzó utcákat kellene megtalálni 2 új funkció fejlesztésével.

a) **eltérő írásmódú utcák felderítése** 
- a referencia lenne a kiindulópont hanem az OSM, mert fordítva nem tudunk szűrni. 
- működése:  A streets már előállt overpass alapján, az ebben lévő utcákon megyünk sorra, és megkeressük a referenciában, ha hiányzik, akkor listázzuk

b) **hiányzó utcák felderítése**
- vidéken, ahol egy településkód 1 relation, ott a referencia lenne a kiindulópont
- működése: a referenciában lévő összes utcán végigmegyünk, és megnézzük, hogy szerepel-e a streets.txt-ben. paraméterben engedélyezzük a relations.yaml fileban.
- tudunk generálni kerületi szintű relation-höz is ilyet, akkor Budapestre is tud működni

referencia: generálok utcaszintet, mert van olyan utca ahol nincs házszám és az most nem került be

Ezek azért fontosak, mert az eltérő írásmódú utcák miatt nem derül fény arra, ha egy utca teljesen kimaradt a házszámozásból, amíg nem mappeljük be az eltérő írásmódjukat.
pl. Biatorbágy Ritsman Pál

**Comment by vmiklos** [comment]
Hmm, gondolkodtam egy kicsit ezen én is, de még nem tudom hogy lenne jó ezt csinálni. Két ellentmondó irány van:

Egyfelől jó lenne a relációkat reftelepules nagyságúra növelni, mivel akkor tudunk hiányzó utcát mutatni.

Másfelől viszont jó ez, hogy városrészeket is tudunk kezelni, mivel sűrűn lakott területen így lehet megoldani, hogy 1-1 reláció csak 1-2e házszámot tartalmazzon és ne többet (ha félmilliót tartalmaz, abba senki se kezd bele).

Lehetne ezt azzal megoldani, hogy ez a hiányzó utca keresés dolog ez egy külön aloldal lenne, ahol direkt nincs szó házszámokról, így nem gond "bp xi. kerület" méretű relációval dolgozni. Csak akkor az meg azért béna, mert milyen jó lenne továbbra is egyetlen reláció-lista. De talán még ez a legjobb.

A validálás másik irányban egy teljesen külön téma, az (ahogy írod) egyszerűbb, viszont nem is annyira izgalmas. :-)

**Comment by vasony** [comment]
Szerintem tudjuk egy relációban kezelni a kétféle funkciót. Sőt a kétféle szintet is, attól még nem kell megszüntetni a városrész szintű relációkat, csak meg kell őket jelölni, hogy azokra nincs értelmezve az új funkció.

Szerintem nem gond, ha valaki kerület szinten akarja a hiányzó házszámokat megnézni, ekkor nem kell külön főoldal neki.
De ha akarunk külön oldalt, úgy is tud menni, lejjebb a minta:


pl:
szentimrevaros:
&nbsp;&nbsp;&nbsp;&nbsp;osmrelation: 2702616`
&nbsp;&nbsp;&nbsp;&nbsp;refmegye: "01"
&nbsp;&nbsp;&nbsp;&nbsp;reftelepules: "011"
&nbsp;&nbsp;&nbsp;&nbsp;**page: "houseno"**  # marad a meglévő funkcionalitás
budapest_11:
&nbsp;&nbsp;&nbsp;&nbsp;osmrelation: 221998
&nbsp;&nbsp;&nbsp;&nbsp;refmegye: "01"
&nbsp;&nbsp;&nbsp;&nbsp;reftelepules: "011"
&nbsp;&nbsp;&nbsp;&nbsp;**page: "street"** # külön szekcióban, csak "meglévő utcák" link lenne, a % ha lesz a hiányzó utcákhoz vezet
biatorbagy:
&nbsp;&nbsp;&nbsp;&nbsp;osmrelation: 113461
&nbsp;&nbsp;&nbsp;&nbsp;refmegye: "14"
&nbsp;&nbsp;&nbsp;&nbsp;reftelepules: "011"
&nbsp;&nbsp;&nbsp;&nbsp;_page: "all"_   # nem szükséges megadni, ez a default

a page: "street" típusúakat mindeképp külön szekcióban jeleníteném meg, akár a mostani lista alatt, mert ott mások a linkek. 
A vidéki városok, ahol mindkét funkció van, azt ki kell találni hogy fér el, mert 2 db % már hülyén néz ki.

egy lehetséges megoldás:

barossgabortelep | 13.68% kész | meglévő házszámok | meglévő utcák | terület határa
biatorbagy | 2.06% kész | meglévő házszámok | meglévő utcák | **hiányzó utcák (99% kész)** | terület határa
csepel-belvaros | 9.93% kész | meglévő házszámok | meglévő utcák | terület határa
...
terezvaros | 72.28% kész | meglévő házszámok | meglévő utcák | terület határa
<hr>
blablabla<br>
budapest-11 | 99% kész | meglévő utcák | terület határa

**Comment by vmiklos** [comment]
OK, ez tetszik, hogy a reláció kapjon egy flaget ami defaultol a mostani viselkedésre ("no"), de lehessen hiányzó utcákat is keresni pl Biatorbágyon ("yes") vagy csak azt pl egy új Újbuda relációban ("only").

**Comment by vmiklos** [comment]
Ilyen lett: https://vmiklos.pythonanywhere.com/osm/suspicious-relations/ujbuda/view-result

Biztos vagyok benne, hogy majd még találunk benne csiszolgatni valót, de alapvetően működik.

**Comment by vasony** [comment]
szuper, én most 3 dolgot látok még ezzel, felveszem külön őket majd ha kell 

1) az utca mappelés megoldás, hogy visszafele is menjen most ugye a refstreets a másik irány tartalmazza
pl: Október Huszonharmad utca > Október huszonharmadika utca
Jó lenne ha nem kellene 2x, de lehet muszáj lesz, mert lehet, hogy több ref is ugyanarra az osm írásmódra mutat. 

2) kiszűrés, most nincs példa, de kiderül, hogy nincs a valóságban az utca.
lehet az előzővel is megoldható
pl: Kukutyin utca:null vagy -

3) ez az egyszerűbb, a parkot is hozzá kell venni az overpass street listához, a Csonka János tér nem jön fel.

**Comment by vasony** [comment]
Máris kijött egy házszám hiány, ennek kapcsán, amit nem vettem észre
Október huszonharmadika utca | 12 | 1, 3, 9, 11, 13, 14, 17, 21, 23, 29, 31, 33
osm-ben meg kétféleképp volt.

**Comment by vmiklos** [comment]
> ez az egyszerűbb, a parkot is hozzá kell venni az overpass street listához, a Csonka János tér nem jön fel.

Ehhez a data/streets-template.txt-t kéne bővíteni, hogy a leisure=parkot is belevegye ha van neki neve. Ezt elvileg külön is le tudod magadnak tesztelni overpass-turbóval. Megnézed?

**Comment by vasony** [comment]
Megnézem.
