### ISSUE TITLE
refstreets egy részének megjelenítése hiányzó házszámokban

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#436]
Főleg vidéken lesz érdekes, hogy valahogy megjelöljük, hogy az utca hivatalos neve eltér az osm-től. Úgy tűnik nem esik le, hogy először az utcaneveket kell rendbetenni, csak utána a házszámokat. A mappelést én elvégezném, ahol tudom, akkor viszont az infó elvész az enduser felé.
Azért nem az összes refstreets utca, mert van ahol egyértelműen helyesírási hiba van a refben, azokat nem írnám ki, mert csak zavaró.

filter: (refstreets formátum, annak egy részhalmaza)
vagy külön, vagy a filter részen is mehet (v1 vagy v2)

minták Budapest 04

```
altnames:
  # 'OSM Name 1': 'Ref Name 1'
  'Farkaserdő utca': 'Farkas-erdő utca'  # utcatábla = OSM
  'Kossuth Lajos utca': 'Kossuth utca'  # utcatábla = OSM
  'Kölcsey Ferenc utca': 'Kölcsey utca'  # utcatábla = OSM
  'Körösbánya utca': 'Kőrösbánya utca'   # falu röviddel van, helyesírási probléma
  'Ódry Árpád utca': 'Ódry utca'  # utcatábla = OSM
  'Venetiáner utca': 'Venetianer utca'  # utcatábla = OSM
```

v2
```
filters:
  Ódry Árpád utca:
    altname: 'Ódry utca'  # egyelőre csak 1
    ranges:
      - {start: '1', end: '99'}
      - {start: '2', end: '98'}
    
```

v3 - talán ez a legegyszerűbb, ekkor nem kell duplán leírni, a refstreetsben már megvan mi az altname
```
filters:
  Ódry Árpád utca:
    show-altname: 'yes'
  vagy
  show-official-name: 'yes'
vagy show nélkül is
```

Megjelenítőben: csak html kimeneten
```
<td>Ódry Árpád utca
<br>
(Ódry utca)
</td><td>10</td><td>3, 9, 11, 13, 15<br>4, 10, 12, 14, 16</td>
```

**Comment by vmiklos** [comment]
Az ötlet tetszik, de feleslegesnek tűnik a yaml file-okba explicit markup. Annyi nem elég, hogy:

- van egy refstreets már most is, van benne ilyen pl, hogy:

https://github.com/vmiklos/osm-gimmisn/blob/038bbe8fbdd758173412937a98c3d5be03ca28b0/data/relation-sashegy.yaml#L97-L100

- mikor kiírom, hogy 'OSM Name 1', alá mindig mehet a 'Ref Name 1'?

Ez igazából a fentiből a v3, de alapból be lenne kapcsolva. Tudsz olyan helyzetről ahol van értelme ezt kikapcsolni?

**Comment by vasony** [comment]
Ld:
`Azért nem az összes refstreets utca, mert van ahol egyértelműen helyesírási hiba van a refben, azokat nem írnám ki, mert csak zavaró.`

Ezért írtam, hogy ki/be kell tudni kapcsolni, de lehet bekapcsolva default, mert talán kevesebb a rossz: pl:

```
  'Károly Iréneusz József utca': 'Károly Ireneusz J. utca'   # rövidítés, nem kell
  'Keserűvíz utca': 'Keserűviz utca'  # helyesítási hiba
  'Október huszonharmadika utca': 'Október Huszonharmad utca'  # ez f*szság
```

**Comment by vmiklos** [comment]
Ja látom.

**Comment by vmiklos** [comment]
Máshol `refstreet` néven hivatkozunk a "másik" névre, szóval talán `show-refstreet: true` jobb.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
Szépen megjelenik, a kikapcsolást még kipróbálom.

**Comment by vasony** [comment]
@vmiklos Valamit nem jól adok meg, vagy nem működik.

budapest_03
```
  Kaszásdűlő utca:
    show-refstreet: false
```
```
Kaszásdűlő utca(Kaszásdülő utca) | 10 | 19, 41/B, 594, 6, 10, 14, 22, 30, 38
```

**Comment by vasony** [comment]
én bénáztam el, nem merge-elődött be a PR, most jó, zárom.

**Comment by vasony** [comment]
#453
