### ISSUE TITLE
txt kimeneten elment a magyar sort order

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#437]
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/alsorakos/view-result.txt

Az ékezetek a végére kerültek, nem tudom, hogy csak a te instanciádon-e vagy nálam is, az majd akkor derül ki ha feléledt a gép.

```
Csokor utca	[3, 5, 7, 9], [2, 4, 6, 8, 10]
Csáktornya park	[1*, 9], [4, 6]
```
04.30-án még így volt:
```
Czobor utca	[1, 3, 5, 13, 15, 17/B, 19, 21, 23, 25, 29, 31, 33/A, 35/B, 37/A, 39/A, 41/A, 43, 45/A...
Csáktornya park	[1*, 9], [4, 6]
```

**Comment by vasony** [comment]
úgy  tűnik csak az osm-gimmisn.vmiklos-hu érintett, az osm.vasony.hu jó.
(btw a cron sem futott le 1-jén)

**Comment by vmiklos** [comment]
Volt egy Fedora 31->32 upgrade a gépen, ami hozott új pythont is, lehet valami tönkrement, majd megnézem. A cron ma lefutott hibák nélkül ha jól látom.

**Comment by vasony** [comment]
cron: úgy értem az összes területre ami elsején fut: pl. Szentantalfa:  "Utolsó frissítés: 2020-04-24 04:44"

**Comment by vmiklos** [comment]
Ah, látom mindkettőt.

Sort order: nálam helyben is jó, megnézem mi okozza a dolgot.

Cron: a config opció, hogy legyen-e inaktívra is futtatva True/False lehet csak, kéne még egy harmadik Monthly érték is. Sajnos már nem emlékszem, hogy miért tűnt jó ötletnek, hogy a havi verziót kidobtam a 7d57ce075933a6ca56157067e928d140733ba6d2 commitban, mindenesetre majd vissza fogom rakni.

**Comment by vmiklos** [comment]
Sort order javítva, csak a glibc locale nem volt feltéve, szóval az osm-gimmisn.v.h-n, szerintem sose volt jó. Azért maradjon ez az issue nyitva, install doksi jó ha írja ezt explicite.

**Comment by vmiklos** [comment]
Sorrendet lehet tesztelni. :)

**Comment by vasony** [comment]
a sorrend most jó

**Comment by vasony** [comment]
>Cron: a config opció, hogy legyen-e inaktívra is futtatva True/False lehet csak, kéne még egy harmadik Monthly érték is. 

ez külön issue, akkor

**Comment by vmiklos** [comment]
Köszi, és akkor ez meg zárható gondolom.
