### ISSUE TITLE
cron monthly visszaállítás

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#441]
#437 
>Cron: a config opció, hogy legyen-e inaktívra is futtatva True/False lehet csak, kéne még egy harmadik Monthly érték is. 

Vagy kell egy Mothly, vagy command line-ból felül kell tudni írni a False értéket, mert most sosem frissülnek a területek maguktól ezeknél.
Utóbbival egyedi ütemezést lehet csinálni, de legyen az amelyiket egyszerűbb megcsinálni, révén most csak nálad fut `false` üzemmódban.

**Comment by vmiklos** [comment]
Futtatok egyet kézzel, csak hogy ne kelljen jún 1-ig várni.

**Comment by vmiklos** [comment]
Azt hiszem ez kész

**Comment by vasony** [comment]
Akkor zárjuk, most nem fogjuk elsejéig nyitva hagyni :-)
