### ISSUE TITLE
Duplikált házszám a listában

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#472]
Budafok, Vihar utca: 3, 5, 7, 7 , 23
A 7-es szám kétszer szerepel a listában, a második után van egy szóköz. Itt valami trimmelési probléma lehet?

**Comment by vmiklos** [comment]
Igen: https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budafok/view-query

A "7 *" tipikusan "7*" szokott lenni.

@vasony van rá preferenciád, hogy ezt hol javítsuk? Csinálsz új referenciát, vagy a kódban stripeljek miután levettem a * véget?

**Comment by vasony** [comment]
Ez a sima referenciából jön, nem a govcenterből, és a csillag miatt meghülyül.
A referenciát javítom, ez az egy sor érintett.

**Comment by vasony** [comment]
Valamit benéztme, van még ilyen, olyan is van hogy 96/*

**Comment by vasony** [comment]
@vmiklos felraktam az új refet. nálam már jó.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/4aad01fa5dfedcde3d31115db46e92d8706e8d47 beraktam, köszi.
