### ISSUE TITLE
2 db Kossuth Lajos utca megkülönböztetése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#473]
Van valami ötlet, hogy lehetne megkülönböztetni? 
Azon kívül, hogy szétvágom irányítószámra:

1) osm: Kossuth Lajos utca, ref: Kossuth Lajos (2500 Esztergom)
https://www.openstreetmap.org/way/35550227

2) osm: Kossuth Lajos utca, ref: Kossuth Lajos P utca (2508 Esztergom-Pilisszentlélek)
https://www.openstreetmap.org/way/103025751

**Comment by vmiklos** [comment]
Jó kérdés. A referenciában csak Esztergom van, nem? Illetve osm-ben sincs "Esztergom-Pilisszentélek" nevű település, ami viszont a vágás ellen szól.

**Comment by vasony** [comment]
Igen csak Esztergom van, csak az utcanévől látszik, és csak annak aki tudja, hogy a  P = Pilisszentlélek.

Nincs, viszont ez "saját irányítószámmal rendelkező településrész", most ezzel a házszámok pipa, ha elvágom. Csak a hiányzó utcákat nem lehet kihozni, illetve egyben nem lehet majd látni.

Máshol is van ilyen ahol összecsatoltak településeket és duplázódnak az utcák, vagy az utca elé/mögé írnak valamit, vagy külön irányítószáma van.

Egyébként a referenciát át tudnám alakítani, hogy legyen külön település kódja, nem kell tartanunk magunkat az eredeti közigazgatási beosztáshoz, akkor teljesen elkülönülne.

**Comment by vmiklos** [comment]
Elég lehetetlen probléma :) De igen, ha ezt lehet referencia szintjén kezelni, örülök neki

**Comment by vasony** [comment]
ezt elengedtem
