### ISSUE TITLE
stat városonként, utolsó havi diff

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#489]
Fel kellene grouppolni a házszámos text filet (workdir/stat/2020-06-01.csv) az első 2 oszlop szerint, valahogy így, hogy budapestnél legyen kerület szintű bontás: (most a python szintaxis nem fog menni de kb látod), és elmenteni.
```
if(addr:postcode like '1%') then addr:city + '_' + substr(addr:postcode,2,2)
elsif (!addr:city) then `<empty>` 
else addr:city
```

Aztán az utolsó teljes hónapot megjeleníteni, vagy elsejétől, vagy csúszó ablak 30 nap, még el kell dönteni.
2020-06-01 még megvan a 05-01 már nincs. 

```
budapest_15 | 1463
esztergom | 1434
budapest_11 | 411
budapest_03 | 304
budaors | 298
budapest_04 | 223
budapest_12| 132
```

**Comment by vmiklos** [comment]
Ez megoldható. Elkezdhetjük gyűjteni pl egy <dátum>.citycount file-ba, aztán ha már van elég adat, hogy érdekes legyen, mehet ki a stats.jsonba meg hozzá diagram.

> Aztán az utolsó teljes hónapot megjeleníteni, vagy elsejétől, vagy csúszó ablak 30 nap, még el kell dönteni.

Csúszó ablak az egyszerűbb, azt használjuk már több másik esetben is.

További eldöntendő dolgok: mit akarunk ábrázolni, városonként a házszámok számát? Ezt könnyű, de annyira nem érdekes szerintem. Sokkal érdekesebb lenne, hogy a referencia hány százalékánál tartunk, de a referencia az egyelőre csak egyetlen szám, esetleg tudsz csinálni városonkénti bontást a referenciához? (Fenti formátum teljesen jó.)

Még egy kérdés, hogy majd hogy legyen ábrázolva: lehet talán erre nem is diagram kéne, hanem egy sima 2 oszlopos táblázat (városnév, százalék), amit lehet jsből rendezni. Vélemény?

**Comment by vasony** [comment]
A városonkénti diff azért érdekes, hogy melyik területen aktív a házszámozás, mindegy hány százalék a referenciának, mert 100 házszám felvitele ugyanannyira melós mucsalyröcsögén mint a 17. kerületben. Ez mehet oszlopdiagramként.

Amit te írsz az egy táblázat, és külön kellene szedni tényleg, ehhez meg tudom csinálni a countot városonként, csak akkor a filtereket is be kell építenem, addig csak sima count, 
Külön issue.

**Comment by vmiklos** [comment]
Oké, tehát az ábrázolás a https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/#_dailytotal szerű lenne, csak városonkénti bontva és mondjuk utolsó hónap, nem 2 hét?

Ha igen, azt még ki kéne találni, hogy hogy oldjuk meg, hogy ne legyen borzasztóan sok diagram, minden városra egy a /osm/housenumber-stats/hungary/ oldalon alapból az kicsit túlzás. Esetleg egy lenyíló lista, abból választ a user és gombnyomás után azt az egyet mutatjuk?

**Comment by vmiklos** [comment]
> Elkezdhetjük gyűjteni pl egy <dátum>.citycount file-ba

Ez a rész a fentivel meg is volna.

**Comment by vasony** [comment]
nem így gondoltam, hanem mint a topusers-nél, csak nem végtelen időre.
az x tengely a városok, y tengely hány db házszám került fel az adott hónapban.
2 db citycountot kivonod.
bal oldalt a legaktívabb város, jobbra csökkenőben top x

http://www.vasony.hu/osm/citystat.png

**Comment by vmiklos** [comment]
Hm, adott hónap helyett érdekesebb lenne csúszó ablakkal dolgozni és mondjuk utolsó 30 napot venni, nem?

**Comment by vasony** [comment]
lehet csúszó ablak 30 nap.

**Comment by vmiklos** [comment]
A JS rész még hiányzik.

**Comment by vmiklos** [comment]
A teszteknel a today() mockolas lemaradt pár helyen, de szerencsére a CI elkapta.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
A stat jó.
1 kérdés van: ha már vannak ékezetek, nem kellene nagy betűvel írni a város neveket?

**Comment by vmiklos** [comment]
Ez kicsit szerencsétlen, explicite lett kisbetűsítve, és most ez a kulcs, így ha kiveszem a kisbetűsítést, megint 30 napig nem lesz adat. Vagy maradjon így, vagy esetleg nagybetűsítem az első karaktert. Van olyan település név ahol eredetileg más karakter is nagybetű, mint az első? Az OSM névre gondolok, nem a táblán kiírt Siófok-Sóstó névre.

A .citycount file-ok formátumához ennyi miatt nem nyúlnék hozzá.

**Comment by vasony** [comment]
ok, akkor maradjon annyira nem létkérdés
