### ISSUE TITLE
stat városonként hol tart a készültség

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#490]
#489 2. fele

Egy táblázat ami rendezhető, mutatja, hogy hogy áll a házszámozás a referenciához képest.
Teendők
1) data: referencia count városonként, első körben filterek nélkül
2) python: beépíteni
3) data: referencia count fiterek figyelembe vétele és levonása a referenciából

további nehézségek eldönteni, hogy mit számolunk 1 db házszámnak: housenumber-letters yes vagy no
teszt terület bp12.
pl: 15, 15/a 15/a/2, 15/anyam

@vmiklos addig álíltsd át légy szíves, hogy hagyja meg a csv-ket a workdirben, amíg eldöntjük mit is akarunk.

**Comment by vmiklos** [comment]
A .citycount tartalmazza napi szinten a nyers varosonkenti OSM hazszamokat, az nem elég?

**Comment by vasony** [comment]
Elég a tört (százalék) számlálójához, a nevezőt nekem kell megcsinálni a referenciából. küldöm kisbetűsítve, akkor csak össze kell joinolni és elosztani a számokat.
A 3. pont meg majd később.

**Comment by vasony** [comment]
varosok_count_20200717.tsv a referencia könyvtárban
kicsit szarakodtam az > 500 házszámokkal (Bécsi út, Üllői és társai), így a szumma is nőtt  ebből kellene felszummázni a továbbiakban a ref.count fájlba hogy konzisztens legyen, ennyinek kell kijönnie: 3263711
ha a filterezést majd belerakom, ez fog majd frissülni. úgy kellene kezelni mit a többi referencia fájlt

**Comment by vmiklos** [comment]
Oké, akkor ez innentől már nem adat feladat.

**Comment by vasony** [comment]
a hármas pontot felveszem külön, mert majd egyszer

**Comment by vmiklos** [comment]
Ilyen lett:

https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/cityprogress

Lehet tesztelni. A 100% feletti lefedettséget maxoltam 100%-ban, hogy ne nézzen ki bután. Az alján van egy disclaimer, hogy világos legyen: ebben nincsenek filterek. Saját instance-en a wsgi.inibe vedd fel az új kulcsot, a sablont frissítettem.

**Comment by vasony** [comment]
Lehetne kérni azt a 2 oszlopot a táblázatba, ami alapján a % képződik, még maxolás előtt? Lehet valami hidden paraméter is.
Akarom debuggolni a 100+%-osakat, és van 1-2 gyanús.

**Comment by vmiklos** [comment]
Persze.

**Comment by vasony** [comment]
minta a ref.count nem frissült volna

**Comment by vmiklos** [comment]
Magától nem frissül. :) Hogy legyen számolva, egy sum() a 2. oszlopra elég?

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/cityprogress lehet tesztelni.

**Comment by vasony** [comment]
Teszt budapest_07, 

Három dolog derült ki
**Kellene egy unique szűrés**, ezzel egyel közelebb kerülünk a valóshoz a sok dupla házszám miatt. (python)
**ref count-ból** lemaradt a govcenter (db)
**osm-ben többlet** van #546-ban kezelendő

osm count: 2099
unique count: 1604
ref count: 1490

#546-hoz:
De sosem fog egyezni, a megoldás az lesz, hogy ref count-ba belveszem a csak osm-ben szereplő számokat is, akkor nem lehet több mint 100%.
De mivel itt nem végzünk felbontást, az egyik oldal: 16,18 másik oldal: 16-18-at  kérdéskörre nincs megoldásom.
Hacsak nem konvertálom át a ref-et osm formára a count kedvéért, szép munka lesz.

pl: osm

```
Dohány utca	12
Dohány utca	14
Dohány utca	16
Dohány utca	16-18
```
REF

```
Dohány utca  10
Dohány utca  16-18
```

**Comment by vasony** [comment]
TL;DR
Kellene egy unique szűrés a countokba, a db részt megcsináltam frissítsd be a refet.

**Comment by vmiklos** [comment]
Az osm-es .citycount file-okban szereplő számokra gondolsz, ugye?

**Comment by vasony** [comment]
Igen, azokra.

**Comment by vmiklos** [comment]
Ez mondjuk az utolsó havi diffet el fogja torzítani, de ez 30 nap alatt megoldódik, kisebb probléma, mint hogy eddig nem voltak szűrve a duplikátumok.

**Comment by vmiklos** [comment]
b391b89f40725abe548f3bd633f2d277cfacec87

Lehet tesztelni.

**Comment by vasony** [comment]
Nem írtad át a configot:
FileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/refdir/varosok_count_20200717.tsv'

**Comment by vasony** [comment]
Nálam automata a config:
`
HAZSZAMOK=$(basename $(ls -1 $BASEDIR/refdir/hazszamok_20*.tsv | sort -rn | head -1))
HAZSZAMOK_KIEG=$(basename $(ls -1 $BASEDIR/refdir/hazszamok_kieg_20*.tsv | sort -rn | head -1))
UTCAK=$(basename $(ls -1 $BASEDIR/refdir/utcak_20*.tsv | sort -rn | head -1))
CITYCNT=$(basename $(ls -1 $BASEDIR/refdir/varosok_count_20*.tsv | sort -rn | head -1))
`

**Comment by vmiklos** [comment]
Átírtam. Nem kéne késő este ilyeneket csinálni. :)

A másikat frissítem ha az is meglesz.

**Comment by vasony** [comment]
Nem jók a számok, budapest_07-ben 246 jött ki, 1604 helyett.

**Comment by vmiklos** [comment]
Ja, most jöttem rá u.erre én is. ;)

**Comment by vasony** [comment]
2:4 ? a user nem kell, akkor nem lesz jó.

**Comment by vmiklos** [comment]
Általában igyekszem nem vakon javítani dolgokat, most is kipróbáltam. :)

````
>>> cells = ["1078", "Budapest", "Nefelejcs utca", "9"]
>>> "\t".join(cells[2:4])
'Nefelejcs utca\t9'
````

**Comment by vasony** [comment]
Leszögezem, hogy nem értek hozzá, csak okoskodom :)

Nekem csak fura a szintaxis. a 2:4 azt jelenti hogy a 2-es és 3-as elem?
A commentben ott volt a user is, itt me a tömbödben nincs.
Holnap ránézek ha frissült.

**Comment by vasony** [comment]
Na pipa

**Comment by vmiklos** [comment]
> Nekem csak fura a szintaxis. a 2:4 azt jelenti hogy a 2-es és 3-as elem?

Igen:

https://stackoverflow.com/questions/509211/understanding-slice-notation
