### ISSUE TITLE
Meglévő házszámok darabszám

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#498]
Valami furcsaság van, amit nem értek a "meglévő: xxx" számolásánál

Szigetmonostor:
**tegnapi adatok szerint:**
már a 2 szerveren is eltért, eközben a lementett meglévő házszám lista egyezik:
2020-06-14 09:17 ... nem tartalmazza ... 725 házszámot. (**meglévő: 586**, készültség: 44.70%)
2020-06-13 03:45 ... nem tartalmazza ... 725 házszámot. (**meglévő: 615**, készültség: 45.90%)

**ma  hozzáadtam a refstreets** részt, és csökkent a meglévő házszámok száma, ami nem érthető számomra, mert nem szabadna csökkennie ha újabb utcákat adok hozzá.

2020-06-14 09:36	OpenStreetMap nem tartalmazza a lenti 102 utcához tartozó 861 házszámot. (**meglévő: 601,** készültség: 41.11%)

a nagyobb gond, hogy a meglévő házszámok részből kipulva a /a /b-ket és 800 körüli egyedi házszám van, nem 600 körüli. lenne 200 házszám ami nincs benne a ref-ben?
ki lehet dumpolni valahogy mi az a 601 házszám amit ő meglévőnek vesz?

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/szigetmonostor/view-result hmm, én még mindig az 586-ot látom itt, nem a 601-et. Amúgy ez a szám abból jön, hogy a referencia adatot két részre osztjuk: a "done" és a "missing" részekre. Tehát ez csak azt számolja, ami a referenciában is van. Ha X utca 42 nincs a referenciában, de OSM-en van, az ebbe nem kerül bele. Ez így érthető vagy nézzek utána jobban?

**Comment by vasony** [comment]
ez alapján rájöttem, hogy ilyen ellenőrzést tudok írni az adatbázisban, hogy mennyi az olyan osm házszám ami nincs a refben, és 207 db jött ki, akkor kilóra megvan a különbség.
ennyire jó a ref :-O

Szentantalfán csak 9 db :)
