### ISSUE TITLE
GUI fejléc / lábléc ráncfelvarrás

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#50]
Az alábbi dolgok növelnék a használhatóságot, és könnyebb lenne áttekinteni a fejlődést.

1. Most a 3 oldalon 3 különböző feljéc van, javaslolt lenne egységesen kezelni

Jelenlegi állapot
**street-housenumbers**
Területek listája ¦ Frissítve 2019-05-12T14:43:23.930521¦ Meglévő házszámok ¦ Frissítés Overpass hívásával (másodpercekig tarthat) ¦ Lekérdezés megtekintése ¦ github
**streets**
Területek listája ¦ Frissítve 2019-05-05T17:13:32¦ Meglévő utcák ¦ Frissítés Overpass hívásával (másodpercekig tarthat) ¦ Lekérdezés megtekintése ¦ github
**suspicious**
Területek listája ¦ Meglévő házszámok a környéken ¦ Meglévő utcák a környéken ¦ Frissítés referenciából (másodpercekig tarthat) ¦ terület határa ¦ github

- A frissítési dátumot kiszedni a menüből ahol nincs.
- suspicious: Az egész lábléc előtti blokkot (% és dátum) a fejléc második sorába tenném, a tetején lászana egy gyors összefoglaló, x db házszám hiányzik, ekkor frissült
-  streets/house numbers link a suspicious oldalra, plusz egy összefoglaló (x db házszám szerepel), (y db utca szerepel (csak ahol van név))

2. Overpass frissítés után nem lehet visszatérni az eredmény oldalra. azt mondja sikeres, de csak a back gomb meg az F5 marad. Régen volt egy eredmény megtekintése ami kikerült.

Vélemény?

**Comment by vasony** [comment]
### Minták:  Suspicious

Területek listája ¦ Meglévő házszámok a környéken ¦ Meglévő utcák a környéken ¦ Frissítés referenciából (másodpercekig tarthat) ¦ terület határa ¦ github
<hr>
Elképzelhető, hogy az OpenStreetMap nem tartalmazza a fenti 3 utcához tartozó 9 házszámot. (meglévő: 113, készültség: 92.62%)<br>
Frissítve 2019-05-11 04:59<br>
<br>
Budaörsi út	6<br>
['181', '183', '187', '189', '193', '201']<br>
Bordézsma utca	2<br>
['3', '10']<br>
Libella köz	1<br>
['6']<br>
<br>
Téves információ jelentése.<br>
<hr>
OSM adatok © OpenStreetMap közreműködők. Verzió: v1-174-ge0178b3<br>

**Comment by vasony** [comment]
### 2.  Streets
<br>
Területek listája ¦ Hiányzó házszámok ¦ Meglévő utcák ¦ Frissítés Overpass hívásával (másodpercekig tarthat) ¦ Lekérdezés megtekintése ¦ github
<hr>
A terület 74 névvel rendelkező útszakaszt tartalmaz  vagy A terület 15 utcát tartalmaz (1 név 1x)<br>
Frissítve 2019-05-08T21:21:54<br>
<br>
@id	name	highway	service<br>
24741904	Bordézsma utca	residential	<br>
....<br>
<br>
OSM adatok © OpenStreetMap közreműködők. Verzió: v1-174-ge0178b3<br>

**Comment by vmiklos** [comment]
Jogos, a frissítés után gagyi a vissza + frissítés.

Teljesen azonos fejléc szerintem nagyon sok tartalmat fog jelenteni, ezek jutnak eszembe:

- első dimenzió: van ugye a főoldal, régen kinn volt az összes link, és nehéz volt eligazodni. De a főoldalnak minimum minden relációhoz mutatni kell valamit
- második dimenzió: egy területtel mit lehet csinálni: utcalista, házszámlista, referencia, hiányok
- harmadik dimenzió: adott terület, adott rész (pl utcalista) aminél meg lehet nézni a mostani eredményt, a lekérdezést, meg újra lehet futtatni

Kiindulva abból amit javasolsz, esetleg arra kéne gyúrni, hogy a fejléc ebben a három dimenzióban engedjen valahogy navigálni:

- terület-listára visszajutni (főoldal)
- ha egy adott területen vagy, a jelenlegi lekérdezés kimenetét minden típusra (utcák, házszámok, stb) el lehessen érni (ez implicite megoldja a felvetésedet, hogy query után nem látható könnyen az eredmény)
- adott terület adott részére (pl utcák) mutatnám az összes akciót: mi a lekérdezés, jelenlegi eredmény, lekérdezés futtatása

És igen, a dátum mehet az láblécbe pl.

Ez így tetszene? Nekem konzisztensnek tűnik (a #43 által kért hiányzó utca funkció is beleilleszthető ebbe a sémába) és azt hiszem azt is adja amit felvetettél problémaként.

**Comment by vasony** [comment]
Igazából hasonlót írunk. Valójában tényleg nem kell egyforma fejléc, konkrétan a fejléccel csak 2 gondom van, a dátum és hogy a streets-től nem lehet átjutni a másik típusra.
Nekem az is jó ha mind a 3 fent van de az is ha a saját nem, ahogy egyszerűbb.

Az összefoglaló adatokat meg a lista elejére tenném, ahogy írtam, de nem ragaszkodom hozzá, csak ott könnyebb egyből átnézni

**Comment by bkil** [comment]
Valamelyest nekem is csípi a szemem. Viszont frissítés után vissza lehet menni az eredmény oldalra: ez a fejlécben a jelenlegi xy megtekintése. Valószínűleg még jobb lenne egy in place incremental HTTP válasz, redirect, XHR, vagy ilyesmi. Persze én pártolom, hogy kerüljük a js-t ahol nincs rá szükség, de még anélkül is volna körüljárás. A frissítés kattintás után amúgy jobb UX lenne behozni egy pörgőt vagy ETA oldalt, ami utána mutatná az eredményt, mint azt látni a böngészőben, hogy nincs válasz.

**Comment by vmiklos** [comment]
Leraktam a láblécbe a frissítés dátumát, ez nekem tetszik, mivel az asciidoc doksik végén is így szokott lenni, és a kérés az volt, hogy ne a fejlécben legyen.
A fejlécet újracsináltam, most már frissítés után van hova kattintani, hogy látszódjon az eredménye. Egy területen belül az első fele a fejlécnek fix, a második fele (lekérdezés forrása és lekérdezés frissítése) pedig az adott funkció szerint változik. Remélhetőleg ez egy jó középút a teljesen egységes és az állandóan más fejléc között.
A hiányzó házszám oldalon egyelőre nem cseréltem meg a sorrendet (összefoglaló vs adatok) mivel jelenleg az adatok kiírása közben számolom ki a statisztikát, de ez úgyis változni fog a tervek szerint (#55).
Írj ha valami fontos kimaradt. :-)

**Comment by bkil** [comment]
Még azzal is spórolhatnánk helyet, ha "eldugjuk" a github linket. Szerintem túl feltűnő helyen van. Ez is lehetne vagy a legalján, vagy csak a főoldalon (szintén legalul)

**Comment by vmiklos** [comment]
Nem vagyok ellene a dolognak, küldesz PR-t?

**Comment by vasony** [comment]
Jó lett így.. a GitHub link most sehol sem látszik. Azért a főoldalra kéne. Vagy a verzióra kellene kattintani?

**Comment by vmiklos** [comment]
A dokumentáció meg a verzió is linkel ide, bár tényleg nem a projekt főoldalára. Szerintem ennyi elég.
