### ISSUE TITLE
pesthidegkut beragadt

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#502]
valami cache-elési probléma van a vmiklos instancian.

elírtam a refsettlement-et, javítottam, de osm-gimmisn nem veszi át. hiábra frissítek bármit.
a vasony.hu-n jó, mert ott úgy megy a frissítés hogy` rm workdir/*pesthidegkut*`, aztan cron

http://osm.vasony.hu/missing-housenumbers/pesthidegkut/view-result 52.58%
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/pesthidegkut/view-result 13.14%

**Comment by vmiklos** [comment]
Van rajta inactive: true, nem amiatt van a különbség?

**Comment by vasony** [comment]
megvan, visszaíródott az egyik frissítésnél a rosszra.
