### ISSUE TITLE
Overpass free slots

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#51]
Ha akarjuk, akkor innen lehet figyelni, hogy tudunk-e futtatni:
https://overpass-api.de/api/status

pl 1)
Connected as: 1501896992
Current time: 2019-05-19T16:31:08Z
Rate limit: 2
**Slot available after: 2019-05-19T16:32:43Z, in 95 seconds.**
Currently running queries (pid, space limit, time limit, start time):
31417	536870912	425	2019-05-19T16:31:06Z

pl 2)
Connected as: 1501896992
Current time: 2019-05-19T16:31:45Z
Rate limit: 2
**1 slots available now.**
Slot available after: 2019-05-19T16:32:43Z, in 58 seconds.
Currently running queries (pid, space limit, time limit, start time):

**Comment by vmiklos** [comment]
Köszi, erről az API-ról nem tudtam. Hatékonyabbnak tűnik mint a naiv megközelítés, hogyha kidob a szerver, akkor újrapróbálni 1, 2, 4, 8 (mondjuk) perc múlva. Ez alapján már lehetne csinálni valamilyen nightly scriptet ami akkor is végigfrissít mindent ha nem nyom rá napközben senki.

**Comment by vasony** [comment]
Tegnap belefutottam, és az error írta. Ugye ki lehet parse-olni az üzenetből mennyit kell sleepelni.

**Comment by vmiklos** [comment]
És tényleg:

https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/dispatch/dispatcher_server.cc#L343

Mindig másodpercben írja ki, nem kell szórakozni perc/óra/stb-vel.

**Comment by vmiklos** [comment]
Az issue gondolom implicit arról szól, hogy legyenek dolgok automatikusan frissítve. 3 dolgot cache-elünk jelenleg:

1) reláció utcái overpassból
2) reláció házszámai overpassból
3) reláció házszámai referenciából

Kérdés, hogy ebből mit frissítsen a cronjob: az 1) és 2) elég egyértelmű; a 3)-nak van értelme?

**Comment by vasony** [comment]
1-2 elég szerintem, gyakrabban a 2) ritkábban az 1)

Miklos Vajna <notifications@github.com> ezt írta (időpont: 2019. jún. 9., V
14:49):

**Comment by vmiklos** [comment]
38m37,001s -- jelenleg amúgy ennyi az összes reláció utcáinak befrissítése, rávizsgálva, hogy mennyit kell várni (minden overpass lekérdezés előtt).

**Comment by vasony** [comment]
ilyenek jutottak még eszembe
- ahol 100% ott nem kell frissíteni
- talán tehetnénk egy flaget a relations-be, refresh=false, vagy archive=true, ahol nem kellene frissíteni. pl Felsőtárkányt előbb utóbb befejezem, akkor biztos nem nyúlok hozzá utána. 
Az archive=true későbbiekben a főoldalon is segíthetne, ha sok lesz a relation és akarunk szűrést. 
- frissítés után meg kell hívni a hiányzó házszám funkciót, mindegyikre, hogy a %-ok frissüljenek a főoldalon
- esetleg később ha nagyon sok idő lesz a szumma frissítés, akkor még lehet intelligenciát vinni a dologba, hogy mi frissüljön és mi nem az alapján, hogy mikor változott utoljára (ami rég változott ott ritkábban frissítünk)

**Comment by vmiklos** [comment]
Úgy tűnik elég nagy a szórás, most 32p alatt lefutott a teljes street+házszám frissítés is. A % téma jogos, de egyelőre az a webes UI része, először azt onnan le kell választani. Majd megnézem. A flag, hogy valamelyik relációt pocsékolás naponta újraszámolni is tetszik; ha majd konkrétan lesz ilyenre igény, akkor megcsinálom.

Egyelőre ha stabilan 1 óra alatt van (és úgy tűnik ez adott, legalábbis helyben) és naponta fut akkor kezdetnek nem gond ha az 1) és 2) naponta elejétől végéig lefut.

**Comment by vmiklos** [comment]
Ez alapvetően megvan, az kell még, hogy főoldali % frissüljön.

**Comment by vmiklos** [comment]
Éjjel lefutott a PythonAnywhere (PA) instance-en a cronjob 8 perc alatt, ez egyelőre megfelel. Most pusholtam a %-os frissítést is. Az helyben jó volt, így gondolom holnapra a PA instance-en is jó lesz.

**Comment by vmiklos** [comment]
Most a főoldalon a százalékok többségében fél4 után nem sokkal frissültek, szóval most már ez az utolsó rész is rendben van.
