### ISSUE TITLE
NMHH szolgáltatók listájának beemelése a referenciába

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#512]
@urbalazs chatből átemelve
újabb címadatbázis az NMHH szolgáltatók listájából: 
http://webext.nmhh.hu/hir_szolg/app/index.jsp
A Listázás gombra kattintás után az eredmények oldalon letölthető Excel fájlként a teljes lista.

**Comment by bkil** [comment]
Köszi. Átraktam CSV-be - letöltés link a mátrixon.

**Comment by vasony** [comment]
kész.
