### ISSUE TITLE
Overpass lekérdezés a refsteets (zárójeles) utcákra

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#513]
http://osm.vasony.hu/missing-streets/keszthely/view-result

mondjuk ide szeretnék egy a [hiányzó házszámokhoz](http://osm.vasony.hu/missing-housenumbers/keszthely/view-turbo) hasonló overpassos funkciót, ami az átnézendő utcákat tartalmazza. nem teljesen itt van a helye, de csak ezért nem kellene neki külön oldal. 
"Overpass lekérdezés a kérdéses nevű utcákra"

A konkrét feladat a már refstreets-ben szereplő utcák osm neveit fel kellene felsorolni, kihagyva azokat amik el vannak nyomva a  `show-refstreets: false értékkel.

Az alap probléma, hogy ha már megcsináltam a street mappinget, akkor itt már nem jelenik meg, és a filterből kellene egyesével keresgetnem hol vannak ha szeretném bejárni a kérdéses utcákat.

**Comment by vmiklos** [comment]
A /missing-housenumbers/keszthely/view-turbo mintájára lehetne egy /missing-streets/keszthely/view-turbo, ami most csak fallbackel a view-resultsra.

**Comment by vmiklos** [comment]
Mondjuk akkor a keszthely az pont rossz példa, mert ott egyetlen `show-refstreet: false` utca sincs. :-) balatonlelle inkább.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
most má' keszthely is jó példa, tökéletes.
