### ISSUE TITLE
fejlécek: overpass turbo

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#521]
http://osm.vasony.hu/missing-housenumbers/keszthely/view-result
http://osm.vasony.hu/missing-streets/keszthely/view-result

lehetne a 2 fejléc egyforma? pont az overpass turbo hiányzik

**Comment by vmiklos** [comment]
Persze

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
ok
