### ISSUE TITLE
UX meglevő házszámok eredménye táblázatba

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#54]
A tabos kimenet a sok mező miatt kevésbé parszolható szemmel mintha egy táblázatot adnánk vissza.

**Comment by vasony** [comment]
támogatom, nekem is eszembe jutott, de már nem mertem új issue-t felvenni :)
akkor már mindegyik legyen táblázatban, mert mobilról nem jól skálázódik a pre

**Comment by vmiklos** [comment]
A "mindegyik" kicsit általános: az overpass eredményeket szerintem is jó lenne táblázatba átrakni, már csak a konzisztencia miatt is. Viszont az overpass bemenetét én meghagynám pre-ben. Szóval az 5-ből 2-t átraknék, a 3 "view query" viszont maradna. Vélemény?

**Comment by vasony** [comment]
A view-query az nem olyan, az maradjon, főleg, hogy azt nem kell nyitogatni annyit

**Comment by vmiklos** [comment]
Ez meg is volna azt hiszem.

**Comment by bkil** [comment]
:dancing_women: :alien:
