### ISSUE TITLE
UX hiányzó házszámok eredménye oldal nem-<pre>

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#55]
Valószínűleg egy sima lista is elég lenne, esetleg egy 3 oszlopos táblázat. Ha már itt vagyunk, az `XY utca 42 ['1', '2']` helyett valami olyan megfogalmazás kellene, hogy ne asszociáljak az XY utca 42. házszámra rögtön, hanem elkülönüljön, hogy 42db hiány van az XY utcában. (`42db XY utca`, `42# XY utca`, `42 XY utca`, új sorban, esetleg `XY utca, hiányzik: 42`) Az aposztrófozásra sincs szükség.

Bár én amikor terepre viszem, be szoktam másolni egy txt-be, így nekem pont jó. Viszont ahol sok házszám hiányzik, a görgető miatt elég fapados hatást kelt. Valójában itt eleve nem nagy feature az, hogy egymás alá rendeződnek a hiányzó házszámok, főleg mivel a számjegyszám eltérés miatt hamar szétcsúszik az illeszkedés.

Plusz kívánság, hogy valószínűleg jó lenne megvastagítani az x<1, x>99, vagy nem-integer bejegyzéseket vagy más módon meghatározott outlier-eket (ahol lukat találunk a referenciában?).

**Comment by vasony** [comment]
ha lehet kérni ne legyenek plusz szövegek, 100% leírjuk ,hogy hiányzik, akkor elég béna lesz.
- 3 oszlopos táblázat az kész, a fejlécbe: utcanév hiányzik db, házszámok
- és ha akarunk, akkor js-el lehet sortolni, aki meg nem szertei a js-t az nem sortol

**Comment by vmiklos** [comment]
A 3 oszlopos táblázat tetszik, azt csináltam meg. A JS sortolásra nincs ellenvetésem, leginkább ha valaki más megcsinálja. :-)

**Comment by bkil** [comment]
I'm delighted. :1st_place_medal:

**Comment by vasony** [comment]
Király lett, a sort-al majd lesz vmi.

**Comment by vasony** [comment]
Ez hogy tetszene? Ezt aláltam, fejlécre sortol:
http://www.vasony.hu/osm/csilleberc.html

ez az erdetei, itt vannak nyilak, de nálam lejjebb ugrik egy kicsi a fejléc ( a p /p-t ki kell szedni a table-ből)
http://www.vasony.hu/osm/csilleberc2.html

**Comment by vasony** [comment]
Most t*k*n szúrtam mag, mert faszán néz ki csak azt kell kitalálni, hogy teszem át text fileba, hogy normálisan nézzen ki :-O 
Most ezzel oldottam meg: http://www.convertcsv.com/html-table-to-csv.htm

Túl nagy kérés egy raw formátum is, ami gyakorlatilag a régi? esetleg az aposztrofok nélkül és egy sorban 
oldal aljára mehetne a link: letöltés text fileban
pl:
Móricz Zsigmond utca	3	[1, 2, 3]
vagy nekem pl a számosság sem kell:
Móricz Zsigmond utca	[1, 2, 3]

ha kell felveszem issue-nak is

**Comment by vmiklos** [comment]
Köszi, tetszik a JS sort, nem tölt be random helyről 5MB-ot, ezzel már átlagon felüli. :-)

Vedd fel kérlek issue-nak, már én is gondoltam erre, hogy az URL végére ha .json-t teszel akkor legyen json kimenet, hátha valakinek csak az adat kell, ne már HTML-t kelljen ehhez parse-olni. Ezt tovább gondolva lehetne .txt végződés is ami meg az eredeti parancssoros kimenetet adja. (A jsont csak példaként írtam, addig nem tervezem megcsinálni amíg valakinek nincs rá szüksége ténylegesen.)

**Comment by vmiklos** [comment]
Beraktam, köszi a static HTML példát.

**Comment by vasony** [comment]
Azért volt benne a CSS, hogy vmi látszódjon a fejlécen, különben senki nem
fog rájönni hogy kattintható. De lehet linkkel is.

A leugrást nem tudtam kiküszöbölni... a háromszög nagyobb mint a font,
azért csinálja, a középre rendezzük kevésbé zavaró:

újabb változat:
http://www.vasony.hu/osm/csilleberc2.html

**Comment by bkil** [comment]
:+1: Még azt szeretném javasolni, hogy hívjuk rá a sort függvényt betöltés után. Jelenleg ha kétszer kattintasz a db oszlopra nem a kezdeti képernyőt kapod vissza, mivel az szerver oldalon volt rendezve.

Amúgy miért szeretnénk txt fájlba menteni? A HTML-t is le lehet menteni ha út közben kell, ha pipálgatni kell, a HTML kódban is meg lehet tenni (főleg ha raknánk még bele néhány entert), stb. Nekem a jelenlegi állapotában is kiválóan működik a copy&paste, egyetlen baj az a plusz `<p></p>` az első sorban, ha kivettem a HTML-ből már makulátlan (főleg ha fel lenne cserélve az első két oszlop).

```
Utcanév	Hiányzik db	Házszámok
Konkoly-Thege Miklós út	21	6, 8, 10, 11, 12, 13, 15, 16, 17, 18, 19, 22, 23, 24, 38, 50, 52, 56, 58, 60, 62
Magas út	12	1, 2, 4, 10, 13, 14, 22, 27, 29, 45, 47, 48
Moha utca	9	6, 9, 11, 13, 17, 21, 31, 33, 37
Tatárvirág utca	7	2, 3, 4, 7, 9, 14, 29
Moha köz	4	2, 3, 4, 6
Sötétvágás utca	3	4, 6, 7
Adorján köz	2	4, 14
Bérclejtő utca	2	7, 10
Magasút dűlő	2	7, 33
```

**Comment by vmiklos** [comment]
> Még azt szeretném javasolni, hogy hívjuk rá a sort függvényt betöltés után. Jelenleg ha kétszer kattintasz a db oszlopra nem a kezdeti képernyőt kapod vissza, mivel az szerver oldalon volt rendezve.

Mindkét irányban tudnék ezzel kapcsolatban érvelni. Értem amit te írsz, viszont pl nekem teljesen jó a táblázat úgy ahogy van, nem nagyon fogom rendezgetni sehova, feleslegesen alapból ráhívni egy JS sortot pazarlás. Úgyhogy azt mondanám, hogy ha küldesz hozzá PR-t akkor nem ellenzem, de nem is csinálom meg. :-)

A .txt formázást a <https://github.com/vmiklos/osm-gimmisn/issues/64> alatt tárgyaljuk, legyen minden ott, hogy később visszakereshető legyen egy helyen.

**Comment by vmiklos** [comment]
> Azért volt benne a CSS, hogy vmi látszódjon a fejlécen, különben senki nem fog rájönni hogy kattintható. De lehet linkkel is. A leugrást nem tudtam kiküszöbölni... a háromszög nagyobb mint a font, azért csinálja, a középre rendezzük kevésbé zavaró: 

Oké, a linkes dolgot meg a valign=centert beraktam.
