### ISSUE TITLE
stat: ref.count

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#561]
varosok_count_20200717.tsv a referencia könyvtárban
...ebből kellene felszummázni a továbbiakban a ref.count fájlba hogy konzisztens legyen, ennyinek kell kijönnie: 3263711

#490

**Comment by vasony** [comment]
> Hogy legyen számolva, egy sum() a 2. oszlopra elég? 

elég

**Comment by vmiklos** [comment]
3268441 lesz az a varosok_count_20200801.tsv alapján most már, ha jól számolok.

**Comment by vmiklos** [comment]
Lehet tesztelni: a `./cron.py --mode stats --no-overpass` jó ref.count file-t kell generáljon most már.

**Comment by vasony** [comment]
frissült
