### ISSUE TITLE
Stat: Városonkénti lefedettség link

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#563]
A stat oldal elején lévő linkj egyből vihetne a külön oldalra, nem az oldal aljára ahol még egyet kell kattintani.

http://osm.vasony.hu/housenumber-stats/hungary/#_cityprogress
helyett
http://osm.vasony.hu/housenumber-stats/hungary/cityprogress

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/

Lehet ezt is tesztelni.

**Comment by vasony** [comment]
ok
