### ISSUE TITLE
Tizedesvessző

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#564]
A magyar oldalon a százalékoknál tizedes pont helyett tizedes vessző kellene.
Helyesírási szabályzat: "A számok írásában a tizedes törtek kezdetét vesszővel jelöljük"

Meg nekem is könnyebb lenne amikor Excelbe másolom

**Comment by vmiklos** [comment]
Lehet róla szó. Azt hiszem ez locale-aware number formatting néven fut, majd megnézem Pythonban mik erre a lehetőségek.

**Comment by vmiklos** [comment]
```
$ LC_ALL=en_US.UTF-8 python3 -c "import locale; locale.setlocale(locale.LC_ALL, ''); print('{0:n}%'.format(12.31))"
12.31%
$ LC_ALL=hu_HU.UTF-8 python3 -c "import locale; locale.setlocale(locale.LC_ALL, ''); print('{0:n}%'.format(12.31))"
12,31%
```

Valami ilyesmi kell majd.

**Comment by vmiklos** [comment]
Lehet tesztelni. Remélhetőleg az összes helyet megtaláltam ahol eddig kézzel formáztuk a százalékot.

**Comment by vasony** [comment]
rpad kéne 100% helyett 100,00%  83,8% helyett 83,80% mert most így bután néz ki.

**Comment by vmiklos** [comment]
A UI nyelve és a locale két külön dolog. A locale configban állítható, magyarra defaultol. A UI nyelvét meg a böngésző dönti el. Ez eddig is így volt, pl a magyar locale szerint ment a sortolás angol UI esetén is.

A 100.00%-ot lehet tesztelni. :)

**Comment by vasony** [comment]
na mi régi

```
Internal error when serving /
Traceback (most recent call last):
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/wsgi.py", line 836, in application
    return our_application(environ, start_response)
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/wsgi.py", line 825, in our_application
    doc.asis(handle_main(request_uri, relations).getvalue())
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/wsgi.py", line 689, in handle_main
    doc.asis(webframe.get_footer().getvalue())
  File "/var/lib/www/osm.vasony.hu/osm-gimmisn/webframe.py", line 43, in get_footer
    doc.asis(util.git_link(version.VERSION, "https://github.com/vmiklos/osm-gimmisn/commit/").getvalue())
AttributeError: module 'version' has no attribute 'VERSION'
```

**Comment by vmiklos** [comment]
Nézd meg a version.py-t, talán valahogy sikerült üressé tenni. Törölheted és akkor a "make" újragenerálja.

**Comment by vasony** [comment]
benne van a VERSION

**Comment by vasony** [comment]
kapott egy restartot, most jó

**Comment by vasony** [comment]
a 100,00 jó, de szerintem egy angolt pont nem érdekli a server locale. Ezt nem configban kellene állítani.

**Comment by vmiklos** [comment]
Lecseréltem egy kézműves megoldásra. :)

**Comment by vasony** [comment]
Jó is :)
