### ISSUE TITLE
Referencia: Berekfürdő POI lista alapján címek, utcák

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#567]
* https://lite.framacalc.org/9hnx-h2tgt7bklf-berekfurdo

Ebből lett előállitva:
* https://wiki.openstreetmap.org/wiki/Hungary/Tal%C3%A1lkoz%C3%B3k/2020-07-05-Berekf%C3%BCrd%C5%91-mapathon#POI

**Comment by vasony** [comment]
hazszam_kieg_20200823 - +26 db cím

**Comment by vmiklos** [comment]
Beraktam: https://github.com/vmiklos/osm-gimmisn/commit/314998db9ec0b62508b18769835c91cf81db2abf

**Comment by vmiklos** [comment]
Beraktam a utca / városszám részt is: https://github.com/vmiklos/osm-gimmisn/commit/3b821ec84b58210f665d6b5f60ec885fe3c3c2b8
