### ISSUE TITLE
Hiányzó házszámok oldal frissítési dátum nem jó

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#57]
Ha frissítem a meglévő házszámokat, akkor frissül a suspicious streets is, mert eltűntek a házszámok helyesen, de a frissítési dátum nem változik.
Csak a ref. frissítéssel.
Régebben ez jó volt.

**Comment by vmiklos** [comment]
Hm, szerintem ez úgy működik ahogy kéne: a dátum az alján azt mondja, hogy a referenciából mikor volt utoljára frissítve, míg a tényleges összehasonlítás az olcsó, így mindig újraszámolódik.

A tényleges működést szerintem butaság lenne átírni, esetleg egyértelműsítsük, hogy az "utolsó frissítés" az minek a frissítése?

**Comment by vasony** [comment]
Ez így félrevezető, mert nem az érdekel, hogy referencia mikor lett frissítve, hanem mikori állapot az, hogy hiányzik a Libella köz 6. Vagy esetleg mindkettő, vagy mégjobb lenne a max() a kettő közül.

A baj ezzel, hogy a dátum nem változik, de a tartalom igen.

**Comment by vmiklos** [comment]
Ja értem. Igen, a max() jó ötletnek tűnik.

**Comment by vmiklos** [comment]
Befrissítettem a weboldalt is.
