### ISSUE TITLE
szemétgyűjtés:  a <1 hónapja berakott aktív relációkat ne módosítsa a parse_access_log.py

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#576]
> Jul1-jul31 közötti időszak adatai, az én instance-emen. A frissen hozzáadott relaciokra lehet türelmi limit, mennyi legyen, 1 hét? 1 hónap? Ezt érdemes lenne kitalálni. Ha írsz neki issue-t, berakhatok ilyet.

Szerintem 1 hónap.

>A Szentantalfát most nem tudom hányadik, mert nem hoztam magammal laptopot :) de ha júliusban nálam nem nézte senki, akkor logikus, hogy kiesett.

Épp hogy bekerült, pedig szerintem a kutya se nézte rajtam kívül.
A másik fura hogy a Békés megyei dolgok 0,1%-on állnak és nem nagyon változtak.

>Ja és azért kötöm látogatottságoz, mert a cél, hogy gyakran kiszolgált adatok naprakészek legyenek. 

Igen, de az se jó ha egy terület aktívan frissül és nem változik a gimmisn.
Akkor valahogy mergelni kellene a 2 instance-t, mondjuk nem tudom, hogy az enyémet rajtam kívül nézi-e bárki, de valamit írtál az access loggal kapcsolatban, majd megnézem ez nálam mit hoz ki.

Akkor összefoglalva
- a) 1 hónap türelmi idő
- b) Kellene generálni egy diffet területenként, ehez el kellene menteni egy textbe a terület + meglévő házszámok db listát (véletlenül épp tudok szolgálni ilyennel a múltból)
- c) A látogatottság eredményét felülbírálni a top 5-tel. ha benne van inactive:false mindenképp
- d) A látogatottság eredményét felülbírálni opcionálisan ha a változás < x (mondjuk 5), akkor inactive: true mindenképp
- e) a 100%-os területek inactive: true, de gondolom ez már benne van

egyébként így nézett ki a top 5
```
balatongyorok	589
esztergom	503
budapest_04	238
komlo		206
budapest_03	146
```

**Comment by vasony** [comment]
```
adyliget	305
albertfalva	1076
alsorakos	1140
balatonalmadi	278
balatoncsicso	100
balatongyorok	599
balatonlelle	157
balatonoszod	276
balatonszarszo	341
balatonszemes	551
barossgabortelep	535
bekes	22
bekescsaba	371
belso-ferencvaros	275
berekfurdo	1088
biatorbagy	1322
bogacs	122
bonyhad	200
budafok	4586
budakeszierdo	25
budaors	2927
budaors-belvaros	928
budaors-kamaraerdo	88
budaors-kertvaros	1263
budaors-lakotelep	286
budapest_03	3720
budapest_04	4110
budapest_05	945
budapest_06	1375
budapest_07	1276
budapest_08	2301
budapest_09	1284
budapest_10	936
budapest_12	4520
budapest_15	3651
budapest_16	1379
budapest_17	1122
budapest_18	702
budapest_19	829
budapest_20	3639
budapest_21	849
budapest_23	270
budateteny	822
csatarka	117
csepel-belvaros	132
dobogo	1
domos	543
esztergom	5215
esztergom-kertvaros	1311
esztergom-kozpont	3893
esztergom-pilisszentlelek	105
felheviz	93
felsotarkany	506
gazdagret	208
gellerthegy	473
godollo	3257
gyomaendrod	6
gyula	46
harshegy	29
herminamezo	210
hosszuret	116
huvosvolgy	38
infopark	3
istvanmezo	246
kamut	4
kelenfold	2679
kelenvolgy	1154
keszthely	1058
kiszuglo	107
koerberek	18
komlo	554
krisztinavaros	950
kurucles	252
lagymanyos	428
lipotmezo	52
madarhegy	199
mezobereny	161
murony	5
nadorkert	0
nagyteteny	390
nagyzuglo	196
nemesgulacs	92
nyek	39
obudavar	31
ormezo	315
orsod	27
orszagut	378
palotanegyed	393
palvolgy	198
pasaret	310
pesthidegkut	2889
peterhegy	299
petnehazyret	57
pilismarot	623
pilisvorosvar	3779
posingermajor	181
rakosfalva	131
rezmal	162
rozsadomb	343
sasad	1954
sashegy	437
sersekszolos	48
somogysard	134
spanyolret	22
szekszard	2754
szemlohegy	202
szentantalfa	129
szentimrevaros	542
szentjakabfa	53
szepilona	50
szepvolgy	6
szigetmonostor	664
szilvasvarad	255
taban	38
tagyon	46
tisztviselotelep	317
torokbalint	2869
torokor	210
torokvesz	785
ujlak	374
ujszilvas	99
var	198
varosliget	19
veresegyhaz	552
verhalom	381
visegrad	477
vizafogo	256
vizivaros	545
zanka	214
zoldmal	182
```

**Comment by vmiklos** [comment]
Legyen ez az issue csak arról, hogy az <1 hónapja berakott aktív relációkat ne módosítsa a `parse_access_log.py`. Ez se triviális önmagában. :-) Ezzel kapcsolatban: mi számítson egy reláció létrehozási dátumának?

Két lehetőség:

- git mondja meg. ennek előnye, hogy már most is van adat, viszont ha pl átrendezed a sorrendet a relations.yaml-ban akkor a git blame az új dátumot fogja írni.

- ezt is explicite elkezdjük követni, mondjuk egy workdir/nev.create file-ban vagy valami ilyesmi. előnye, hogy ha a relations.yaml-ban valaki rendezget, nem veszik el, viszont akkor $today lesz a létrehozási dátuma egyelőre minden relációnak, hiszen most nincs ilyen adatunk.

a .create file-okat mondjuk lehet gitből inicializálni, inkább az a kérdés, hogy van-e értelme ezt explicite követni, vagy "elég" a gites megoldás. Vélemény?

A többire: az Agárd esete valóban jó példa arra, hogy a 31-én felvett relációkat nem optimális elsején kikapcsolni. A többi esetén is meg kéne szerintem nézni, hogy a gyakorlatban indokolt-e ezeket a metrikákat figyelembe venni. Bonyolítja a kódot, nekem időm megy el vele míg lefejlesztem, szóval előbb mérlegelnék.

**Comment by vmiklos** [comment]
> Legyen ez az issue csak arról, hogy ...

https://wiki.openstreetmap.org/wiki/Hungary/osm-gimmisn#Probl.C3.A9m.C3.A1k_jelz.C3.A9se

Ez visszatérő probléma, úgyhogy írtam szájbarágót, hátha ez segít :-)

**Comment by vasony** [comment]
nem segít :-)
más az absztrakciós szint, szerinted ezek külön problémák, szerintem meg nem, mert mind arról szól, hogyan kellene ennek rendesen működnie.

**Comment by vmiklos** [comment]
Jól van, akkor fókuszáljunk a fenti kérdésre, hogy mi lesz a létrehozási dátuma a relációknak. :)

**Comment by vasony** [comment]
>     * git mondja meg. ennek előnye, hogy már most is van adat, viszont ha pl átrendezed a sorrendet a relations.yaml-ban akkor a git blame az új dátumot fogja írni.

git nem tudja megmondani a relations-teruletre? alapvetően a street mappinget meg akarom csinálni minden újra.
fallback a reláció?

**Comment by vmiklos** [comment]
Rendben, akkor git alapján lesz.

**Comment by vasony** [comment]
most akkor a többi külön van, koncentrálhatunk erre :-)

**Comment by vmiklos** [comment]
Lehet tesztelni, Agárdot visszaraktam és nem is szól érte egyelőre.

**Comment by vasony** [comment]
ezt nehéz lesz tesztelni, hozzak létre egy újat aztán megnézzük elsején vagy állítsam át Miskolctapolcát aktívra?

**Comment by vmiklos** [comment]
> visszakapcsoltam Miskolctapolcát, megvárjuk vele elsejét, addig nem zárjuk le

Akkor egyelőre ez lesz a tesztelési terv.

**Comment by vmiklos** [comment]
42f3b9068d087482f4b468dabf4e481feb38ec3b lehet tesztelni

**Comment by vasony** [comment]
ez a része jó, miskolctapolcát és kisoroszit se nyitotta vissza.
viszont a következő körre az #578 legyen, mert több olyan területet is visszanyitott ami 100%-os.
