### ISSUE TITLE
szemétgyűjtéshez: mennyi házszám került fel adott hónapban a monitorozott területekre

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#577]
#576/b (házszám bővülési statisztika)
Kellene generálni minden hónapban minden területre 1 számot, hogy menny házszám került fel az osm-re adott hónapban. 
Sajnos mivel a filterek még nem mennek a referenciából, illetve nem csak város szintű relációink vannak, ezért nem megoldható overpassból

A módszer: 
Lementeni elsején az összes területről mennyi a meglévő házszám xxx_20200801.txt
```
balatonalmadi  276
balatoncsicso  100
balatongyorok  10
```

Ha létezik, összehasonlítani az előző állománnyal xxx_202020701.txt
```
balatonalmadi  278
balatoncsicso  100
balatongyorok  599
velence 111
```
Amelyik terület mindkettőben létezik, a számokat kivonni xxx_diff.txt

```
balatonalmadi  2
balatoncsicso  0
balatongyorok  589
```

ezt az állományt fogjuk felhasználni később a szemétgyűtjő algoritmus továbbgondolásához

**Comment by vmiklos** [comment]
Már most is van egy ilyenünk, hogy: workdir/stats/<dátum>.citycount, ami overpassból jön. Ezen filterekkel nagyon nincs mit szűrni, hiszen OSM adatról beszélünk. (Csak azért, mert valami nincs benne a referenciában, én nem szűrném a szemétgyűjtés céljaira.) Nem település szintű reláció meg csak átmenetileg van, míg egy-egy településen annyi a hiányzó házszám, hogy tovább van bontva. De hosszútávon ezek eltűnnek, ahogy a budapest_12-nél is lett.
Ezek alapján nekem úgy tűnik, hogy a mostani overpassos citycount ad elég értéket, ha az a cél majd, hogy "ami gyorsan bővül, azt ne dobjuk ki, akkor se ha nem látogatják". Viszont külön, párhuzamosan számolni minden településre ezeket bonyolítja a kódot, kevés értéket adva hozzá.
Ezek alapján én hajlok arra, hogy használjuk a .citycountból jövő adatokat, és ne számoljunk mást: sok munka, kevés hozzáadott érték. Vagy valami fontos szempont még kimaradt?

**Comment by vasony** [comment]
OK, használjuk, akkor ezeket. A nem város szint egyelőre kimarad ebből a statisztikából.
Attól még kell egy ilyen összesítő állomány a másikhoz, de az is jó, ha ott kiszámolod.

**Comment by vasony** [comment]
> Nem település szintű reláció meg csak átmenetileg van,

Azért ez nem igaz, Gárdony a példa ahol nem lehet kezelni az azonos nevű utcákat másképp, amíg a referenciában nem választom ketté. De tudok vele élni ha csak város szinten lesz.

**Comment by vmiklos** [comment]
Rendben. Akkor egyelőre maradjunk abban, hogy a szükséges munka/kódbonyolítás és haszon aránya túl nagy, így egyelőre jó lesz a .citycountból számolni. A delta meg egyszerű, azt tudom röptében számolni.
