### ISSUE TITLE
szemétgyűjtés: 100%-os területek kizárása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#578]
#576/e
nem tudom ez meg van-e már valósítva.

A 100%-on álló területeket mindenképp inactive: true-ra kell állítani, a maradék területeket kell látogatottság alapján 80/20-as szabály alapján besorolni.

**Comment by vmiklos** [comment]
A régi és az új kimenetnek ez a diffje az augusztusi adatok alapján:

````
--- old 2020-09-04 22:15:56.249097957 +0200
+++ new 2020-09-04 22:16:02.193097355 +0200
@@ -1,10 +1,6 @@
-data/relation-balatoncsicso.yaml: set inactive: false
+data/relation-budafok.yaml: set inactive: false
 data/relation-gardony-agard.yaml: set inactive: true
-data/relation-kelenfold.yaml: set inactive: false
-data/relation-kelenvolgy.yaml: set inactive: false
-data/relation-obudavar.yaml: set inactive: false
 data/relation-sasad.yaml: set inactive: true
 data/relation-szentantalfa.yaml: set inactive: false
-data/relation-szentjakabfa.yaml: set inactive: false
 data/relation-zanka.yaml: set inactive: false
-Suggested 2 removals and 7 additions.
+Suggested 2 removals and 3 additions.
````

Szóval 5 aktiválás eltűnik: ezek mind 100%osak. A budafok meg bekerül, valszeg azért, mert az új, kisebb listának már így bekerült a felső 20%ába.

@vasony rád bízom, hogy október elejéig nyitva hagyod-e vagy a fentiek alapján lezárod. :-)

**Comment by vasony** [comment]
ez alapján jónak tűnik, majd nyitok újat, ha valami gond van a következő körben.
