### ISSUE TITLE
szemétgyűjtés: látogatottság és házszám bővülési statisztika alapján az algoritmus finomítása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#579]
#576 #577 #578 után

Meglévő működés:
- Van egy listánk mi lesz aktív és mi inaktív a (korrigált) látogatottsági statisztika alapján. 
- Ezt átvezetjük a területeken.

Továbbfejlesztett működés
- Van egy listánk mi lesz aktív és mi inaktív a (korrigált) látogatottsági statisztika alapján. 
- Fogjuk a házszám bővülési statisztikát, csökkenő sorrendbe rendezzük: a top 5 elemet aktívra állítjuk a fenti listát felülbírálva.
- Fogjuk a házszám bővülési statisztikát, és mindazon területeket hol a bővülés < 5, inaktívra állítjuk, a fenti listát felülbírálva.
- A módosított listát átvezetjük a területeken.

**Comment by vmiklos** [comment]
Pár megjegyzés:

- tegyük fel, hogy ezt ma futtatom, akkor a bővülést szerintem az előző hónapra érdemes nézni, tehát a diff az 2020-09-01 és 2020-10-01 legyen, azt javaslom. a log amit adok neki az tipikusan ezt az időszakot fedi le
- inkább csak magamnak írom, hogy a bővüléshez az adatok itt érhetőek el: pl. workdir/stats/2020-09-01.citycount
- a diffből kimarad az aláhúzással kezdődő üres/invalid

A többi egyelőre egyértelműnek tűnik, bár ha nekiállok, még lehet felmerül valami. :-)

**Comment by vmiklos** [comment]
Régi kimenet:

````
data/relation-pilisvorosvar.yaml: set inactive: true
Suggested 1 removals and 0 additions.
````

Új kimenet:

````
data/relation-balatonalmadi.yaml: set inactive: true
data/relation-balatonszemes.yaml: set inactive: true
data/relation-bekes.yaml: set inactive: true
data/relation-bekescsaba.yaml: set inactive: true
data/relation-biatorbagy.yaml: set inactive: true
data/relation-bogacs.yaml: set inactive: true
data/relation-bonyhad.yaml: set inactive: true
data/relation-budaors.yaml: set inactive: true
data/relation-budapest_08.yaml: set inactive: true
data/relation-budapest_09.yaml: set inactive: true
data/relation-domos.yaml: set inactive: true
data/relation-esztergom.yaml: set inactive: true
data/relation-felsotarkany.yaml: set inactive: true
data/relation-godollo.yaml: set inactive: true
data/relation-gyula.yaml: set inactive: true
data/relation-keszthely.yaml: set inactive: true
data/relation-komlo.yaml: set inactive: true
data/relation-murony.yaml: set inactive: true
data/relation-pilismarot.yaml: set inactive: true
data/relation-somogysard.yaml: set inactive: true
data/relation-szekszard.yaml: set inactive: false
data/relation-velence.yaml: set inactive: true
data/relation-visegrad.yaml: set inactive: true
data/relation-zanka.yaml: set inactive: true
Suggested 23 removals and 1 additions.
````

Lényeg, hogy pilisvörösvár már nem esik ki, mivel megvan az aktivitás. U.ez szekszárdra. A többinél meg az ellenkezője: hiába van látogató, nincs aktivitás, így kiesik.

Egyelőre ezeket most nem állítgattam, de a következő hónap eleji frissítés akkor már ez alapján lesz.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/osm-gimmisn/commit/d7b37e4ce242268fd7176b72628d0721175d57f2

Lehet tesztelni.

**Comment by vasony** [comment]
a specifikációnak megfelel, kérdés a top 5 elég-e, vagy top 10 legyen. pilismarót 47 bővüléssel most inactive lett.
tégy belátásod szerint, zárható.

**Comment by vmiklos** [comment]
Egyelőre jó lesz, ha nagyon zavaró, akkor újra fel lehet vetni.
