### ISSUE TITLE
Csak az OSM-ben szereplő házszám többlet megjelenítése

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#580]
Ha nem szerepel a referenciában az adott házszám, azt is lehetne mutatni egy új táblázatban.

Néha ez valódi:
* amikor ezek újonnan kiosztottak a régi referenciához képest,
* ha pontosabbak vagyunk mint a referencia,
* ha olyan házat találtunk ahol nincs vagy abban a pillanatban nem volt bejelentve szavazó vagy üzlet.

Néha ez hamis:
* elírás a számban (vagy utcanévben),
* utca átnevezés (rendszerváltás vagy más okból),
* út vs útja vs. utca különbség,
* jó szám, csak rossz utcához lett rendelve.

Ehhez a funkcióhoz is kell szűrőfájlokat támogatni, amivel elrejthető az a többlet amit már verifikálta valaki és/vagy patchtáblát a jó-rossz utcanevekkel.

**Comment by vmiklos** [comment]
A dolog gyökere az `util.get_only_in_first()` fordított paraméterekkel való meghívása, a többi meg a hab a tortán. :-)

**Comment by bkil** [comment]
Igen, emlékszem rá, jó kis függvény is az.

**Comment by urbalazs** [comment]
Áthozom a Matrixról, hátha van benne használható ötlet:

A gimmisn jelenleg azt ellenőrzi, hogy az OSM-en szerepel-e minden utca és házszám, ami a referenciában adott. Mekkora munka lenne egy fordított ellenőrzést implementálni, vagyis hogy mutassa meg azokat az utcákat és házszámokat, amelyek az OSM-en megvannak, de a referenciában nincsenek? Mondok két használati esetet:

1. Felesleges utcák: Berekfürdőn jelenleg az Orgona utca több szakaszból áll, és egy szakaszon hibásan Orgona út szerepel. A gimmisn most azt mutatja, hogy 100%-os az utcalefedettség, ami igaz is, mert van Orgona utca. Viszont van Orgona út is, ami hiba. Jó lenne, ha ezt is tudná jelezni.
2. Felesleges házszámok: tegyük fel, hogy van egy üzletház, Minta utca 10. Van benne 5 üzlet, ugyanilyen címmel. Egyet véletlenül elírtak, és Minta utca 100. lett a cím. A gimmisn szerint minden házszám megvan, viszont van egy olyan is, amely hibás, nem szerepel a referenciában. Jelenleg az `invalid` szűrővel lehet kiszűrni a referencia hibás számait. Hasonlóan, a `valid` szűrő bevezetésével lehetne jelezni, ha egy házszám valóban szerepel a terepen, de nincs a referenciában. Ez utóbbit ellenőrizni is egyszerű, mert az OSM koordináta adott, így pontosan tudni, hova kell menni megnézni a gyanús házszámot.

   Vagy egy egyszerűbb példa: a Minta utca páros oldala 10-ig tart, de meg lett rajzolva egy új épület, és exrapolációs becslés alapján ki lett töltve a házszám 12-re. A terepen ellenőrizve kiderül, hogy az nem külön telek, csak egy gazdasági épülete a 10-es háznak.

**Comment by vmiklos** [comment]
https://wiki.openstreetmap.org/wiki/Hungary/osm-gimmisn#Probl.C3.A9m.C3.A1k_jelz.C3.A9se

Kérem legyen egy külön issue a házakra. Az utcákat lenne érdemes először, az egyszerűbb, azt követhetjük itt. Köszi.

**Comment by bkil** [comment]
Kettébontottam, hogy ez az issue megegyezzen az @urbalazs által leírtakkal és ne kelljen szerkeszteni a kommentjét. Ez az issue a házszámokkal foglalkozik, a #611 pedig csak az utcanevekkel.

**Comment by vmiklos** [comment]
Az utcaneves dolgot megcsináltam még november elején, egyelőre senki nem ugrott rá, hogy elkezdje átnézni az eredményt. Feltételezem, hogy ez is olyan lesz mint a házszámoknál, hogy a fele jogos és OSM-re szerkesztendő, fele meg zaj.

Először szeretném látni, hogy az utca többletet használja valaki, addig sok értelmét nem látom a házszám többlet leprogramozásának.

**Comment by bkil** [comment]
Ez jogos. A véleményem szerint amennyiben kihirdetnéd 1-2 mondatban a mikroblogodon (Mastodon, Pleroma, stb), majd a linket tovább osztanád a levlistán és mátrixon, biztosan többen elkezdenék használni.

Valami ilyesmi lehetne (279 karakter linkkel együtt, hely szűkében a _mostantól_ szó még elhagyható):

> Osm-Gimmisn fejlesztés: mostantól minden területhez listázom az OSM-ben szerepelő, de a referenciából hiányzó utcákat (eddig csak fordítva volt). Elírások rettegjetek! 🔬 ✍️ Szeretettel várok minden visszajelzést https://osm-gimmisn.vmiklos.hu/ #OsmGimmisn #OpenStreetMap #Hungary

Úgy általában a felhasználói funkciók bevezetését javasolt meghirdetni, még ha nem is muszáj minden változáscsomagot szétkürtölni.

**Comment by vmiklos** [comment]
Azóta @vasony meg @urbalazs használja az utca többletet, így egyelőre reklámra nincs szükség.

**Comment by vasony** [comment]
ezt még ne írjuk le

**Comment by vmiklos** [comment]
Lesz itt még sok teendő de valahol el kell kezdeni. :-)

**Comment by vmiklos** [comment]
Most már van ilyen pl, hogy https://osm-gimmisn.vmiklos.hu/osm/additional-housenumbers/szigetmonostor/view-result (itt tipikusan sok a zaj, mivel a sok nyaralóba nincs bejelentett választópolgár). Szűrni még nem lehet, és nem is linkel ezekre az oldalakra semmi. Folyt. köv.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/additional-housenumbers/szigetmonostor/view-result annyit fejlődött, hogy most már írja, hogy X utcából Y házszám a többlet, míg eddig csak az X utca volt meg. Ez azért fontos, mert a főoldalra majd pont ezt az Y számot érdemes kivezetni.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/additional-housenumbers/szigetmonostor/view-result

A fentivel már lehet szűrni az házszám többlet listát ha felmérés alapján jó az OSM. Példaként a Muskátli utca 8-at kiszűrtem, létezik az csak nincs benne a referenciában. Doksiba tettem egy kis figyelmeztetést, hogy azért ez alapján ne álljon neki törölni a nép. Azt hiszem az opt-in + webes linkek (főoldalról, oldal tetején eszköztárból) hiányzik még és akkor majd lehet megköpködni, hogy jó-e így.

**Comment by vmiklos** [comment]
Lehet tesztelni. @vasony kérésének megfelelően ez alapból ki van kapcsolva, mintaképpen szigetmonostorra bekapcsoltam.

@urbalazs tippelek, hogy budafokra be akarod majd kapcsolni, ehhez a configba egy sor kell csak:

https://github.com/vmiklos/osm-gimmisn/blob/d1fb0689ad82b2eb211d82260d855b7d4104ab6a/data/relation-szigetmonostor.yaml#L241

**Comment by vmiklos** [comment]
ha van még ezzel kapcsolatban valami kérés, akkor arra legyen külön issue
