### ISSUE TITLE
(Vesszőt tartalmazó utcanév) street mapping nem működik

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#585]
http://osm.vasony.hu/missing-streets/miskolc/view-result

Probléma:
"Első sor" megjelenik hiányzónak, pedig van rá street mapping:

relation-miskolc.yaml:
  'Kisavas, Első sor': 'Első sor'

Azt gyanítom hogy a vessző kavar be, mert [itt](http://osm.vasony.hu/streets/miskolc/view-result) macskakörömben van: "Kisavas, Első sor"

**Comment by vmiklos** [comment]
Ha jól látom, az overpass így adja vissza. Mivel \t a szeparátor, így a "," esetén a "" escape-elés felesleges.

```
$ git grep '.get_osm_streets_stream('
areas.py:    def get_osm_streets_stream(self, mode: str) -> TextIO:
areas.py:        with self.get_osm_streets_stream("w") as sock:
areas.py:        with self.get_files().get_osm_streets_stream("r") as sock:
wsgi.py:        with relation.get_files().get_osm_streets_stream("r") as sock:
```

A 2, 3, 4. hívásokat kell átnézni, hogy kezeljék ezt.

**Comment by vmiklos** [comment]
Házszámoknál ugyanilyen probléma van (ott is CSV az overpass kimenete), akkor már javítom a kettőt egyszerre.

**Comment by vasony** [comment]
melyik mezőben van ott vessző?

**Comment by vmiklos** [comment]
Ha a hazszam oszlopban pl 1-2 helyett 1,2 lenne, akkor az overpass "1,2"t ad, ez nem volt kezelve. Nem néztem, hogy tényleg kaptunk-e ilyet a gyakorlatban, a mypy (a python tipusellenorzoje) találta meg a hibát. Amúgy lehet tesztelni :)

**Comment by vasony** [comment]
ok
