### ISSUE TITLE
legaktívabb városok stat: csak valós települések és budapest kerületek legyenek

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#594]
2020-08-22.citycount-ban most ilyenek vannak:
```
budapest_00  1
budapest_77	2
budapest_99  1
```
kellene egy mapping az addr:city-re a .citycount létrehozóba
1. minden ami nem budapest_01..23 közötti budapest* azt budapest-re kellene mappelni
2. minden ami nem létező település (nincs a varosok_count_20200820.tsv-ben és nem budapest)-> (hibás) 

illetve a megjelenítőbe:
3. üresek nem tudom most milyen szöveggel kerülnek be a unique miatt még nem jelentek, de azt is el kellene nevezni, pl. (üres)

**Comment by vmiklos** [comment]
>     1. minden ami nem budapest_01..23 közötti budapest* azt budapest-re kellene mappelni

Pár ilyen kiesett:

-budapest_00    1
-budapest_56    1
-budapest_83    2
-budapest_99    1

**Comment by vmiklos** [comment]
> 2. minden ami nem létező település (nincs a varosok_count_20200820.tsv-ben és nem budapest)-> (hibás)

Ebből most _Invalid meg _Empty lett, majd a megjelenítő csinál belőle szép stringet. A diff amúgy érdekes:

````
$ diff -u1 workdir/stats/2020-09-25.citycount.orig workdir/stats/2020-09-25.citycount    
--- workdir/stats/2020-09-25.citycount.orig     2020-09-25 22:34:29.116267046 +0200
+++ workdir/stats/2020-09-25.citycount  2020-09-25 22:34:36.120253896 +0200
@@ -27,7 +27,8 @@
 budapest_05    1167
-budapest       201
+budapest       151
 budapest_02    9780
 budapest_06    1741
+_Invalid       243
 budapest_07    1606
-       2271
+_Empty 2271
 enying 12
@@ -1296,3 +1297,2 @@
 kékcse 1
-pilismarót-dunapart    5
 murarátka      2
@@ -1355,6 +1355,4 @@
 sóly   1
-veszprém-kádárta       1
 litér  12
 szentkirályszabadja    131
-badacsony      3
 lesencetomaj   1
@@ -1442,3 +1440,2 @@
 ikervár        42
-11     1
 pér    1
@@ -1796,3 +1793,2 @@
 gádoros        1
-szõd   183
 vanyarc        1
````

Ez a hullámos ő betűs Sződ pl aranyos. :-)

**Comment by vmiklos** [comment]
A javascriptre nincs teszt, szóval úgy teszteltem kézzel, hogy most épp orgovány és kisoroszi a top 2 település, helyben átírtam a JS-t, hogy azokat cserélje a lokalizált üres/hibás stringekre. Egyébként egyik se kerülne bele a top 20-ba, szerencsére. :-)

Lehet tesztelni. A .citycount file-t így lehet gyorsan újragenerálni:

````
./cron.py --no-overpass --mode=stats
````

**Comment by vasony** [comment]
```
-budapest       201
+budapest       151
```

ez miért csökkent?

**Comment by vasony** [comment]
igazából nem csökkent, ez valami köztes állapot lehetett, nálam ez van:
```
-budapest	50
+budapest	151
```

**Comment by vmiklos** [comment]
Valószínűleg valamit rosszul diffeltem
