### ISSUE TITLE
Május 1. utca simplify()

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#61]
A fitlerben nem tudom megadni a majus_1_utca és 'majus_1._utca' sem tetszik neki, mert a travis elszáll.
Szerintem a helpers-ben a simplify a pontot is szedje ki, es akkor nincs gond, egyebkent sem kell pl:

    s = s.replace('.', '')

**Comment by vmiklos** [comment]
Jogos, amíg van simplify (beszéltük, hogy hosszútávon ne legyen), addig vesszen a pont.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/biatorbagy/view-result
Május 1. utca	42 -> ez eltűnt, jónak tűnik.

**Comment by vasony** [comment]
Eltűnt az nem jó. De ref frissítés után már jó, mert most oda is legenerálta az új formátumot.
Május 1. utca	41 a helyes.
