### ISSUE TITLE
Csak az OSM-ben szereplő utcanév többlet megjelenítése

### ISSUE THREAD

**Issue by bkil** [vmiklos/osm-gimmisn#611]
Ha nem szerepel a referenciában az adott utca, azt is lehetne mutatni egy új táblázatban.

Néha ez valódi:
* amikor ezek újonnan kiosztottak a régi referenciához képest,
* ha pontosabbak vagyunk mint a referencia,
* ha olyan utcát találtunk ahol nincs vagy abban a pillanatban nem volt bejelentve szavazó vagy üzlet.

Néha ez hamis:
* elírás az utcanévben,
* utca átnevezés (rendszerváltás vagy más okból),
* út vs útja vs. utca különbség.

Ehhez a funkcióhoz is kell szűrőfájlokat támogatni, amivel elrejthető az a többlet amit már verifikálta valaki és/vagy patchtáblát a jó-rossz utcanevekkel.

**Comment by vmiklos** [comment]
Tervezek ezzek a közeljövőben foglalkozni. Pár gondolat mielőtt nekiesnék, mint Marc hevesen. :-)

- az osm <-> referencia megfeleltetés az szerintem a valóságban minkét irányban veszteséges (általában 1:1, de néha 1:N, néha N:1), így az összerendeléseket is kézzel kell majd a visszafele irányban is felvenni, én ezt nem automatizálnám
- ennek megfelelően a reláció yaml-ba kell majd 2 új kulcs: a `refstreets` és a `street-filters` mintájára

Elvileg nem egy bonyolult dolog, de persze majd közbe derül ki mi az amire előre nem számítottam.

**Comment by vasony** [comment]
sok szemét utcanév lesz. 
vagy az overpasst tuningoljuk fel vagy sok lesz a filter.
főleg a path footway pedestrian típusoktól tartok.
az osm-ref 1:1 összerendelések megvannak en ezt felhasználnám.
esetleg a refstreets kulcsot át lehetne irni street mappingre, a street-filters név se lesz egyértelmű ezután kell osm street filter és  ref street filter

**Comment by vmiklos** [comment]
A jelenlegi street mappeles engedi, hogy több osm nevet is ugyanahhoz a ref névhez rendelje. Szerinted feltételezhetjük, hogy ezt sehol se használjuk? Ha elvben igen, akkor írok erre tesztet és akkor tényleg visszafelé is használhatjuk az osszerendelest. Amúgy meg persze, hogy sok lesz a szemét, de ha közte találunk nem felszerkesztett utca atnevezeseket vagy elirasokat, akkor van értelme végignézni kézzel, gondolom.

**Comment by vmiklos** [comment]
Lesz még itt más is: https://wiki.openstreetmap.org/wiki/Hungary/Utcan%C3%A9v_teljess%C3%A9g "a választási utcanévjegyzék csak azokat az utcákat tartalmazza, ahol laknak választópolgárok. Lakatlan - építés alatt lévő - kihalt utcák nem szerepelnek benne. Ebből az is következik, hogy vannak utcák az OpenStreetMap-ben, amelyek nem szerepelnek a választási utcanévben, és ez így normális."

Szóval lesz mit kiszűrni filterekkel :) még ha az osszerendelesek meg is vannak

**Comment by vmiklos** [comment]
Ez csak a dolog magja egyelőre, webes felület meg filterek még hátravan.

**Comment by vasony** [comment]
Govcenterből és egyéb forrásokból én bővítem az utcákat, de valószínű ha valós az utca (van rá más forrás), akkor a referenciát fogom inkább utána húzni.


> A jelenlegi street mappeles engedi, hogy több osm nevet is ugyanahhoz a ref névhez rendelje. Szerinted feltételezhetjük, hogy ezt sehol se használjuk? Ha elvben igen, 

Nem emlékszem olyanra, ahol nem 1:1 mappelés van, ha írnál rá tesztet most, akkor okosabbak lennénk. Rezső tér volt ilyen, de azzal nem boldogultam, így nem került mappelésre.

**Comment by vmiklos** [comment]
> Nem emlékszem olyanra, ahol nem 1:1 mappelés van, ha írnál rá tesztet most, akkor okosabbak lennénk.

A fentivel a validator mostantól nem engedi több osm név egyetlen ref névre való mapelését. Úgyhogy ez a rész megoldva, innentől ezek a hozzárendelések mindkét irányban használhatók lesznek, lehet örülni. :)

Amúgy csak érdekességként írom, hogy lesz kimenet bőven, budapest_12-re pl ezeket kapom most:

```
$ ./additional_streets.py budapest_12

5-7 (magánterület)
Abos lépcső
Adonis utca
Anjou lépcső
Anna-rét
Barabás-villa kertje
Csaba lépcső
Csemegi lépcső
Csermely lépcső
Csobolyó lépcső
Devecseri Gábor park
Disznófő út
Dr. Csapody István út
Dr. Gergely Rezső lejtő
Dr. Gyurmán Emil park
Dr. Góth Endre út
Dr. Hajdu Imre tér
Dr. Horváth Mihály út
Dr. Hudovernig Károly út
Dr. Jantsek Gyula út
Dr. Kasper Károly út
Dr. Kluge Endre út
Dr. Kováts Ferenc út
Dr. Kálló Antal út
Dr. Ludvik Endre tér
Dr. Lénárt Gyula út
Dr. Manninger Vilmos sétány
Dr. Nebenführer László lejtő
Dr. Noszkay Aurél sétány
Dr. Sassy Dobray Gábor út
Dr. Sebestyén Gyula út
Dr. Szám István tér
Dr. Takó József út
Erdő ösvény
Erdőalja út
Erzsébet-kilátó út
Ezüstfenyő utca
Eötvös József park
Eötvös Loránd park
Farkasréti temető
Fenyő ösvény
Feszület körönd
Fogashoz vezető út
Főtér
Gesztenyés kert
Gyopár ösvény
Gyöngyvirág utca
Gálszécs út
Hunyad-orom lépcső
Hóvirág köz
Ibolya ösvény
Jenő út
Juliska út
Kakukk lépcső
Kakukkhegyi erdősor
Kalóz köz
Karolina út
Karthauzi köz
Kepe lépcső
Kodály körönd
Korányi Frigyes út
Kossuth Lajos utca
Kossuth Zsuzsanna tér
Lepke ösvény
Liliom ösvény
Lisszabon sétány
MOM park
MOM, Alkotás utca
Madár lépcső
Makkosi út
Maros passage
Mezei Mária utca
Mindenszentek tere
Mindszenty József bíboros tér
Mária út
Márton Áron tér
Mélygarázs
Mókus ösvény
Németvölgyi lejtő
Orgona ösvény
Padka lépcső
Padka utca
Perbete utca
Perem ösvény
Pethényi lépcső
Pillangó ösvény
Pille köz
Pipacs ösvény
Rekortán futócsík
Ribizli lépcső
Róka ösvény
Rózsa dűlő
Sota Rusztaveli tér
Sugár út
Szegfű ösvény
Szent Család park
Szepesi utca
Sztehlo Gábor utca
Szunyogh út
Széchenyi-emlék út
Szélső utca
Szépkilátás út
Sólyom lépcső
Tearózsa út
Trinitárius utca
Tulipán dűlő
Tücsök lépcső
Tündérhegyi út
Vezér utca
Virágvölgy utca
Visszhang utca
Várfok utca
Városmajor
Vérmező út
Wodiáner Albert park
Zugligeti Szent Család Plébánia
mozgássérült gyakorlópark
Árkay Aladár sétány
Árkay Bertalan sétány
Élmény a természetben
```

**Comment by vmiklos** [comment]
Egyelőre a 'refstreets' kulcsot meghagytam változatlan névvel, illetve lett egy új 'osm-street-filters' kulcs is, amivel az OSM utcanév hibás riasztásokat lehet szűrni. Illetve doksit az egészhez. Ezzel sztem a yaml résszel megvagyunk, max esetleg majd a kulcsokat érdemes átnevezni ha van jobb név-ötlet rá. Webes felület is lesz majd, de az még hiányzik.

**Comment by vmiklos** [comment]
Lehet tesztelni: https://osm-gimmisn.vmiklos.hu/osm/additional-streets/budapest_12/view-result

főoldal linkeli a többi relációra is

**Comment by vmiklos** [comment]
Doksi: https://github.com/vmiklos/osm-gimmisn/tree/master/doc#searching-for-additional-streets

**Comment by vasony** [comment]
OK, nézem majd. János kórház és a Csillebérci központot kiszűrjük, akkor már jóval kevesebb lesz.

Olyan lehet kérni, hogy linkeljen az osm objektumra? Vagy az külön issue legyen? Révén több osm objektum is lehet 1 néven.

**Comment by vasony** [comment]
Illetve nem tudom az ilyen Barabás villa kertje dolgokkal mit kezdjük, nyilván ki lehet szűrni, de úgy általában van-e módszerünk rá? (overpass, access stb.)

**Comment by vmiklos** [comment]
> Olyan lehet kérni, hogy linkeljen az osm objektumra? Vagy az külön issue legyen?

Megnézem, valszeg nem bonyolult. Ha egyszerre egy dolgot kértek, tőlem mehet továbbra is ebben az issue-ban. :)

> Illetve nem tudom az ilyen Barabás villa kertje dolgokkal mit kezdjük, nyilván ki lehet szűrni, de úgy általában van-e módszerünk rá? (overpass, access stb.)

Van a data/streets-template.txt, esetleg azt érdemes szigorítani? Jó lenne ha a "mi számít utcának" (az OSM-ből) kérdésre a missing-streets meg az additional-streets estén is u.azt a választ adnánk.

**Comment by vasony** [comment]
> Van a data/streets-template.txt, esetleg azt érdemes szigorítani? Jó lenne ha a "mi számít utcának" (az OSM-ből) kérdésre a missing-streets meg az additional-streets estén is u.azt a választ adnánk.

igen, ezért vakarom a fejemet, hogy ha itt kiszűrünk valamit, akkor ne legyen az hogy a másik oldalon megszívjuk, kísérletezek majd, de nem is szeretném túlbonyolítani az overpass queryt, mert akkor az életben nem fut le.

**Comment by vmiklos** [comment]
Ha a fenti átcsorog a CI-on akkor most már az eredmények többsége link kell, hogy legyen. (Akkor nem, ha az utca neve csak egy házszámból jön, az ilyen ritka és további macera lenne, hogy az is link legyen.)

**Comment by vasony** [comment]
http://osm.vasony.hu/additional-streets/telkibanya/view-result

Az OpenStreetMap tartalmazza a lenti 1 további utcát.

A táblázat meg üres :-O

**Comment by vmiklos** [comment]
Van ott egy elem, csak üres. Gondolom az OSM-en van több név nélküli utca is, a referenciában meg nincs. Van olyan eset ahol ez érdekes lehet vagy egyszerűen szűrjem ki kódban az üres utcanevet az OSM oldalon?

**Comment by vasony** [comment]
szűrd ki az üres utcaneveket, itt nem releváns.
szerintem overpassban is szűrhetnénk, minek hozzuk le ha úgyse kezdünk vele semmit.
ha egyetértünk akkor csak 2 [name] kell a 3. és 12. sorba

**Comment by vmiklos** [comment]
Igen, tetszik az ötlet, hogy már az overpass szűrje ki. Megszereled a query-t vagy csináljam én?

**Comment by vasony** [comment]
Megszerelem.

**Comment by vasony** [comment]
azt hittem csak megemlíti, inkább kiszedtem, még ne zárja le

**Comment by vasony** [comment]
> Van ott egy elem, csak üres. Gondolom az OSM-en van több név nélküli utca is, a referenciában meg nincs. Van olyan eset ahol ez érdekes lehet vagy egyszerűen szűrjem ki kódban az üres utcanevet az OSM oldalon?

Még mindig rossz, most már kénytelen leszel megnézni, hogy miért van ott még továbbra is az 1 elem :)

**Comment by vmiklos** [comment]
Az volt a baj, hogy az házszámokból még jöhetett üres utca. Javítva, lehet tesztelni.

**Comment by vmiklos** [comment]
Ez zárható, vagy van még ezzel tennivaló? Leszámítva a külön issue-ban kért dolgokat.

**Comment by vasony** [comment]
szerintem ha lesz gond, akkor majd külön issueban, most ez így jó lesz, zárhatjuk.
majd elkezdem filterezgetni, akkor még jöhet ki gond
