### ISSUE TITLE
vesszőt tartalmazó házszámok kezelése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#613]
A vesszőt úgy kellene kezelni mint a pontosvesszőt, több számra bontani, nem csak az elsőt használni

http://osm.vasony.hu/missing-housenumbers/budaors/view-result.txt
Bazsarózsa utca	[...29-33...]

https://www.openstreetmap.org/node/7814506857
Bazsarózsa utca	29,33

**Comment by vasony** [comment]
Egyelőre nem találtam másik példát amivel tudjuk tesztelni, de még keresek. 
Amit néztem azoknál vagy nem volt a refben, vagy megvolt külön is a hátsó szám.

**Comment by vasony** [comment]
Találtam tesztesetet, ez lefedi az összes problémát, nem csak 2 tagú lehet vesszőnél, pontosvesszőnél, de most erre nem veszek fel külön issuet, úgyis ugyanott javítod.

http://osm.vasony.hu/missing-housenumbers/komlo/view-result.txt
```
Eötvös Loránd utca	[5, 9, 13, 17, 19],...
```

osm:
```
Eötvös Loránd utca	3,5
Eötvös Loránd utca	7,9
Eötvös Loránd utca	11,13
Eötvös Loránd utca	15,17,19
```

**Comment by vmiklos** [comment]
Most nem túrtam ki gitből a történetét, de a ; kicsit más, ott az 1;5 is csak 1, 5 lesz, és 3 nem lesz belőle, gondolom ez valami OSM-es dolog, hogy elemeket ; választ el. Az 1-5 az 1, 3, 5 és a vesszőt is ilyen kötőjelesre tervezem.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
szerintem a vesszőt inkább a pontosvesszőhöz hasonlóan kellene kezelni nem a minuszhoz hasonlóan. 
valamelyik wiki oldal a házszámok közé vesszőt javasolt:
https://wiki.openstreetmap.org/wiki/Item:Q43

az eredeti hibajelentésem ilyen szempontból rossz, ott maradnia a javítás után is hiányzónak kell venni, az osm-ben kell javítani.
29,33 maradjon csak 29,33 a 29;33-hoz hasonlóan, ne 29,31,33. ezért kerestem a másik példát

tehát:
29,33 -> 29, 33
29;33 -> 29, 33
29-33 -> 29, 31, 33

**Comment by vmiklos** [comment]
Köszi a wiki linket, meggyőztél.

**Comment by vmiklos** [comment]
Teszt kör 2 :-)

**Comment by vasony** [comment]
Most jó lesz.
