### ISSUE TITLE
szemétgyűjtés: user agent szűrés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#616]
Szentantalfa 163 találatot adott augusztusra, ebből 1 tűnik humánnak a többi robot.
A vastagokat kellene kiszűrni:

Mozilla/5.0 (compatible;   **SemrushBot**/6~bl; +http://www.semrush.com/bot.html)
Mozilla/5.0 (compatible; **AhrefsBot**/6.1;   +http://ahrefs.com/robot/)
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P)   AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile   Safari/537.36 (compatible; **Googlebot**/2.1; +http://www.google.com/bot.html)
Mozilla/5.0 (compatible; **YandexBot**/3.0;   +http://yandex.com/bots)
Mozilla/5.0 (compatible; **bingbot**/2.0;   +http://www.bing.com/bingbot.htm)
Mozilla/5.0 (compatible; **AhrefsBot**/7.0;   +http://ahrefs.com/robot/)
**CCBot**/2.0 (https://commoncrawl.org/faq/)

**Comment by vmiklos** [comment]
> Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92

Ebben a sorban nem jelöltél bolddal semmit és validnak is tűnik, ez nem lesz bot szerintem.

**Comment by vmiklos** [comment]
Ilyen lett a diff:

````
--- old 2020-09-11 18:09:29.466523766 +0200
+++ new 2020-09-11 18:17:41.609994275 +0200
@@ -1,6 +1,31 @@
+data/relation-balatonalmadi.yaml: set inactive: true
+data/relation-balatonoszod.yaml: set inactive: true
+data/relation-balatonszarszo.yaml: set inactive: true
+data/relation-bekes.yaml: set inactive: true
+data/relation-biatorbagy.yaml: set inactive: true
 data/relation-budafok.yaml: set inactive: false
-data/relation-gardony-agard.yaml: set inactive: true
+data/relation-budakeszierdo.yaml: set inactive: false
+data/relation-budaors-kertvaros.yaml: set inactive: false
+data/relation-budapest_05.yaml: set inactive: true
+data/relation-budapest_07.yaml: set inactive: true
+data/relation-budapest_08.yaml: set inactive: false
+data/relation-budapest_09.yaml: set inactive: false
+data/relation-budapest_16.yaml: set inactive: false
+data/relation-budapest_21.yaml: set inactive: false
+data/relation-domos.yaml: set inactive: true
+data/relation-gellerthegy.yaml: set inactive: true
+data/relation-gyula.yaml: set inactive: true
+data/relation-kamut.yaml: set inactive: true
+data/relation-keszthely.yaml: set inactive: true
+data/relation-mezobereny.yaml: set inactive: true
+data/relation-murony.yaml: set inactive: true
+data/relation-nemesgulacs.yaml: set inactive: true
+data/relation-orszagut.yaml: set inactive: true
+data/relation-pilisvorosvar.yaml: set inactive: true
 data/relation-sasad.yaml: set inactive: true
-data/relation-szentantalfa.yaml: set inactive: false
-data/relation-zanka.yaml: set inactive: false
-Suggested 2 removals and 3 additions.
+data/relation-szekszard.yaml: set inactive: false
+data/relation-torokbalint.yaml: set inactive: false
+data/relation-ujlak.yaml: set inactive: false
+data/relation-varosliget.yaml: set inactive: false
+data/relation-veresegyhaz.yaml: set inactive: true
+Suggested 19 removals and 11 additions.
````

Augusztusi adatokkal. Nekem az jön le, hogy volt egy csomó reláció amit ember nem látogatott, de nem esett ki az aktívból, mert a botok látogatták. Teszteld még ha akarod, vagy le lehet zárni.

**Comment by vasony** [comment]
ha ki is dumpolná a workdirbe a listát ami alapján dolgozi, akkor milyen jó lenne :)
egyébként zárható

**Comment by vmiklos** [comment]
Mire gondolsz, 2 oszlop, első be a reláció neve, másodikba pedig, hogy hány látogatás volt?

**Comment by vasony** [comment]
Igen pont ez.
Van ott a programkód végefele valami változó (tömb, lista nem tudom mi) amit csak ki kellett printelni, de már nem emlékszem.

**Comment by vmiklos** [comment]
workdir/frequent-relations.csv alá írja ki.
