### ISSUE TITLE
robots.txt update-result

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#617]
Nem tudom mennyire jó ötlet, hogy a keresőrobotok hívásai frissítik az állományokat meghívva az update-result oldalt...
robots.txt-ben ki lehetne őket erről a részről tiltani

valami ilyesmi
```
User-agent: *
Disallow: /*update-result$
```

**Comment by vasony** [comment]
http://osm.vasony.hu/robots.txt
Nálam most ez van:
```
User-agent: *
Disallow: /*update-result$
Disallow: /filter-for
Disallow: /*view-turbo$
Disallow: /*.txt$
Disallow: /*.chkl$
```

**Comment by vmiklos** [comment]
Jó az ami nálad van, átvettem egy az egyben:

https://osm-gimmisn.vmiklos.hu/robots.txt

**Comment by vasony** [comment]
ezt csak te tudod tesztelni :-)

**Comment by vmiklos** [comment]
https://technicalseo.com/tools/robots-txt/

https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_12/view-result ok
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/budapest_12/update-result ko

Egyelőre jónak tűnik
