### ISSUE TITLE
Range szintű reftelepülés kezelése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#63]
Ha az utca egyik oldala egyik kerület, a másik a másik kerületben, és mindkettő oldal ugyabannan a városrészben van, akkor a mostani struktúrában nem kezelhető. 

Pl. Krisztinaváros: Alkotás utca, Márvány utca, vagy Víziváros: Csalogány utca, Újlak: Kolosy tér, Szépvölgyi út

Megoldás a range szintre betenni a reftelepules-t, opcionálisan.
pl:

alkotas_utca
ranges:
- {start: '1', end: '37, retelepules:"012'}
- {start: '2', end: '32, retelepules:"001'}

**Comment by vmiklos** [comment]
És akkor ebben az esetben a referenciában mindkettővel keresünk és a kettő uniója az amihez viszonyítjuk az OSM db-t, jól gondolom?

**Comment by vasony** [comment]
Igen, a suspicious/view-query-ben adott utcára mindkettő uniója lesz.

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-streets/krisztinavaros/view-result itt most az Alkotás utcán vannak páros és páratlan házszámok is, jónak tűnik.
