### ISSUE TITLE
Hiányzó házszámok oldal, különböző adat kimenetek

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#64]
Most hogy a grafikus rész a #55 -ben megoldódott, szükség lehet a nyers adatokra is további feldolgozásra.
Nekem pl. az 1) az ideális.

Példák, az url csak minta, nem tudom mik a paraméterátadás lehetőségei

1.  https://vmiklos.pythonanywhere.com/osm/suspicious-streets/posingermajor/view-result/txt 
(order by street)
Kossuth Lajos utca<tab>[1, 2, 3]
Móricz Zsigmond utca<tab>[1, 2, 3, 4, 5]

2.  https://vmiklos.pythonanywhere.com/osm/suspicious-streets/posingermajor/view-result/full-txt 
Régi formátum (order by count(mising) desc)
Móricz Zsigmond utca 5
[1, 2, 3, 4, 5]
Kossuth Lajos utca 3
[1, 2, 3]

3.  https://vmiklos.pythonanywhere.com/osm/suspicious-streets/posingermajor/view-result/json
[{
   street: "Móricz Zsigmond utca",
   count: 5,
   numbers: [1, 2, 3, 4, 5]
},
{
   street: "Kossuth Lajos utca",
   count: 3,
   numbers: [1, 2, 3]
}
]a darabszám duplikált infó, mert a tömb megszámolható, de elfér

**Comment by vmiklos** [comment]
Egyelőre linkelem a menüből; ha ez túl sok hirdetés ennek, akkor esetleg át lehet rakni csak egy utalást erre a doc/hu/ alá és kiszedni a menüből.

**Comment by vasony** [comment]
Jó ez így szerintem. Egy tabot tegyél még be légyszi a [ elé.

**Comment by vmiklos** [comment]
^ Kész.
