### ISSUE TITLE
Rendezés magyar ABC betűi alapján

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#68]
txt kimeneten angol szerint rendez, nem magyar szerint

helytelen sorrend:
Budaörsi út	[44, 48, 50, 54, 56, 58, 60]
Bukarest utca	[5, 6, 7, 9, 14]
Bánk bán utca	[5, 6, 14, 16, 18]

helyesen
Bánk bán utca	[5, 6, 14, 16, 18]
...
Budaörsi út	[44, 48, 50, 54, 56, 58, 60]
Bukarest utca	[5, 6, 7, 9, 14]

Megoldás:
https://stackoverflow.com/questions/1097908/how-do-i-sort-unicode-strings-alphabetically-in-python/1318709#1318709

**Comment by vmiklos** [comment]
Köszi, a megoldás első fele tényleg ez volt. Úgy tűnik elég a unicode sort nekünk, nem kell kifejezetten magyar:

https://vmiklos.pythonanywhere.com/osm/suspicious-streets/kelenfold/view-result.txt

**Comment by vasony** [comment]
majdnem jó
tudom ez már majdnem marginális, de , o=ó, de o !=ö rendezésnél, ha a locale-bel meg lehet oldani, akkor menjen, ha nem, akkor elengedem:

excelben ez jön
K**o**vászna utca	[16, 54]
K**ö**körcsin utca	[12, 17]
K**ö**nyves György utca	[3, 4]

pythonban
K**o**csis utca	[4, 6, 14, 16, 17, 19, 20, 21, 23, 24, 25, 27, 28, 29, 30, 31, 46, 52]
K**ö**körcsin utca	[12, 17]
K**o**ndorfa utca	[1, 5, 15, 18, 19, 80]

**Comment by vmiklos** [comment]
Nem, ez jogos.

**Comment by vmiklos** [comment]
Elvileg jó lett.

**Comment by vasony** [comment]
Igen, most jó.
