### ISSUE TITLE
Fejléc átalakítása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#688]
Szerintem a további utcákat is be kellene tenni a fejlécbe, illetve Statisztikák | Dokumentáció az nem szükséges az aloldalakra, mert nem kapcsolódik területhez.

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
Ez a része jó, viszont nem egységes a fejléc.
Az overpass turbo csak bizonyos dolgoknál jelenik meg. Nem tudom ez direkt van-e.

**Comment by vmiklos** [comment]
Írsz egy példát, hogy melyik oldalon melyik linket hiányolod? Van egy pár... :)

**Comment by vasony** [comment]
További hazátlanoktól hátrafelé a menuben az ovepass. Kattintgasd sorban es nem szabad változnia a fejlécnek

**Comment by vmiklos** [comment]
Ja látom. Igen, volt egy feltétel rá, hogy csak a missing-* oldalakon mutassa, de igazából lehet mindig, annyival egyszerűbb a kód. És mivel kiszórtunk másik kettőt, van rá hely.

**Comment by vmiklos** [comment]
Lehet tesztelni.
