### ISSUE TITLE
Főoldal: További utcák

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#689]
További utcák felirat helyett a darabszámot kellene listázni a területek melletet, mivel százalékot nem tudunk.
Ez informatívabb mint mindenhova a "további utcák" feliratot betenni, és már egyből látszik, hogy kell-e kezdeni valamit vele.

Meglévő utcák és meglévő házszámokat fegyelőre nem bántanám, ott nincs jelentősége hogy 22 vagy 48 utca van egy településen.

**Comment by vmiklos** [comment]
Ennek is lesz több része:

- kell egy olyan funkció, hogyha kiszámoljuk a további utcákat, akkor mentsük el a találatok számát
- kell az, hogy a főoldal ezt mutassa, ha van
- cronjob generálja ezeket az adatokat

Ez mind már megy a hiányzó utcákra, tehát ahhoz hasonlóan.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
nem kéne valami mértékegység a szám mögé? db vagy utca?

**Comment by vmiklos** [comment]
Legyen utca/utcák.

**Comment by vasony** [comment]
akkor "23 utca", mert a "23 utcák" csak angolul értelmes :)

**Comment by vmiklos** [comment]
Igen, utca / streets lett.

**Comment by vasony** [comment]
Az angol nem jó: 1 streets ha nyelévszkedni akarunk. ha nem akkor zárható.

**Comment by vmiklos** [comment]
Igen, ez bennem is felmerült, de annyira ritka, hogy egyelőre nem izgat :)
