### ISSUE TITLE
Filter saját pozició alapján

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#690]
Ez egy nagyobb falat, ha egyáltalán meg tudjuk csinálni, mobilról érdekes főként.

https://stackoverflow.com/questions/47067097/python-3-3-5-get-my-current-locations-lat-and-long

1) Külön szűrő: "Sajáz pozició"
2) Rákattintva engedélyt kér a browser, a saját poziciót megszerzi lat, lon
3) Overpassból megszerzi a megfelelő relációkat adott pozición: az osm felület meg tudja tenni, akkor mi is
4) Lefilterezi a listát azokra amik egyeznek a fenti listából

**Comment by vmiklos** [comment]
A helyzet gondolom megoldható javascripttel, elsőnek annak kéne utánanézni, hogy overpassból hogyan lehetne lekérni azokat a relációkat amik egy adott pontot tartalmaznak. Valahogy biztos megoldható, mert ha osm.orgon rákeresek, hogy "Mészáros utca, Budapest" akkor a találatok adnak valamiféle infót arról, hogy mik ezek a relációk. Az már nem biztos, hogy ez overpassból megoldható.

Ha ez megvan, a többi kevésbé tűnik vészesnek.

**Comment by vasony** [comment]
azt megy az osm

> A helyzet gondolom megoldható javascripttel, elsőnek annak kéne utánanézni, hogy overpassból hogyan lehetne lekérni azokat a relációkat amik egy adott pontot tartalmaznak.

A openstreetmap.org is ezt csinálja, jobb gomb funkciók lekérdezése, rel(pivot); de még eljátszom vele

**Comment by vasony** [comment]
Még meg kell valahogy szűrni
```
[out:csv(::id, "name","admin_level", "boundary", ::type)]  [timeout:425];
is_in(47.46,19.00);
(._;>;);
out meta;
```

**Comment by vmiklos** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/longitude ez mobilon működőképesnek tűnik a koordináták eléréséhez

Az overpass is jó lesz:

```
[out:json]  [timeout:425];
is_in(47.4766726,19.003091);
(._;>;);
out meta;
```

Utána meg ebből ki kell mazsolázni azokat a relációkat amiket mi ismerünk. Valami ilyesmi:

```
>>> osm_relations = [i.get_config().get_osmrelation() + 3600000000 for i in relations.get_relations()]
>>> [(i["id"], i["tags"]["name"]) for i in j["elements"] if i["id"] in osm_relations]
[(3600221998, 'XI. kerület'), (3602714372, 'Sasad')]
````

A kettőt összerakva már lehet valami ilyesmit hívni, hogy `/filter-for/relations/3600221998,3602714372` JS-ből, ami adja a szokásos leszűkített reláció listát.

**Comment by vmiklos** [comment]
hevenyészett terv:

1. kell egy json endpoint, ami kiadja, hogy milyen relációkat kezelünk (id lista)
2. kell egy /filter-for változat, ami adott relációkra szűr
3. kell a JS rész ami ezt a kettőt használja, és koordináta alapján kéri a releváns és ismert relációkat

**Comment by vmiklos** [comment]
Ebből most az első 2 megvan, a JS még hiányzik.

**Comment by vmiklos** [comment]
Ez alapvetően működik nekem, a fenti koordinátákra szépen leszűkül a lista budapest_11 és sasadra. Lokalizáció hiányzik még.

**Comment by vasony** [comment]
Nálam: Error from GPS: [object GeolocationPositionError]

**Comment by vmiklos** [comment]
Mobilon próbáltad? Desktopon nekem is csak akkor megy ha a Chrome-nak megadom kézzel a koordinataimat: https://www.comparitech.com/blog/vpn-privacy/change-location-chrome-firefox-spoof/

Úgy tűnik ez más oldalon is így van (pl domcsi kutyasetaltatos oldala), szóval gondolom ez ilyen.

**Comment by vasony** [comment]
Chrome sem már.
Jó buli lesz átrakni https-re. Egyébként én az első helyre tenném a szűrőt.

**Comment by vmiklos** [comment]
A szűrőt előre raktam meg egy (amúgy ártalmatlan) js hibát is javítottam, lokalizáció még mindig TODO.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
Alapvetően jó, még ki akarom próbálni másik körzetekben mint a 11. kerület.

**Comment by vasony** [comment]
Egy csomó helyen néztem, mindenhol jó volt.
