### ISSUE TITLE
Házszám és helyrajzi szám nélküli pontokat ne vegyük figyelembe a hiányzó házszámoknál

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#754]
https://osm.vasony.hu/missing-housenumbers/huvosvolgy/view-result

Rezeda utca területen kívüli, de mivel van rajta addr: pont ezért behúzza a referencia közé

overpasst nem akarom átírni, mert nem baj ha látszanak a csonka címek, viszont a betöltésnél kellene szűrni

**Comment by vmiklos** [comment]
Igen, ez jogos, az utca-lista generáláskor mikor egyáltalán felmerült, hogy a házszámokat is nézze, nem merült fel, hogy az üres is lehet.

Lehet tesztelni:

https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/huvosvolgy/view-result

**Comment by vasony** [comment]
jó lesz

**Comment by vasony** [comment]
Kiesett pár csontváz :)
Lett egy pár hiányzó utca, ahol csak házszám nélküli pontként voltak. Nem is baj.

**Comment by vasony** [comment]
Bocs, hogy újranyitom, de annyi módosítást szeretnék, kérni ha van addr:conscriptionnumber, akkor mégis kerüljön be.
https://osm.vasony.hu/missing-streets/szentantalfa/view-result

**Comment by vmiklos** [comment]
Nem teljesen értem, részleteznéd, hogy mi a mostani viselkedés a szentantalfa esetén és mit szeretnél helyette kimenetnek? Magát a kérést értem, de hogy ennek a Barcfa dűlőnek hol kéne megjelennie, azt nem.

**Comment by vmiklos** [comment]
Mindegy, közben csináltam egy teszt relációt amiben van ilyen "házszám nincs, de van helyrajzi szám" node, azzal tudok tesztelni. :-)

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
látod, mégis érted :-D el kellett tűnnie a Barfca dűlőnek, a hiányzó utcákból, ez jó, volt még 1 terület azt megnézem,

**Comment by vasony** [comment]
helyreállt a rend.
