### ISSUE TITLE
kész területek elrejtése helyett mutatása

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#759]
Ahogy egyre több 100% terület lesz, célszerű lenne megfordítani a funkciót, hogy alapból nem látszanának a 100%-os területek.
És a gomb engedélyezné vissza a főoldalon. 

Kérdés, hogy a további utcák = 0 is legyen-e feltétel, ha igen, akkor ez már egy másik issue.

**Comment by vmiklos** [comment]
Jó ötletnek tűnik.

**Comment by vmiklos** [comment]
Egyelőre legyen csak csere a UI-on, a filter-for/incomplete most nem vizsgál az additional-streets oszlopra, ez marad így.

**Comment by vmiklos** [comment]
Ezt is lehet tesztelni.

**Comment by vasony** [comment]
Nem látszanak azok, amiknél az utca 100%, de a másik nem.
Pl. Zánka

**Comment by vmiklos** [comment]
Igen, ezt én is észrevettem. Valszeg eddig is így volt, csak most jobban látszik. :) Megnézem...

**Comment by vmiklos** [comment]
Teszteléshez: budapest_12 pl újra látszódik a főoldalon, de balatoncsicso az továbbra se.

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
ok
