### ISSUE TITLE
frissítés overpass hívásával redirect

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#765]
- ha a további utcákon frissítést nyomok, akkor a hiányzó házszám oldalra ugrik, ne ugorjon, hanem önmagát frissítse
- ha a hiányzó utcákon frissítést nyomok, akkor kiírja hogy frissítve, nem ugrik sehova, itt is frissítse magát

**Comment by vmiklos** [comment]
Igen, mert mikor a redirect történik, már nincs meg, hogy honnan jöttél. Talán az lehetne megoldás, hogy js frissít, és mikor az adat már frissült, utána csak reload.

**Comment by vmiklos** [comment]
Ez több lépésre bontható:

1) A 3 esetben mikor a missing-housenumbers oldalon valami hiányzik (osm utcalista, osm házszámok, ref házszámok), akkor a mostanival szemben úgy frissüljön, hogy nem hagyjuk el az oldalt.

2) additional-streets u.így

3) missing-streets u.így

**Comment by vmiklos** [comment]
Az elsőhöz kell 3 új json endpoint, hogy azokat tudja hívogatni a JS, ez az első.

**Comment by vasony** [comment]
Azért még arra gondoljunk, hogy egy új területnél végig tudjon menni automatikusan.

**Comment by vmiklos** [comment]
Igen, sztem ez fog menni először :)

**Comment by vmiklos** [comment]
Ez a fenti változtatás az elején vázolt 1. lépésből is csak egyet alakít át, utána jön majd még a többi is.

**Comment by vmiklos** [comment]
Az elején lévő hárompontos terv első része megvan, pl itt: https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/sasad/view-result

Ezek mennek:

- ha új a reláció és hiányozna az osm utca, osm házszám vagy ref házszám lista, azokat JS-sel behúzza + reload
- az Update from OSM link is JS-sel húzza be az új osm házszám listát + reload

A lényeg, hogy így sose hagyjuk el az eredeti URL-t, így a végén nem köthetünk ki rossz helyen.

A második és harmadik pont még hiányzik.

**Comment by vmiklos** [comment]
A fenti hármas listából most már a missing streets is közel kész, még /missing-streets/.../update-result.json-t kell használni.

**Comment by vmiklos** [comment]
Azt hiszem most már mindenhol megmaradunk az eredeti oldalon, így nem tud félremenni vagy hiányozni a redirect. Spinner legyen a "..." után? Ezt eddig adta a browser ingyen...

**Comment by vasony** [comment]
Pörgőforgó? Ha nem túl bonyolult. Fapad |/- \ vagy valami más?

**Comment by vasony** [comment]
Valami kell, mert nem látszik a frissítés. 
A hiányzó házszámoknál látszik a várakozás overpass ...
A másik kettőnél nem látszik semmi a kattintás után.

**Comment by vmiklos** [comment]
De, mindennek mennie kéne, a pörgőt leszámítva. Írsz konkrét lépéseket, hogy mi nem megy?

https://codepen.io/rramphal/pen/gpjXNy pörgőre ilyet találtam ami egyszerű és inline is megy (nem töri 3 sorba a toolbart), majd berakom.

**Comment by vmiklos** [comment]
> a meglévő házszámok, meglévő utcák még nem JS-el megy, igaz?

most már azon a 2 oldalon is JS-sel megy az overpass. lehet tesztelni
