### ISSUE TITLE
Hibás OSM ID a hozzá tartozó objektumhoz a további utcák listájában

### ISSUE THREAD

**Issue by urbalazs** [vmiklos/osm-gimmisn#782]
[Ebben a listában](https://osm-gimmisn.vmiklos.hu/osm/additional-streets/budapest_12/view-result) a Városmajorhoz listázott OSM ID teljesen más objektumra mutat. A listában `way` szerepel `relation` helyett.

Ide mutat: https://www.openstreetmap.org/way/7264483
Ez lenne a helyes: https://www.openstreetmap.org/relation/7264483

**Comment by vmiklos** [comment]
Jogos

**Comment by vmiklos** [comment]
Javítottam.
