### ISSUE TITLE
mapping ellenőrzés (street-filters)

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#784]
Célja az időközben teljesen vagy résznem megváltozott utcanevek jobb követéséhez.

```  'Tomori utca': 'Tomori Pál utca'```

Amikor frissül napi 1x a cucc akkor, ellenőrizni kellene
-- osm-name létezik-e az összegyűjtött osm utcalistában, ha nem -> hiba
-- a ref-name létezik-e az összegyűjtött osm utcalistában, ha igen -> hiba

Ha van hiba, akkor valahova tegye le a hibás nevű utcákat, mind a 2 nevet

a) Jelölje pirossal az utcanévben az alábbiakban
- a hiányzó házszám listán
- a további utcák listán

b) ha az a) nem szimpatikus, akkor lehet warning a hiányzó házszámos lista oldal tetején/alján

Tesztelhető  ezzel az állapottal:
https://github.com/vmiklos/osm-gimmisn/commit/9a676ae9b386198423b5afb98460a4aa12b3365

**Comment by vmiklos** [comment]
Kicsit általánosítva ha jól értem azt akarjuk, hogy az osm név akkor és csak akkor valid ha létezik az osm utcalistában, és u.az a ref névre is a ref utcalistával. Szóval ez összesen 4 eset: osm/ref és név létezik/listában létezik.

Talán az tetszene a legjobban ha az összes ilyen hibát egyetlen oldalra ki lehetne gyűjteni, hiszen vélhetőleg nincs belőlük túl sok, és minden relációt végigkattingatni egyesével unalmas.

**Comment by vasony** [comment]
Az külön oldal pluszban jó ötlet, hogy legyen 1 helyen, de nem elég, lejjebb kifejtem

Nem 4 eset, vagy én nem értem mi a 4 eset :)
A REF nevet is az OSM listában kell megnézni, mert hibás a mapping ha a REF név már létezik osm-ben és átmappeljük egy  másikra.  Persze ettől a saját listás ellenőrzések is kellenek.

Tipikus esetek:
-  átnevezik az utcát osm-ben, és a házszámokat is
-  átnevezik az utcát osm-ben, de a házszámokat meg nem, így duplán van minden utca

Ez utóbbi miatt nem ártana jelezni adott oldalon is hogy valami nem stimmel, mert akkor így néz ki a hiányzó házszám oldal:
(mapping: Petőfi utca: Petőfi Sándor utca)
- Petőfi utca 1 2 3
- Petőfi Sándor utca 1 2 3 4 5 6 7 8 9 10

**Comment by vmiklos** [comment]
data/relation-szigetmonostor.yaml-ba pl lehet rakni egy ilyet, hogy 'Muskátli út': 'Muskátli utca', az egyből 2 warning (utca van, út nincs, és ebben az osm meg a ref egyetért).

**Comment by vmiklos** [comment]
Ilyet talált pl:

https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/esztergom-kozpont/view-result

Warning: broken OSM <-> reference mapping, the following OSM names are invalid:

- Mindszenty tér

Warning: broken OSM <-> reference mapping, the following reference names are invalid:

- Mindszenty hercegprímás tér

Még az kérdés, hogy ezeket most röptében számolja, tehát nincs szükség cronra. Mit csináljon a cron, szeretnél kapni egy listát azokról a relációkról amikben valamelyik lista nem üres? Esetleg egy json ahol a kulcs a reláció neve, az érték pedig a két lista, ha valamelyik nem üres?

**Comment by vasony** [comment]
Szerintem egyelőre jó ez így, nem kell külön lista.
A Mindszenty tér miért invalid? Létezik az osm-ben, a másik fele jogos.

**Comment by vasony** [comment]
ja ezért: " Utolsó frissítés: 2021-01-01 00:59", most frissítettem, és már nem hibás, csak az egyik fele.

**Comment by vasony** [comment]
>     * Mindszenty hercegprímás tér

Nálam így van a ref-ben, kár volt elrontanom. Visszaírom, nézzük meg megint.

**Comment by vasony** [comment]
rendben.
