### ISSUE TITLE
Hiányzó utcák osm és ref közti mappelése és társai

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#79]
#43 kapcsán

1) Az utca mappelést meg kell oldani, hogy visszafele is menjen most ugye a refstreets a másik irány tartalmazza. Ez vidéken érdekes, ahol 1 relation mindkét irányba dolgozik.
pl: Október Huszonharmad utca > Október huszonharmadika utca
Jó lenne ha nem kellene 2x, de lehet muszáj lesz, mert lehet, hogy több ref is ugyanarra az osm írásmódra mutat, és a 2)-es pontot is kezelni kell.

2) kiszűrés, most nincs példa, de kiderül, hogy nincs a valóságban az utca.
ugyanezzel megoldható, ha a value-ban üres értéket vagy null-t adunk, nem tudom mi a szintaxis yaml-ban.
pl: Kukutyin utca:null vagy -

**Comment by vasony** [comment]
most látom a relation-ujbuda-ban hogy kellene mennie akkor visszafele is? akkor csak a 2. pontot kell megoldani?

**Comment by vasony** [comment]
1. pipa
2.-ra példa

Alsóhegyi lépcső (csak házszám van, nem találtam meg az utcát hozzá), el akarom nyomni.
Alsóhatár utca - ez egy határon lévő utca, rossz oldalon van az utca

A közös, hogy házszám szinten léteznek, utca szinten adott relation-ben nem.
Megoldás
1) Vagy házszámokból is hozzávesszük az utcákat (overpass?)
2) Egyesével elnyomjuk

**Comment by vmiklos** [comment]
Szerintem erre is lehetne szűrő, a meglévő `filters` mellé egy új `street-filter` pl, aminek egy utcalistát lehet megadni, ami tudjunk, hogy nincs az OSM-ben, de nem is bánjuk.

**Comment by vasony** [comment]
Akkor legyen filter, aztán meglátjuk mennyi van. De akkor legyen többesszámban mint a többi. `street-filters`.

**Comment by vmiklos** [comment]
OK, tetszik a `street-filters`. Elnevezésben nem vagyok jó. :-)

**Comment by vasony** [comment]
Felvettem az ujbudába, nem tudom így gondoltad-e, lehet majd tesztelni

**Comment by vmiklos** [comment]
Jónak tűnik, köszi.

**Comment by vmiklos** [comment]
Hrm, űgy tűnt, hogy a Talaj köz eltűnt, de nem. Még kutatok. :-)

**Comment by vmiklos** [comment]
bcc07ac ha a sor végére teszel `# foo` formában commentet yamlban akkor fontos a # előtt a space

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-relations/ujbuda/view-result így már nincs Talaj köz itt (meg a többi amit kiszűrtél configban).

**Comment by vasony** [comment]
eredetileg volt space, csak szólt a validátor, hogy szedjem ki :-O

**Comment by vmiklos** [comment]
Azt hiszem az a szándék, hogy a megjegyzés vagy a saját sorában legyen (tipikusan előtte) vagy >= 2 space legyen a # előtt. Ez gondolom a python hagyományokból jön, ott van ez a mánia, hogy 1 space az csúnyának számít a # előtt.
