### ISSUE TITLE
további utcák: id nélküli utcák

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#830]
azokhoz a további utcákhoz, amikhez most nincs id, mert házszámból jöttek, kellene valamelyik házszámnak az id-je, hogy könnyebb legyen debuggolni.

pl:

https://osm.vasony.hu/additional-streets/budapest_11/view-result
  | Allee Bevásárlóközpont, Október 23. u.

**Comment by vmiklos** [comment]
Igen, ennek volna értelme. Ráadásul már most is megy, hogy az objektum lehet relation vagy way, szóval a node nem bonyolítja sokkal a kódot.

**Comment by vasony** [comment]
Valahogy majd különböztessük meg, hogy melyik jön pontból és melyik utcából.
Pl. link nevében legyen benne vmi betű ha nem utcából jön az utcanév, hanem címpontból, pl: x1234567, vagy n1234567

**Comment by vmiklos** [comment]
Vagy egy type oszlop, az kicsit könnyebben érthető

**Comment by vasony** [comment]
Álmodni se akartam új oszlopot :)

**Comment by vmiklos** [comment]
Az Allee példa azóta eltűnt, de pl a budapest_10 alatt még van ilyen, az Ifjúmunkás utca.

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/additional-streets/budapest_10/view-result

Lehet tesztelni, van itt olyan "utca" is ami node-ból jön.

**Comment by vasony** [comment]
azon goldolkozom, hogy van-e értelme még megkülönböztetni, hogy highway name vagy addr:street-ből jön-e az érték, mert way típus az lehet épület is.
egyébként működik.

**Comment by vasony** [comment]
pontossabban nem gondolkozom, mert ez volt a plusz kérés "melyik jön pontból és melyik utcából.". nem pedig a típusa, persze az is hasznos.

**Comment by vmiklos** [comment]
Megoldható

**Comment by vmiklos** [comment]
Lett új oszlop.

**Comment by vasony** [comment]
Szuper!
Egyből egy szép találat, a 10. kerületben egy 9. kerületi cím.
https://www.openstreetmap.org/way/228345166#map=15/47.4717/19.1341
