### ISSUE TITLE
Rendezés magyar ABC a hiányzó utcákra is

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#85]
#68-hoz hasonlóan a hiányzó házszám oldalra is magyar sort kellene.

**Comment by vmiklos** [comment]
Jogos. ujbuda hiányzó utcalistáján jól látszik a gond. Amúgy most látom, hogy explicit erőfeszítés nélkül megy településre a hiányzó házszám és hiányzó utca egyszerre, cool!

Mindenütt csak != only és != no check-ek vannak, szóval logikus, hogy a yes azt csinálja amire számítasz, de általában szokott lenni valami amin az ilyen mégis elbukik. :-)

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-relations/ujbuda/view-result jónak tűnik most már
