### ISSUE TITLE
Rendezés magyar ABC a sorttable-be

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#86]
sorttable.js felokosítása, hogy tudjon magyar ABC-t is.

**Comment by vmiklos** [comment]
Tudsz írni egy példát ahol az előjön? Illetve van kedved megnézni a problémát tüzetesebben?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

Lehet ezt kéne használni, nem mélyedtem el a témában.

**Comment by vmiklos** [comment]
Ja semmi, látom biatorbagy erre is reproducer.

**Comment by vasony** [comment]
egyelőre csak felvettem ide, még nem tudom értek-e hozzá ennyire :)

**Comment by vmiklos** [comment]
Ez alapvetően működik, majd még írok a sorttable csávónak hátha beveszi a patchet.

**Comment by vasony** [comment]
Látom azért ezzel elég egyszerű volt a fix.
Azt nem tudtam reprodukáni, hogy  c cs jól megy e., mert nem volt rá példa, de szerintem az se nagy érvágás ha nem.

**Comment by vmiklos** [comment]
Tekintve, hogy server oldalon alapból nem volt jó, lehet, hogy itt se lesz az. Esetleg böngésző nyelvétől függ, és akkor nálam angol UI-on rossz, de másnál meg lehet, hogy jó. De a mozillás wiki alapján a localeCompare() paraméterei már közel sem egységesek, X böngészővel meg nincs sok kedvem tesztelni, így egyelőre marad így. :-)

**Comment by vasony** [comment]
nekem megy az a légyeg :))
