### ISSUE TITLE
További utcák: overpass query készítése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#861]
Ehhez hasonló kellene:
"Overpass lekérdezés a lenti utcákra."
https://osm.vasony.hu/missing-housenumbers/budapest_21/view-turbo

Mivel az id-k megvannak, ezért csak össze kell rakni ezt:
#830 után, mert a node-ok is kellenek, viszont ha 1 utca többször van, akkor az összes id-t listázni kell.
```
[out:json][timeout:425];
(
way(279951290);
way(192077821);
way(145946556);
way(319896666);
way(254462282);
way(763830282);
node(2330620711);
);
out body;
>;
out skel qt;
```

**Comment by vmiklos** [comment]
Meg akkor már a missing streets oldalra is lehetne egy ilyen, hogy egységes legyen.

**Comment by vasony** [comment]
> Meg akkor már a missing streets oldalra is lehetne egy ilyen, hogy egységes legyen.

Lehetne, de épp azért missing mert nincs meg osm-ben :)

**Comment by vasony** [comment]
Illetve ott már van overpass, de nem a hiányzókra, hanem a street-mapping részre.

**Comment by vmiklos** [comment]
Ja jogos, egy string listán nehéz mit térképre vinni.

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
> ha 1 utca többször van, akkor az összes id-t listázni kell.

ez még nem teljesül.
pl:
https://osm.vasony.hu/additional-streets/budapest_02/view-turbo

"Közép út"-ra csak 1 id jön vissza: `way(127306357);`

Közben:
https://osm.vasony.hu/streets/budapest_02/view-result


127306357 | Közép út | track |   |   |   | way
-- | -- | -- | -- | -- | -- | --
127306358 | Közép út | track |   |   |   | way
127306359 | Közép út | track |   |   |   | way
198509861 | Közép út | track |   |   |   | way
295191281 | Közép út | track |   |   |   | way

**Comment by vmiklos** [comment]
Ja látom, egyszer akarunk név szerinti duplikatum szűrést, másszor meg nem. Most?

**Comment by vasony** [comment]
Ez már csak ilyen bicikli, a térképen mindent akarok látni, mert ott áttekinthető, a táblázatban is lehetne, de ott sok lenne a zaj, azért maradt ki.
Jó lesz.
