### ISSUE TITLE
UI: txt, chkl egységesítés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#875]
Arra gondoltam ,hogy a fejlécből kiszednénk a txt és chkl opciókat és szövegként jelenne meg az adott oldalon, az overpass query alatt valami hosszabb szöveggel, akkor talán mobilról se fogom állandóan félrenyomni.
Ezzel egyidejűleg a missing-streets is kapna chkl, és az additional streets is kapna txt, chkl opciókat.

**Comment by vmiklos** [comment]
Lehet róla szó.

**Comment by vmiklos** [comment]
Részfeladatok:

1. fejlécből kiszedés
2. missing-streetsnek chkl
3. additional streetsnek txt
4. additional-streetsnek chkl

**Comment by vmiklos** [comment]
Elvileg elkészült a mű

**Comment by vasony** [comment]
Jó lett.
