### ISSUE TITLE
Street ref - "null" kiszedése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#88]
Rosszul generáltam a street ref file-t, nem replace-eltem ki a null-okat azoknál ahol nincs közterület jelleg. (a házszámoknál figyeltem erre, itt lemaradt)

vagy a file-ból kell kiszedni vagy a feldogozás során

https://vmiklos.pythonanywhere.com/osm/suspicious-relations/biatorbagy/view-query

"Alsómajor null" helyet "Alsómajor" kell

**Comment by vmiklos** [comment]
Jogos.

Nem volt ez sehol eddig leírva, szóval azért írom ide: a bug/enhancement labeleket azért tettem a bugokra, hogy valahogy követve legyen az új issue és az "olvastam, előbb-utóbb én vagy más jó ha megcsinálja" közötti állapot, ebből a szempontból nem hasznos ha te ráteszed. :-)

De akkor legyen ez explicit, teszek rá egy `confirmed` címkét, a bug/enhancement meg végül is maradhat, az jelzi azt, hogy valami nagyobb falatról van-e szó vagy csak egy egyszerűbbnek vélt javításról.

**Comment by vasony** [comment]
nem ragaszkodom hozza hogy rategyem. :)

**Comment by vmiklos** [comment]
https://vmiklos.pythonanywhere.com/osm/suspicious-relations/biatorbagy/view-query most már jónak tűnik. A referencia beolvasását javítottam, szóval ha más relációnál is gondot okoz, akkor a referenciából be kell frissíteni: /osm/suspicious-relations/.../update-result link.
