### ISSUE TITLE
További utcák: utolsó frissítés dátuma

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#886]
https://osm.vasony.hu/additional-streets/budapest_12/view-result
A végéről hiányzik az "¦ Utolsó frissítés: 2021-01-01 03:37".

**Comment by vmiklos** [comment]
Jogos

**Comment by vmiklos** [comment]
Lehet tesztelni.

**Comment by vasony** [comment]
Határozottan ott van.
