### ISSUE TITLE
addr:place bekötése

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#964]
A házszámokat tartalmazó listához hozzá kell adni az addr:place_mezőt.
Ha nincs kitölve az addr:street, akkor innen vegye az utcanevet a hiányzó házszám megállapításhoz, és a hiányzó utcákhoz is.
Teszt terület Orgovány, Tolvajos tanya

**Comment by vmiklos** [comment]
https://www.openstreetmap.org/way/810328181 ezekről van szó, ha jól értem

**Comment by vasony** [comment]
pontosan

**Comment by vmiklos** [comment]
Jelenleg a workdir/street-housenumbers-....csv oszlopai be vannak drótozva, az 1, 2, 5, 11-es oszlopokat nézzük. Először ezt érdemes rendbetenni, hogy az oszlopok neveivel dolgozzon a kód, és akkor egy új oszlop felvétele nem túl bonyolult.

**Comment by vasony** [comment]
#973 #974

**Comment by vmiklos** [comment]
Az overpass template-ben csak a fejlécbe került bele az addr:place, a törzsből hiányzik ha jól látom.

**Comment by vmiklos** [comment]
Lehet tesztelni; egy unit teszt mutatja, hogy működik a dolog, de egy valós reláción is érdekes lehet kipróbálni.

**Comment by vasony** [comment]
> Az overpass template-ben csak a fejlécbe került bele az addr:place, a törzsből hiányzik ha jól látom.

nem is tudom ,hogy kell-e egyáltalán ez a sok sor, ha csak az addr:place vagy addr:door van kitöltve úgyse érdekes, lehet ki lehetne pucolni, akkor gyorsabb lenne a cron.

**Comment by vasony** [comment]
nos megnéztem pár területet, leegyszerűsítem a template-et

**Comment by vasony** [comment]
úgy tűnik a hiányzó házszámoknál nem veszi figyelembe.

Orgovány, Felsőjárás tanya házszámok szerepelnek, de hiányzó házszámnak kijön.
pl:


Utcanév | Hiányzik db | Házszámok
-- | -- | --
Felsőjárás tanya | 155 | 3,  5, 7, 11, 13, 15, 19, 33, 39, 43, 45, 53, 57, 59, 61, 65, 69, 79, 81,  97, 103, 107, 109, 113, 119, 121, 123, 125, 129, 133, 135, 137, 139,  143, 145, 147, 149, 151, 155, 157, 159, 163, 165, 169, **173**, 177, 179,  181, 197, 199, 201, 205, 213, 215, 217, 221, 227, 231, 235, 237, 239,  241, 243, 245, 247, 249, 251, 253, 255, 257, 261/A, 263, 265, 267, 2692,  4, 6, 8, 12, 22, 24, 26, 32, 42, 46, 48, 54, 56, 60, 62, 66, 70, 72,  76, 82, 88, 92, 94, 98, 102, 104, 106, 118, 120, 122, 124, 126, 132,  134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 168, 174, **178**,  182, **184**, 192, 198, **200**, 202, 204, 206, 208, 210, 212, 214, 218, 220,  224, 228, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,  258, 262, 264, 266

addr:street - ez jó


@id | addr:street | addr:housenumber | addr:postcode | addr:place
-- | -- | -- | -- | --
3514938165 | Felsőjárás tanya | 219 | 6077|

addr:place - nem jó
@id | addr:street | addr:housenumber | addr:postcode | addr:place
-- | -- | -- | -- | --
395995966 |   | 173 | 6077 | Felsőjárás tanya |
395995968 |   | 178 | 6077 | Felsőjárás tanya |
395995971 |   | 184 | 6077 | Felsőjárás tanya |
396000454 |   | 200 | 6077 | Felsőjárás tanya|

**Comment by vmiklos** [comment]
Ja ez érthető, a fenti commit csak azt érinti, hogy a házszámlistából hogyan nyerjük ki az utcaneveket, a hiányzó házszámhoz nem nyúltam. Majd megnézem.

**Comment by vmiklos** [comment]
Most már a házszám listának is kell kezelnie az addr:place-t, nem csak az utcalistának.

**Comment by vasony** [comment]
most jónak tűnik
