### ISSUE TITLE
További utcák: angol és magyar szöveg keveredik a magyar oldalon

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#978]
https://osm-gimmisn.vmiklos.hu/osm/additional-streets/balatonalmadi/view-result

**OpenStreetMap additionally has the below 42 streets.**
Egyszerű szöveg formátum
Csekklista formátum
Overpass lekérdezés a lenti utcákra

**Identifier** |**Type** | **Source** | Utcanév
-- | -- | -- | --

**Comment by vmiklos** [comment]
Megnézem majd, valszeg az új forrás file-t elfelejtettem felvenni fordításra.

**Comment by vmiklos** [comment]
Lehet tesztelni
