### ISSUE TITLE
Páros-Páratlan külön megjelenítése txt-ben is, plusz folyamatos házszámozású utcák

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#99]
1) Új property a folyamatos házszámozású utcákra, aminek elsősorban a megjelenítésnél van szerepel, másodsorban a range kezelésnél

filter:
```
  Hamzsabégi út:
    # folyamatos hazszamok
    ranges:
      - {start: '23', end: '63'}
      - {start: '22', end: '64'}
```
helyett

```
  Hamzsabégi út:
    interpolation: all
    ranges:
      - {start: '23', end: '64'}
```
2) txt-ben is kérem a páros páratlan szélválasztását, ha nincs interpolation: all

pl:
```
Alíz utca	[6]
Andor köz	[7][2, 4, 10]
```
'de
```
Hamzsabégi út	[29, 30, 31, 32, 33]
```

**Comment by vmiklos** [comment]
A 2. fele kész, bár picit más lett a formázás, hogy ne térjünk el attól ahogy a Python ki szokott írni 2 listát.

**Comment by vasony** [comment]
tökéletes így is.

**Comment by vmiklos** [comment]
Az 1-et kétfelé bontom: először legyen lehetőség a folyamatos számozás leírására, hiszen ez érinti azt is, hogy az 1-3 range az tartalmazza-e a 2-t vagy nem. Aztán a UI is megtanulhatja, hogy ne 2 listát csináljon folyamatos számozás esetén. A fenti commit az első rész.

**Comment by vmiklos** [comment]
Kész. :-)
